/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * com.trolltech.qt.multimedia Package
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsound.jsx"; // QSound
import "qt/qsoundeffect.jsx"; // QSoundEffect
