/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * com.trolltech.qt.svg Package
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsvggenerator.jsx"; // QSvgGenerator
import "qt/qsvgrenderer.jsx"; // QSvgRenderer
import "qt/qsvgwidget.jsx"; // QSvgWidget
