/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * com.trolltech.qt.webkit Package
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwebelement.jsx"; // QWebElement
import "qt/qwebhistoryinterface.jsx"; // QWebHistoryInterface
import "qt/qwebpluginfactory.jsx"; // QWebPluginFactory
import "qt/qwebpluginfactory_extensionoption.jsx"; // QWebPluginFactory_ExtensionOption
import "qt/qwebpluginfactory_extensionreturn.jsx"; // QWebPluginFactory_ExtensionReturn
import "qt/qwebpluginfactory_mimetype.jsx"; // QWebPluginFactory_MimeType
import "qt/qwebpluginfactory_plugin.jsx"; // QWebPluginFactory_Plugin
import "qt/qwebsettings.jsx"; // QWebSettings
import "qt/webcore.jsx"; // WebCore
