/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * com.trolltech.qt.webkitwidgets Package
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicswebview.jsx"; // QGraphicsWebView
import "qt/qwebframe.jsx"; // QWebFrame
import "qt/qwebhittestresult.jsx"; // QWebHitTestResult
import "qt/qwebinspector.jsx"; // QWebInspector
import "qt/qwebpage.jsx"; // QWebPage
import "qt/qwebpage_choosemultiplefilesextensionoption.jsx"; // QWebPage_ChooseMultipleFilesExtensionOption
import "qt/qwebpage_choosemultiplefilesextensionreturn.jsx"; // QWebPage_ChooseMultipleFilesExtensionReturn
import "qt/qwebpage_errorpageextensionoption.jsx"; // QWebPage_ErrorPageExtensionOption
import "qt/qwebpage_errorpageextensionreturn.jsx"; // QWebPage_ErrorPageExtensionReturn
import "qt/qwebpage_extensionoption.jsx"; // QWebPage_ExtensionOption
import "qt/qwebpage_extensionreturn.jsx"; // QWebPage_ExtensionReturn
import "qt/qwebview.jsx"; // QWebView
