/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * com.trolltech.qt.xmlpatterns Package
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractmessagehandler.jsx"; // QAbstractMessageHandler
import "qt/qabstracturiresolver.jsx"; // QAbstractUriResolver
import "qt/qabstractxmlnodemodel.jsx"; // QAbstractXmlNodeModel
import "qt/qabstractxmlreceiver.jsx"; // QAbstractXmlReceiver
import "qt/qpatternist.jsx"; // QPatternist
import "qt/qpatternistsdk.jsx"; // QPatternistSDK
import "qt/qsimplexmlnodemodel.jsx"; // QSimpleXmlNodeModel
import "qt/qsourcelocation.jsx"; // QSourceLocation
import "qt/qxmlformatter.jsx"; // QXmlFormatter
import "qt/qxmlitem.jsx"; // QXmlItem
import "qt/qxmlname.jsx"; // QXmlName
import "qt/qxmlnamepool.jsx"; // QXmlNamePool
import "qt/qxmlnodemodelindex.jsx"; // QXmlNodeModelIndex
import "qt/qxmlquery.jsx"; // QXmlQuery
import "qt/qxmlresultitems.jsx"; // QXmlResultItems
import "qt/qxmlschema.jsx"; // QXmlSchema
import "qt/qxmlschemavalidator.jsx"; // QXmlSchemaValidator
import "qt/qxmlserializer.jsx"; // QXmlSerializer
