/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * Signals
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractanimation.jsx";
import "qt/qabstractbutton.jsx";
import "qt/qabstractitemdelegate.jsx";
import "qt/qabstractsocket.jsx";
import "qt/qaction.jsx";
import "qt/qbrush.jsx";
import "qt/qcolor.jsx";
import "qt/qclipboard.jsx";
import "qt/qdoublevalidator.jsx";
import "qt/qdate.jsx";
import "qt/qdockwidget.jsx";
import "qt/qfont.jsx";
import "qt/qgraphicsitem.jsx";
import "qt/qgraphicsblureffect.jsx";
import "qt/qheaderview.jsx";
import "qt/qicon.jsx";
import "qt/qimagereader.jsx";
import "qt/qitemselection.jsx";
import "qt/qlistwidgetitem.jsx";
import "qt/qlocalsocket.jsx";
import "qt/qmdisubwindow.jsx";
import "qt/qmodelindex.jsx";
import "qt/qmovie.jsx";
import "qt/qnetworkproxy.jsx";
import "qt/qauthenticator.jsx";
import "qt/qnetworkaccessmanager.jsx";
import "qt/qnetworkreply.jsx";
import "qt/qnetworkrequest.jsx";
import "qt/qobject.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qprinter.jsx";
import "qt/qprocess.jsx";
import "qt/qrect.jsx";
import "qt/qrectf.jsx";
import "qt/qsessionmanager.jsx";
import "qt/qsize.jsx";
import "qt/qsqlrecord.jsx";
import "qt/qsslerror.jsx";
import "qt/qsslsocket.jsx";
import "qt/qstandarditem.jsx";
import "qt/qsystemtrayicon.jsx";
import "qt/qtablewidgetitem.jsx";
import "qt/qtextcharformat.jsx";
import "qt/qtextcursor.jsx";
import "qt/qtime.jsx";
import "qt/qtimeline.jsx";
import "qt/qtreewidgetitem.jsx";
import "qt/qundostack.jsx";
import "qt/qurl.jsx";
import "qt/qwebframe.jsx";
import "qt/qwidget.jsx";
import "qt/qt.jsx";
native __fake__ class QtJSXSignal {
    function connect(callback : function():void): void;
    function disconnect(callback : function():void): void;
}

native __fake__ class QtJSXQAbstractAnimationSignal {
    function connect(callback : function(:QAbstractAnimation):void): void;
    function disconnect(callback : function(:QAbstractAnimation):void): void;
}

native __fake__ class QtJSXQAbstractButtonSignal {
    function connect(callback : function(:QAbstractButton):void): void;
    function disconnect(callback : function(:QAbstractButton):void): void;
}

native __fake__ class QtJSXQActionSignal {
    function connect(callback : function(:QAction):void): void;
    function disconnect(callback : function(:QAction):void): void;
}

native __fake__ class QtJSXQBrushSignal {
    function connect(callback : function(:QBrush):void): void;
    function disconnect(callback : function(:QBrush):void): void;
}

native __fake__ class QtJSXQColorSignal {
    function connect(callback : function(:QColor):void): void;
    function disconnect(callback : function(:QColor):void): void;
}

native __fake__ class QtJSXQDateSignal {
    function connect(callback : function(:QDate):void): void;
    function disconnect(callback : function(:QDate):void): void;
}

native __fake__ class QtJSXQDateTimeSignal {
    function connect(callback : function(:Date):void): void;
    function disconnect(callback : function(:Date):void): void;
}

native __fake__ class QtJSXQFontSignal {
    function connect(callback : function(:QFont):void): void;
    function disconnect(callback : function(:QFont):void): void;
}

native __fake__ class QtJSXQGraphicsItemQGraphicsItemQt_FocusReasonSignal {
    function connect(callback : function(:QGraphicsItem, :QGraphicsItem, :Qt_FocusReason):void): void;
    function disconnect(callback : function(:QGraphicsItem, :QGraphicsItem, :Qt_FocusReason):void): void;
}

native __fake__ class QtJSXQIconSignal {
    function connect(callback : function(:QIcon):void): void;
    function disconnect(callback : function(:QIcon):void): void;
}

native __fake__ class QtJSXQItemSelectionQItemSelectionSignal {
    function connect(callback : function(:QItemSelection, :QItemSelection):void): void;
    function disconnect(callback : function(:QItemSelection, :QItemSelection):void): void;
}

native __fake__ class QtJSXQListWidgetItemSignal {
    function connect(callback : function(:QListWidgetItem):void): void;
    function disconnect(callback : function(:QListWidgetItem):void): void;
}

native __fake__ class QtJSXQListWidgetItemQListWidgetItemSignal {
    function connect(callback : function(:QListWidgetItem, :QListWidgetItem):void): void;
    function disconnect(callback : function(:QListWidgetItem, :QListWidgetItem):void): void;
}

native __fake__ class QtJSXQMdiSubWindowSignal {
    function connect(callback : function(:QMdiSubWindow):void): void;
    function disconnect(callback : function(:QMdiSubWindow):void): void;
}

native __fake__ class QtJSXQModelIndexSignal {
    function connect(callback : function(:QModelIndex):void): void;
    function disconnect(callback : function(:QModelIndex):void): void;
}

native __fake__ class QtJSXQModelIndexListSignal {
    function connect(callback : function(:QModelIndex[]):void): void;
    function disconnect(callback : function(:QModelIndex[]):void): void;
}

native __fake__ class QtJSXQModelIndexQModelIndexSignal {
    function connect(callback : function(:QModelIndex, :QModelIndex):void): void;
    function disconnect(callback : function(:QModelIndex, :QModelIndex):void): void;
}

native __fake__ class QtJSXQModelIndexQModelIndexintListSignal {
    function connect(callback : function(:QModelIndex, :QModelIndex, :int[]):void): void;
    function disconnect(callback : function(:QModelIndex, :QModelIndex, :int[]):void): void;
}

native __fake__ class QtJSXQNetworkProxyQAuthenticatorSignal {
    function connect(callback : function(:QNetworkProxy, :QAuthenticator):void): void;
    function disconnect(callback : function(:QNetworkProxy, :QAuthenticator):void): void;
}

native __fake__ class QtJSXQNetworkReplySignal {
    function connect(callback : function(:QNetworkReply):void): void;
    function disconnect(callback : function(:QNetworkReply):void): void;
}

native __fake__ class QtJSXQNetworkReplyQAuthenticatorSignal {
    function connect(callback : function(:QNetworkReply, :QAuthenticator):void): void;
    function disconnect(callback : function(:QNetworkReply, :QAuthenticator):void): void;
}

native __fake__ class QtJSXQNetworkReplyQSslErrorListSignal {
    function connect(callback : function(:QNetworkReply, :QSslError[]):void): void;
    function disconnect(callback : function(:QNetworkReply, :QSslError[]):void): void;
}

native __fake__ class QtJSXQNetworkRequestSignal {
    function connect(callback : function(:QNetworkRequest):void): void;
    function disconnect(callback : function(:QNetworkRequest):void): void;
}

native __fake__ class QtJSXQObjectSignal {
    function connect(callback : function(:QObject):void): void;
    function disconnect(callback : function(:QObject):void): void;
}

native __fake__ class QtJSXQPointSignal {
    function connect(callback : function(:QPoint):void): void;
    function disconnect(callback : function(:QPoint):void): void;
}

native __fake__ class QtJSXQPointFSignal {
    function connect(callback : function(:QPointF):void): void;
    function disconnect(callback : function(:QPointF):void): void;
}

native __fake__ class QtJSXQPrinterSignal {
    function connect(callback : function(:QPrinter):void): void;
    function disconnect(callback : function(:QPrinter):void): void;
}

native __fake__ class QtJSXQRectSignal {
    function connect(callback : function(:QRect):void): void;
    function disconnect(callback : function(:QRect):void): void;
}

native __fake__ class QtJSXQRectFSignal {
    function connect(callback : function(:QRectF):void): void;
    function disconnect(callback : function(:QRectF):void): void;
}

native __fake__ class QtJSXQRectFListSignal {
    function connect(callback : function(:QRectF[]):void): void;
    function disconnect(callback : function(:QRectF[]):void): void;
}

native __fake__ class QtJSXQRectQPointFQPointFSignal {
    function connect(callback : function(:QRect, :QPointF, :QPointF):void): void;
    function disconnect(callback : function(:QRect, :QPointF, :QPointF):void): void;
}

native __fake__ class QtJSXQRectintSignal {
    function connect(callback : function(:QRect, :int):void): void;
    function disconnect(callback : function(:QRect, :int):void): void;
}

native __fake__ class QtJSXQRegExpSignal {
    function connect(callback : function(:RegExp):void): void;
    function disconnect(callback : function(:RegExp):void): void;
}

native __fake__ class QtJSXQSessionManagerSignal {
    function connect(callback : function(:QSessionManager):void): void;
    function disconnect(callback : function(:QSessionManager):void): void;
}

native __fake__ class QtJSXQSizeSignal {
    function connect(callback : function(:QSize):void): void;
    function disconnect(callback : function(:QSize):void): void;
}

native __fake__ class QtJSXQSqlRecordSignal {
    function connect(callback : function(:QSqlRecord):void): void;
    function disconnect(callback : function(:QSqlRecord):void): void;
}

native __fake__ class QtJSXQSslErrorSignal {
    function connect(callback : function(:QSslError):void): void;
    function disconnect(callback : function(:QSslError):void): void;
}

native __fake__ class QtJSXQSslErrorListSignal {
    function connect(callback : function(:QSslError[]):void): void;
    function disconnect(callback : function(:QSslError[]):void): void;
}

native __fake__ class QtJSXQStandardItemSignal {
    function connect(callback : function(:QStandardItem):void): void;
    function disconnect(callback : function(:QStandardItem):void): void;
}

native __fake__ class QtJSXQStringSignal {
    function connect(callback : function(:string):void): void;
    function disconnect(callback : function(:string):void): void;
}

native __fake__ class QtJSXQStringListSignal {
    function connect(callback : function(:string[]):void): void;
    function disconnect(callback : function(:string[]):void): void;
}

native __fake__ class QtJSXQStringQStringQStringSignal {
    function connect(callback : function(:string, :string, :string):void): void;
    function disconnect(callback : function(:string, :string, :string):void): void;
}

native __fake__ class QtJSXQTableWidgetItemSignal {
    function connect(callback : function(:QTableWidgetItem):void): void;
    function disconnect(callback : function(:QTableWidgetItem):void): void;
}

native __fake__ class QtJSXQTableWidgetItemQTableWidgetItemSignal {
    function connect(callback : function(:QTableWidgetItem, :QTableWidgetItem):void): void;
    function disconnect(callback : function(:QTableWidgetItem, :QTableWidgetItem):void): void;
}

native __fake__ class QtJSXQTextCharFormatSignal {
    function connect(callback : function(:QTextCharFormat):void): void;
    function disconnect(callback : function(:QTextCharFormat):void): void;
}

native __fake__ class QtJSXQTextCursorSignal {
    function connect(callback : function(:QTextCursor):void): void;
    function disconnect(callback : function(:QTextCursor):void): void;
}

native __fake__ class QtJSXQTimeSignal {
    function connect(callback : function(:QTime):void): void;
    function disconnect(callback : function(:QTime):void): void;
}

native __fake__ class QtJSXQTreeWidgetItemSignal {
    function connect(callback : function(:QTreeWidgetItem):void): void;
    function disconnect(callback : function(:QTreeWidgetItem):void): void;
}

native __fake__ class QtJSXQTreeWidgetItemQTreeWidgetItemSignal {
    function connect(callback : function(:QTreeWidgetItem, :QTreeWidgetItem):void): void;
    function disconnect(callback : function(:QTreeWidgetItem, :QTreeWidgetItem):void): void;
}

native __fake__ class QtJSXQTreeWidgetItemintSignal {
    function connect(callback : function(:QTreeWidgetItem, :int):void): void;
    function disconnect(callback : function(:QTreeWidgetItem, :int):void): void;
}

native __fake__ class QtJSXQUndoStackSignal {
    function connect(callback : function(:QUndoStack):void): void;
    function disconnect(callback : function(:QUndoStack):void): void;
}

native __fake__ class QtJSXQUrlSignal {
    function connect(callback : function(:QUrl):void): void;
    function disconnect(callback : function(:QUrl):void): void;
}

native __fake__ class QtJSXQUrlListSignal {
    function connect(callback : function(:QUrl[]):void): void;
    function disconnect(callback : function(:QUrl[]):void): void;
}

native __fake__ class QtJSXQVariantSignal {
    function connect(callback : function(:variant):void): void;
    function disconnect(callback : function(:variant):void): void;
}

native __fake__ class QtJSXQWebFrameSignal {
    function connect(callback : function(:QWebFrame):void): void;
    function disconnect(callback : function(:QWebFrame):void): void;
}

native __fake__ class QtJSXQWebFrameQStringSignal {
    function connect(callback : function(:QWebFrame, :string):void): void;
    function disconnect(callback : function(:QWebFrame, :string):void): void;
}

native __fake__ class QtJSXQWidgetSignal {
    function connect(callback : function(:QWidget):void): void;
    function disconnect(callback : function(:QWidget):void): void;
}

native __fake__ class QtJSXQWidgetQWidgetSignal {
    function connect(callback : function(:QWidget, :QWidget):void): void;
    function disconnect(callback : function(:QWidget, :QWidget):void): void;
}

native __fake__ class QtJSXQWidgetQt_QAbstractItemDelegate_EndEditHintSignal {
    function connect(callback : function(:QWidget, :Qt_QAbstractItemDelegate_EndEditHint):void): void;
    function disconnect(callback : function(:QWidget, :Qt_QAbstractItemDelegate_EndEditHint):void): void;
}

native __fake__ class QtJSXQt_DockWidgetAreaSignal {
    function connect(callback : function(:Qt_DockWidgetArea):void): void;
    function disconnect(callback : function(:Qt_DockWidgetArea):void): void;
}

native __fake__ class QtJSXQt_DockWidgetAreasSignal {
    function connect(callback : function(:Qt_DockWidgetAreas):void): void;
    function disconnect(callback : function(:Qt_DockWidgetAreas):void): void;
}

native __fake__ class QtJSXQt_DropActionSignal {
    function connect(callback : function(:Qt_DropAction):void): void;
    function disconnect(callback : function(:Qt_DropAction):void): void;
}

native __fake__ class QtJSXQt_OrientationSignal {
    function connect(callback : function(:Qt_Orientation):void): void;
    function disconnect(callback : function(:Qt_Orientation):void): void;
}

native __fake__ class QtJSXQt_OrientationintintSignal {
    function connect(callback : function(:Qt_Orientation, :int, :int):void): void;
    function disconnect(callback : function(:Qt_Orientation, :int, :int):void): void;
}

native __fake__ class QtJSXQt_QAbstractAnimation_DirectionSignal {
    function connect(callback : function(:Qt_QAbstractAnimation_Direction):void): void;
    function disconnect(callback : function(:Qt_QAbstractAnimation_Direction):void): void;
}

native __fake__ class QtJSXQt_QAbstractAnimation_StateQt_QAbstractAnimation_StateSignal {
    function connect(callback : function(:Qt_QAbstractAnimation_State, :Qt_QAbstractAnimation_State):void): void;
    function disconnect(callback : function(:Qt_QAbstractAnimation_State, :Qt_QAbstractAnimation_State):void): void;
}

native __fake__ class QtJSXQt_QAbstractSocket_SocketErrorSignal {
    function connect(callback : function(:Qt_QAbstractSocket_SocketError):void): void;
    function disconnect(callback : function(:Qt_QAbstractSocket_SocketError):void): void;
}

native __fake__ class QtJSXQt_QAbstractSocket_SocketStateSignal {
    function connect(callback : function(:Qt_QAbstractSocket_SocketState):void): void;
    function disconnect(callback : function(:Qt_QAbstractSocket_SocketState):void): void;
}

native __fake__ class QtJSXQt_QClipboard_ModeSignal {
    function connect(callback : function(:Qt_QClipboard_Mode):void): void;
    function disconnect(callback : function(:Qt_QClipboard_Mode):void): void;
}

native __fake__ class QtJSXQt_QDockWidget_DockWidgetFeaturesSignal {
    function connect(callback : function(:Qt_QDockWidget_DockWidgetFeatures):void): void;
    function disconnect(callback : function(:Qt_QDockWidget_DockWidgetFeatures):void): void;
}

native __fake__ class QtJSXQt_QDoubleValidator_NotationSignal {
    function connect(callback : function(:Qt_QDoubleValidator_Notation):void): void;
    function disconnect(callback : function(:Qt_QDoubleValidator_Notation):void): void;
}

native __fake__ class QtJSXQt_QGraphicsBlurEffect_BlurHintsSignal {
    function connect(callback : function(:Qt_QGraphicsBlurEffect_BlurHints):void): void;
    function disconnect(callback : function(:Qt_QGraphicsBlurEffect_BlurHints):void): void;
}

native __fake__ class QtJSXQt_QImageReader_ImageReaderErrorSignal {
    function connect(callback : function(:Qt_QImageReader_ImageReaderError):void): void;
    function disconnect(callback : function(:Qt_QImageReader_ImageReaderError):void): void;
}

native __fake__ class QtJSXQt_QLocalSocket_LocalSocketErrorSignal {
    function connect(callback : function(:Qt_QLocalSocket_LocalSocketError):void): void;
    function disconnect(callback : function(:Qt_QLocalSocket_LocalSocketError):void): void;
}

native __fake__ class QtJSXQt_QLocalSocket_LocalSocketStateSignal {
    function connect(callback : function(:Qt_QLocalSocket_LocalSocketState):void): void;
    function disconnect(callback : function(:Qt_QLocalSocket_LocalSocketState):void): void;
}

native __fake__ class QtJSXQt_QMovie_MovieStateSignal {
    function connect(callback : function(:Qt_QMovie_MovieState):void): void;
    function disconnect(callback : function(:Qt_QMovie_MovieState):void): void;
}

native __fake__ class QtJSXQt_QNetworkAccessManager_NetworkAccessibilitySignal {
    function connect(callback : function(:Qt_QNetworkAccessManager_NetworkAccessibility):void): void;
    function disconnect(callback : function(:Qt_QNetworkAccessManager_NetworkAccessibility):void): void;
}

native __fake__ class QtJSXQt_QNetworkReply_NetworkErrorSignal {
    function connect(callback : function(:Qt_QNetworkReply_NetworkError):void): void;
    function disconnect(callback : function(:Qt_QNetworkReply_NetworkError):void): void;
}

native __fake__ class QtJSXQt_QProcess_ProcessErrorSignal {
    function connect(callback : function(:Qt_QProcess_ProcessError):void): void;
    function disconnect(callback : function(:Qt_QProcess_ProcessError):void): void;
}

native __fake__ class QtJSXQt_QSslSocket_SslModeSignal {
    function connect(callback : function(:Qt_QSslSocket_SslMode):void): void;
    function disconnect(callback : function(:Qt_QSslSocket_SslMode):void): void;
}

native __fake__ class QtJSXQt_QSystemTrayIcon_ActivationReasonSignal {
    function connect(callback : function(:Qt_QSystemTrayIcon_ActivationReason):void): void;
    function disconnect(callback : function(:Qt_QSystemTrayIcon_ActivationReason):void): void;
}

native __fake__ class QtJSXQt_ToolBarAreasSignal {
    function connect(callback : function(:Qt_ToolBarAreas):void): void;
    function disconnect(callback : function(:Qt_ToolBarAreas):void): void;
}

native __fake__ class QtJSXQt_ToolButtonStyleSignal {
    function connect(callback : function(:Qt_ToolButtonStyle):void): void;
    function disconnect(callback : function(:Qt_ToolButtonStyle):void): void;
}

native __fake__ class QtJSXQt_WindowStatesQt_WindowStatesSignal {
    function connect(callback : function(:Qt_WindowStates, :Qt_WindowStates):void): void;
    function disconnect(callback : function(:Qt_WindowStates, :Qt_WindowStates):void): void;
}

native __fake__ class QtJSXboolSignal {
    function connect(callback : function(:boolean):void): void;
    function disconnect(callback : function(:boolean):void): void;
}

native __fake__ class QtJSXdoubleSignal {
    function connect(callback : function(:number):void): void;
    function disconnect(callback : function(:number):void): void;
}

native __fake__ class QtJSXintSignal {
    function connect(callback : function(:int):void): void;
    function disconnect(callback : function(:int):void): void;
}

native __fake__ class QtJSXintQSqlRecordSignal {
    function connect(callback : function(:int, :QSqlRecord):void): void;
    function disconnect(callback : function(:int, :QSqlRecord):void): void;
}

native __fake__ class QtJSXintQt_QProcess_ExitStatusSignal {
    function connect(callback : function(:int, :Qt_QProcess_ExitStatus):void): void;
    function disconnect(callback : function(:int, :Qt_QProcess_ExitStatus):void): void;
}

native __fake__ class QtJSXintQt_SortOrderSignal {
    function connect(callback : function(:int, :Qt_SortOrder):void): void;
    function disconnect(callback : function(:int, :Qt_SortOrder):void): void;
}

native __fake__ class QtJSXintboolSignal {
    function connect(callback : function(:int, :boolean):void): void;
    function disconnect(callback : function(:int, :boolean):void): void;
}

native __fake__ class QtJSXintintSignal {
    function connect(callback : function(:int, :int):void): void;
    function disconnect(callback : function(:int, :int):void): void;
}

native __fake__ class QtJSXintintQRectSignal {
    function connect(callback : function(:int, :int, :QRect):void): void;
    function disconnect(callback : function(:int, :int, :QRect):void): void;
}

native __fake__ class QtJSXintintintSignal {
    function connect(callback : function(:int, :int, :int):void): void;
    function disconnect(callback : function(:int, :int, :int):void): void;
}

native __fake__ class QtJSXintintintintSignal {
    function connect(callback : function(:int, :int, :int, :int):void): void;
    function disconnect(callback : function(:int, :int, :int, :int):void): void;
}

native __fake__ class QtJSXqint64Signal {
    function connect(callback : function(:number):void): void;
    function disconnect(callback : function(:number):void): void;
}

native __fake__ class QtJSXqint64qint64Signal {
    function connect(callback : function(:number, :number):void): void;
    function disconnect(callback : function(:number, :number):void): void;
}

native __fake__ class QtJSXqrealSignal {
    function connect(callback : function(:number):void): void;
    function disconnect(callback : function(:number):void): void;
}

