/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractListModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemmodel.jsx";
import "qt/qobject.jsx";

native class QAbstractListModel extends QAbstractItemModel
{
    function constructor (parent : QObject);
}
