/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractUriResolver class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qurl.jsx";

native class QAbstractUriResolver extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function resolve (relative : QUrl, baseURI : QUrl) : QUrl;
}
