/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractScrollArea class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qframe.jsx";
import "qt/qmargins.jsx";
import "qt/qscrollbar.jsx";
import "qt/qsize.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";

native class QAbstractScrollArea extends QFrame
{
    function constructor (parent : QWidget);

    // Methods
    function addScrollBarWidget (widget : QWidget, alignment : Qt_Alignment) : void;
    function cornerWidget () : QWidget;
    function horizontalScrollBar () : QScrollBar;
    function maximumViewportSize () : QSize;
    function scrollBarWidgets (alignment : Qt_Alignment) : QWidget[];
    function scrollContentsBy (dx : int, dy : int) : void;
    function setCornerWidget (widget : QWidget) : void;
    function setHorizontalScrollBar (scrollbar : QScrollBar) : void;
    function setVerticalScrollBar (scrollbar : QScrollBar) : void;
    function setViewport (widget : QWidget) : void;
    function setViewportMargins (margins : QMargins) : void;
    function setViewportMargins (left : int, top : int, right : int, bottom : int) : void;
    function setupViewport (viewport : QWidget) : void;
    function verticalScrollBar () : QScrollBar;
    function viewport () : QWidget;
    function viewportEvent (arg__1 : QEvent) : boolean;
    function viewportSizeHint () : QSize;

    // Instance Properties
    var verticalScrollBarPolicy : Qt_ScrollBarPolicy;
    var horizontalScrollBarPolicy : Qt_ScrollBarPolicy;
}
