/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractItemModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qmimedata.jsx";
import "qt/qmodelindex.jsx";
import "qt/qobject.jsx";
import "qt/qsize.jsx";
import "qt/qt.jsx";
import "qt/_signals.jsx";

native class QAbstractItemModel extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function beginInsertColumns (parent : QModelIndex, first : int, last : int) : void;
    function beginInsertRows (parent : QModelIndex, first : int, last : int) : void;
    function beginMoveColumns (sourceParent : QModelIndex, sourceFirst : int, sourceLast : int, destinationParent : QModelIndex, destinationColumn : int) : boolean;
    function beginMoveRows (sourceParent : QModelIndex, sourceFirst : int, sourceLast : int, destinationParent : QModelIndex, destinationRow : int) : boolean;
    function beginRemoveColumns (parent : QModelIndex, first : int, last : int) : void;
    function beginRemoveRows (parent : QModelIndex, first : int, last : int) : void;
    function beginResetModel () : void;
    function buddy (index : QModelIndex) : QModelIndex;
    function canDropMimeData (data : QMimeData, action : Qt_DropAction, row : int, column : int, parent : QModelIndex) : boolean;
    function canFetchMore (parent : QModelIndex) : boolean;
    function changePersistentIndex (from : QModelIndex, to : QModelIndex) : void;
    function changePersistentIndexList (from : QModelIndex[], to : QModelIndex[]) : void;
    function columnCount (parent : QModelIndex) : int;
    function createIndex (row : int, column : int, data : variant) : QModelIndex;
    function data (index : QModelIndex, role : int) : variant;
    function dropMimeData (data : QMimeData, action : Qt_DropAction, row : int, column : int, parent : QModelIndex) : boolean;
    function endInsertColumns () : void;
    function endInsertRows () : void;
    function endMoveColumns () : void;
    function endMoveRows () : void;
    function endRemoveColumns () : void;
    function endRemoveRows () : void;
    function endResetModel () : void;
    function fetchMore (parent : QModelIndex) : void;
    function flags (index : QModelIndex) : Qt_ItemFlags;
    function hasChildren (parent : QModelIndex) : boolean;
    function hasIndex (row : int, column : int, parent : QModelIndex) : boolean;
    function headerData (section : int, orientation : Qt_Orientation, role : int) : variant;
    function index (row : int, column : int, parent : QModelIndex) : QModelIndex;
    function insertColumn (column : int, parent : QModelIndex) : boolean;
    function insertColumns (column : int, count : int, parent : QModelIndex) : boolean;
    function insertRow (row : int, parent : QModelIndex) : boolean;
    function insertRows (row : int, count : int, parent : QModelIndex) : boolean;
    function match (start : QModelIndex, role : int, value : variant, hits : int, flags : Qt_MatchFlags) : QModelIndex[];
    function mimeData (indexes : QModelIndex[]) : QMimeData;
    function mimeTypes () : string[];
    function moveColumn (sourceParent : QModelIndex, sourceColumn : int, destinationParent : QModelIndex, destinationChild : int) : boolean;
    function moveColumns (sourceParent : QModelIndex, sourceColumn : int, count : int, destinationParent : QModelIndex, destinationChild : int) : boolean;
    function moveRow (sourceParent : QModelIndex, sourceRow : int, destinationParent : QModelIndex, destinationChild : int) : boolean;
    function moveRows (sourceParent : QModelIndex, sourceRow : int, count : int, destinationParent : QModelIndex, destinationChild : int) : boolean;
    function parent (child : QModelIndex) : QModelIndex;
    function persistentIndexList () : QModelIndex[];
    function removeColumn (column : int, parent : QModelIndex) : boolean;
    function removeColumns (column : int, count : int, parent : QModelIndex) : boolean;
    function removeRow (row : int, parent : QModelIndex) : boolean;
    function removeRows (row : int, count : int, parent : QModelIndex) : boolean;
    function rowCount (parent : QModelIndex) : int;
    function setData (index : QModelIndex, value : variant, role : int) : boolean;
    function setHeaderData (section : int, orientation : Qt_Orientation, value : variant, role : int) : boolean;
    function sibling (row : int, column : int, idx : QModelIndex) : QModelIndex;
    function sort (column : int, order : Qt_SortOrder) : void;
    function span (index : QModelIndex) : QSize;
    function supportedDragActions () : Qt_DropActions;
    function supportedDropActions () : Qt_DropActions;

    // Slots
    function resetInternalData () : void;
    function revert () : void;
    function submit () : boolean;

    // Signals
    var dataChanged : QtJSXQModelIndexQModelIndexintListSignal;
    var headerDataChanged : QtJSXQt_OrientationintintSignal;
}
