/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractPrintDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdialog.jsx";
import "qt/qprinter.jsx";
import "qt/qwidget.jsx";

final native class Qt_QAbstractPrintDialog_PrintRange {}

final native class Qt_QAbstractPrintDialog_PrintDialogOption {}

final native class Qt_QAbstractPrintDialog_PrintDialogOptions {}

native class QAbstractPrintDialog extends QDialog
{
    function constructor (printer : QPrinter, parent : QWidget);

    static const AllPages : Qt_QAbstractPrintDialog_PrintRange;
    static const Selection : Qt_QAbstractPrintDialog_PrintRange;
    static const PageRange : Qt_QAbstractPrintDialog_PrintRange;
    static const CurrentPage : Qt_QAbstractPrintDialog_PrintRange;
    static function PrintRange(value : Qt_QAbstractPrintDialog_PrintRange) : Qt_QAbstractPrintDialog_PrintRange;

    static const None : Qt_QAbstractPrintDialog_PrintDialogOption;
    static const PrintToFile : Qt_QAbstractPrintDialog_PrintDialogOption;
    static const PrintSelection : Qt_QAbstractPrintDialog_PrintDialogOption;
    static const PrintPageRange : Qt_QAbstractPrintDialog_PrintDialogOption;
    static const PrintShowPageSize : Qt_QAbstractPrintDialog_PrintDialogOption;
    static const PrintCollateCopies : Qt_QAbstractPrintDialog_PrintDialogOption;
    static const DontUseSheet : Qt_QAbstractPrintDialog_PrintDialogOption;
    static const PrintCurrentPage : Qt_QAbstractPrintDialog_PrintDialogOption;
    static function PrintDialogOption(value : Qt_QAbstractPrintDialog_PrintDialogOption) : Qt_QAbstractPrintDialog_PrintDialogOption;
    static function PrintDialogOptions(...value : Qt_QAbstractPrintDialog_PrintDialogOption) : Qt_QAbstractPrintDialog_PrintDialogOptions;

    // Methods
    function addEnabledOption (option : Qt_QAbstractPrintDialog_PrintDialogOption) : void;
    function enabledOptions () : Qt_QAbstractPrintDialog_PrintDialogOptions;
    function fromPage () : int;
    function isOptionEnabled (option : Qt_QAbstractPrintDialog_PrintDialogOption) : boolean;
    function maxPage () : int;
    function minPage () : int;
    function printRange () : Qt_QAbstractPrintDialog_PrintRange;
    function printer () : QPrinter;
    function setEnabledOptions (options : Qt_QAbstractPrintDialog_PrintDialogOptions) : void;
    function setFromTo (fromPage : int, toPage : int) : void;
    function setMinMax (min : int, max : int) : void;
    function setOptionTabs (tabs : QWidget[]) : void;
    function setPrintRange (range : Qt_QAbstractPrintDialog_PrintRange) : void;
    function toPage () : int;
}
