/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractXmlNodeModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsourcelocation.jsx";
import "qt/qurl.jsx";
import "qt/qxmlname.jsx";
import "qt/qxmlnodemodelindex.jsx";

final native class Qt_QAbstractXmlNodeModel_SimpleAxis {}

final native class Qt_QAbstractXmlNodeModel_NodeCopySetting {}

native class QAbstractXmlNodeModel
{

    static const Parent : Qt_QAbstractXmlNodeModel_SimpleAxis;
    static const FirstChild : Qt_QAbstractXmlNodeModel_SimpleAxis;
    static const PreviousSibling : Qt_QAbstractXmlNodeModel_SimpleAxis;
    static const NextSibling : Qt_QAbstractXmlNodeModel_SimpleAxis;
    static function SimpleAxis(value : Qt_QAbstractXmlNodeModel_SimpleAxis) : Qt_QAbstractXmlNodeModel_SimpleAxis;

    static const InheritNamespaces : Qt_QAbstractXmlNodeModel_NodeCopySetting;
    static const PreserveNamespaces : Qt_QAbstractXmlNodeModel_NodeCopySetting;
    static function NodeCopySetting(value : Qt_QAbstractXmlNodeModel_NodeCopySetting) : Qt_QAbstractXmlNodeModel_NodeCopySetting;

    // Methods
    function attributes (element : QXmlNodeModelIndex) : QXmlNodeModelIndex[];
    function baseUri (ni : QXmlNodeModelIndex) : QUrl;
    function compareOrder (ni1 : QXmlNodeModelIndex, ni2 : QXmlNodeModelIndex) : Qt_QXmlNodeModelIndex_DocumentOrder;
    function createIndex (data : number) : QXmlNodeModelIndex;
    function createIndex (data : number, additionalData : number) : QXmlNodeModelIndex;
    function createIndex (pointer : variant, additionalData : number) : QXmlNodeModelIndex;
    function documentUri (ni : QXmlNodeModelIndex) : QUrl;
    function elementById (NCName : QXmlName) : QXmlNodeModelIndex;
    function kind (ni : QXmlNodeModelIndex) : Qt_QXmlNodeModelIndex_NodeKind;
    function name (ni : QXmlNodeModelIndex) : QXmlName;
    function namespaceBindings (n : QXmlNodeModelIndex) : QXmlName[];
    function nextFromSimpleAxis (axis : Qt_QAbstractXmlNodeModel_SimpleAxis, origin : QXmlNodeModelIndex) : QXmlNodeModelIndex;
    function nodesByIdref (NCName : QXmlName) : QXmlNodeModelIndex[];
    function root (n : QXmlNodeModelIndex) : QXmlNodeModelIndex;
    function sourceLocation (index : QXmlNodeModelIndex) : QSourceLocation;
    function stringValue (n : QXmlNodeModelIndex) : string;
    function typedValue (n : QXmlNodeModelIndex) : variant;
}
