/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QActionEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qevent.jsx";

native class QActionEvent extends QEvent
{
    function constructor (type : int, action : QAction, before : QAction);

    // Methods
    function action () : QAction;
    function before () : QAction;
}
