/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QApplication class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdesktopwidget.jsx";
import "qt/qfont.jsx";
import "qt/qguiapplication.jsx";
import "qt/qicon.jsx";
import "qt/qpalette.jsx";
import "qt/qpoint.jsx";
import "qt/qsize.jsx";
import "qt/qstyle.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QApplication_ColorSpec {}

native class QApplication extends QGuiApplication
{

    // Static Members
    static function activeModalWidget () : QWidget;
    static function activePopupWidget () : QWidget;
    static function activeWindow () : QWidget;
    static function alert (widget : QWidget, duration : int) : void;
    static function allWidgets () : QWidget[];
    static function beep () : void;
    static function colorSpec () : int;
    static function desktop () : QDesktopWidget;
    static function focusWidget () : QWidget;
    static function font (arg__1 : QWidget) : QFont;
    static function isEffectEnabled (arg__1 : Qt_UIEffect) : boolean;
    static function palette (arg__1 : QWidget) : QPalette;
    static function setActiveWindow (act : QWidget) : void;
    static function setColorSpec (arg__1 : int) : void;
    static function setEffectEnabled (arg__1 : Qt_UIEffect, enable : boolean) : void;
    static function setFont (arg__1 : QFont, className : string) : void;
    static function setPalette (arg__1 : QPalette, className : string) : void;
    static function setStyle (arg__1 : QStyle) : void;
    static function style () : QStyle;
    static function topLevelAt (p : QPoint) : QWidget;
    static function topLevelWidgets () : QWidget[];
    static function widgetAt (p : QPoint) : QWidget;

    static const NormalColor : Qt_QApplication_ColorSpec;
    static const CustomColor : Qt_QApplication_ColorSpec;
    static const ManyColor : Qt_QApplication_ColorSpec;
    static function ColorSpec(value : Qt_QApplication_ColorSpec) : Qt_QApplication_ColorSpec;

    // Slots
    function aboutQt () : void;
    function closeAllWindows () : void;

    // Signals
    var focusChanged : QtJSXQWidgetQWidgetSignal;

    // Instance Properties
    var windowIcon : QIcon;
    var cursorFlashTime : int;
    var doubleClickInterval : int;
    var keyboardInputInterval : int;
    var wheelScrollLines : int;
    var globalStrut : QSize;
    var startDragTime : int;
    var startDragDistance : int;
    var styleSheet : string;
    var autoSipEnabled : boolean;
}
