/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QBasicTimer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qt.jsx";

native class QBasicTimer
{
    function constructor ();

    // Methods
    function isActive () : boolean;
    function start (msec : int, obj : QObject) : void;
    function start (msec : int, timerType : Qt_TimerType, obj : QObject) : void;
    function stop () : void;
    function timerId () : int;
}
