/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QBasicMutex class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QBasicMutex
{
    function constructor ();

    // Methods
    function isRecursive () : boolean;
    function lock () : void;
    function tryLock () : boolean;
    function unlock () : void;
}
