/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QBoxLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayout.jsx";
import "qt/qlayoutitem.jsx";
import "qt/qspaceritem.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";

final native class Qt_QBoxLayout_Direction {}

native class QBoxLayout extends QLayout
{
    function constructor (arg__1 : Qt_QBoxLayout_Direction, parent : QWidget);

    static const LeftToRight : Qt_QBoxLayout_Direction;
    static const RightToLeft : Qt_QBoxLayout_Direction;
    static const TopToBottom : Qt_QBoxLayout_Direction;
    static const BottomToTop : Qt_QBoxLayout_Direction;
    static function Direction(value : Qt_QBoxLayout_Direction) : Qt_QBoxLayout_Direction;

    // Methods
    function addLayout (layout : QLayout, stretch : int) : void;
    function addSpacerItem (spacerItem : QSpacerItem) : void;
    function addSpacing (size : int) : void;
    function addStretch (stretch : int) : void;
    function addStrut (arg__1 : int) : void;
    function addWidget (arg__1 : QWidget, stretch : int, alignment : Qt_Alignment) : void;
    function direction () : Qt_QBoxLayout_Direction;
    function insertItem (index : int, arg__2 : QLayoutItem) : void;
    function insertLayout (index : int, layout : QLayout, stretch : int) : void;
    function insertSpacerItem (index : int, spacerItem : QSpacerItem) : void;
    function insertSpacing (index : int, size : int) : void;
    function insertStretch (index : int, stretch : int) : void;
    function insertWidget (index : int, widget : QWidget, stretch : int, alignment : Qt_Alignment) : void;
    function setDirection (arg__1 : Qt_QBoxLayout_Direction) : void;
    function setSpacing (spacing : int) : void;
    function setStretch (index : int, stretch : int) : void;
    function setStretchFactor (l : QLayout, stretch : int) : boolean;
    function setStretchFactor (w : QWidget, stretch : int) : boolean;
    function stretch (index : int) : int;
}
