/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QBuffer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qiodevice.jsx";
import "qt/qobject.jsx";

native class QBuffer extends QIODevice
{
    function constructor (buf : QByteArray, parent : QObject);
    function constructor (parent : QObject);

    // Methods
    function setBuffer (a : QByteArray) : void;
    function setData (data : QByteArray) : void;
}
