/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QButtonGroup class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractbutton.jsx";
import "qt/qobject.jsx";
import "qt/_signals.jsx";

native class QButtonGroup extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function addButton (arg__1 : QAbstractButton, id : int) : void;
    function button (id : int) : QAbstractButton;
    function buttons () : QAbstractButton[];
    function checkedButton () : QAbstractButton;
    function checkedId () : int;
    function id (button : QAbstractButton) : int;
    function removeButton (arg__1 : QAbstractButton) : void;
    function setId (button : QAbstractButton, id : int) : void;

    // Signals
    var buttonClicked : QtJSXintSignal;
    var buttonPressed : QtJSXintSignal;
    var buttonReleased : QtJSXintSignal;
    var buttonToggled : QtJSXintboolSignal;

    // Instance Properties
    var exclusive : boolean;
} = '''QButtonGroup;
QButtonGroup.prototype.buttonClicked = QButtonGroup.prototype['buttonClicked(int)'];
QButtonGroup.prototype.buttonPressed = QButtonGroup.prototype['buttonPressed(int)'];
QButtonGroup.prototype.buttonReleased = QButtonGroup.prototype['buttonReleased(int)'];
''';
