/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QByteArray class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QByteArray
{
    function constructor ();
    function constructor (arg__1 : QByteArray);
    function constructor (size : int, c : string);

    // Static Members
    static function fromBase64 (base64 : QByteArray) : QByteArray;
    static function fromHex (hexEncoded : QByteArray) : QByteArray;
    static function fromInt (arg__1 : int, base : int) : QByteArray;
    static function fromLongLong (arg__1 : number, base : int) : QByteArray;
    static function fromPercentEncoding (pctEncoded : QByteArray, percent : string) : QByteArray;
    static function number (arg__1 : number, f : string, prec : int) : QByteArray;

    // Methods
    function append (a : QByteArray) : QByteArray;
    function append (s : string) : QByteArray;
    function append (s : string, len : int) : QByteArray;
    function appendByte (c : string) : QByteArray;
    function at (i : int) : string;
    function capacity () : int;
    function cbegin () : string;
    function cend () : string;
    function chop (n : int) : void;
    function clear () : void;
    function count (c : string) : int;
    function count (a : QByteArray) : int;
    function endsWith (c : string) : boolean;
    function endsWith (a : QByteArray) : boolean;
    function fill (c : string, size : int) : QByteArray;
    function indexOf (a : QByteArray, from : int) : int;
    function indexOf (s : string, from : int) : int;
    function indexOfByte (c : string, from : int) : int;
    function insert (i : int, a : QByteArray) : QByteArray;
    function insert (i : int, s : string) : QByteArray;
    function insert (i : int, s : string, len : int) : QByteArray;
    function insertByte (i : int, c : string) : QByteArray;
    function isEmpty () : boolean;
    function isNull () : boolean;
    function isSharedWith (other : QByteArray) : boolean;
    function lastIndexOf (a : QByteArray, from : int) : int;
    function lastIndexOf (s : string, from : int) : int;
    function lastIndexOfByte (c : string, from : int) : int;
    function left (len : int) : QByteArray;
    function leftJustified (width : int, fill : string, truncate : boolean) : QByteArray;
    function length () : int;
    function mid (index : int, len : int) : QByteArray;
    function operator_assign (arg__1 : QByteArray) : QByteArray;
    function operator_equal (a2 : QByteArray) : boolean;
    function operator_equal (s2 : string) : boolean;
    function operator_less (a2 : QByteArray) : boolean;
    function operator_less (s2 : string) : boolean;
    function prepend (a : QByteArray) : QByteArray;
    function prepend (s : string, len : int) : QByteArray;
    function prependByte (c : string) : QByteArray;
    function remove (index : int, len : int) : QByteArray;
    function repeated (times : int) : QByteArray;
    function replace (before : string, after : string) : QByteArray;
    function replace (before : string, after : QByteArray) : QByteArray;
    function replace (before : QByteArray, after : QByteArray) : QByteArray;
    function replace (before : string, bsize : int, after : string, asize : int) : QByteArray;
    function replace (index : int, len : int, s : QByteArray) : QByteArray;
    function replace (index : int, len : int, s : string, alen : int) : QByteArray;
    function reserve (size : int) : void;
    function resize (size : int) : void;
    function right (len : int) : QByteArray;
    function rightJustified (width : int, fill : string, truncate : boolean) : QByteArray;
    function setDouble (arg__1 : number, f : string, prec : int) : QByteArray;
    function setFloat (arg__1 : number, f : string, prec : int) : QByteArray;
    function setInt (arg__1 : int, base : int) : QByteArray;
    function setLongLong (arg__1 : number, base : int) : QByteArray;
    function setRawData (a : string, n : int) : QByteArray;
    function setShort (arg__1 : int, base : int) : QByteArray;
    function simplified () : QByteArray;
    function size () : int;
    function split (sep : string) : QByteArray[];
    function squeeze () : void;
    function startsWith (c : string) : boolean;
    function startsWith (a : QByteArray) : boolean;
    function swap (other : QByteArray) : void;
    function toBase64 () : QByteArray;
    function toDouble () : number;
    function toFloat () : number;
    function toHex () : QByteArray;
    function toInt (base : int) : int;
    function toLower () : QByteArray;
    function toPercentEncoding (exclude : QByteArray, include : QByteArray, percent : string) : QByteArray;
    function toUShort (base : int) : int;
    function toUpper () : QByteArray;
    function trimmed () : QByteArray;
    function truncate (pos : int) : void;
}
