/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QByteArrayMatcher class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";

native class QByteArrayMatcher
{
    function constructor ();
    function constructor (pattern : QByteArray);
    function constructor (other : QByteArrayMatcher);
    function constructor (pattern : string, length : int);

    // Methods
    function indexIn (ba : QByteArray, from : int) : int;
    function indexIn (str : string, len : int, from : int) : int;
    function pattern () : QByteArray;
    function setPattern (pattern : QByteArray) : void;
}
