/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QColorDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";
import "qt/qdialog.jsx";
import "qt/qobject.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QColorDialog_ColorDialogOption {}

final native class Qt_QColorDialog_ColorDialogOptions {}

native class QColorDialog extends QDialog
{
    function constructor (parent : QWidget);
    function constructor (initial : QColor, parent : QWidget);

    // Static Members
    static function customColor (index : int) : QColor;
    static function customCount () : int;
    static function getColor (initial : QColor, parent : QWidget, title : string, options : Qt_QColorDialog_ColorDialogOptions) : QColor;
    static function setCustomColor (index : int, color : QColor) : void;
    static function setStandardColor (index : int, color : QColor) : void;
    static function standardColor (index : int) : QColor;

    static const ShowAlphaChannel : Qt_QColorDialog_ColorDialogOption;
    static const NoButtons : Qt_QColorDialog_ColorDialogOption;
    static const DontUseNativeDialog : Qt_QColorDialog_ColorDialogOption;
    static function ColorDialogOption(value : Qt_QColorDialog_ColorDialogOption) : Qt_QColorDialog_ColorDialogOption;
    static function ColorDialogOptions(...value : Qt_QColorDialog_ColorDialogOption) : Qt_QColorDialog_ColorDialogOptions;

    // Methods
    function open (receiver : QObject, member : string) : void;
    function selectedColor () : QColor;
    function setCurrentColor (color : QColor) : void;
    function setOption (option : Qt_QColorDialog_ColorDialogOption, on : boolean) : void;
    function testOption (option : Qt_QColorDialog_ColorDialogOption) : boolean;

    // Signals
    var colorSelected : QtJSXQColorSignal;
    var currentColorChanged : QtJSXQColorSignal;

    // Instance Properties
    var currentColor : QColor;
    var options : Qt_QColorDialog_ColorDialogOptions;
}
