/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QCursor class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbitmap.jsx";
import "qt/qpixmap.jsx";
import "qt/qpoint.jsx";
import "qt/qt.jsx";

native class QCursor
{
    function constructor ();
    function constructor (shape : Qt_CursorShape);
    function constructor (bitmap : QBitmap, mask : QBitmap, hotX : int, hotY : int);
    function constructor (cursor : QCursor);
    function constructor (pixmap : QPixmap, hotX : int, hotY : int);

    // Static Members
    static function pos () : QPoint;
    static function setPos (p : QPoint) : void;

    // Methods
    function bitmap () : QBitmap;
    function hotSpot () : QPoint;
    function mask () : QBitmap;
    function pixmap () : QPixmap;
    function setShape (newShape : Qt_CursorShape) : void;
    function shape () : Qt_CursorShape;
}
