/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDataWidgetMapper class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemdelegate.jsx";
import "qt/qabstractitemmodel.jsx";
import "qt/qbytearray.jsx";
import "qt/qmodelindex.jsx";
import "qt/qobject.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QDataWidgetMapper_SubmitPolicy {}

native class QDataWidgetMapper extends QObject
{
    function constructor (parent : QObject);

    static const AutoSubmit : Qt_QDataWidgetMapper_SubmitPolicy;
    static const ManualSubmit : Qt_QDataWidgetMapper_SubmitPolicy;
    static function SubmitPolicy(value : Qt_QDataWidgetMapper_SubmitPolicy) : Qt_QDataWidgetMapper_SubmitPolicy;

    // Methods
    function addMapping (widget : QWidget, section : int) : void;
    function addMapping (widget : QWidget, section : int, propertyName : QByteArray) : void;
    function clearMapping () : void;
    function itemDelegate () : QAbstractItemDelegate;
    function mappedPropertyName (widget : QWidget) : QByteArray;
    function mappedSection (widget : QWidget) : int;
    function mappedWidgetAt (section : int) : QWidget;
    function model () : QAbstractItemModel;
    function removeMapping (widget : QWidget) : void;
    function rootIndex () : QModelIndex;
    function setItemDelegate (delegate : QAbstractItemDelegate) : void;
    function setModel (model : QAbstractItemModel) : void;
    function setRootIndex (index : QModelIndex) : void;

    // Slots
    function revert () : void;
    function setCurrentModelIndex (index : QModelIndex) : void;
    function submit () : boolean;
    function toFirst () : void;
    function toLast () : void;
    function toNext () : void;
    function toPrevious () : void;

    // Signals
    var currentIndexChanged : QtJSXintSignal;

    // Instance Properties
    var currentIndex : int;
    var orientation : Qt_Orientation;
    var submitPolicy : Qt_QDataWidgetMapper_SubmitPolicy;
}
