/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDateTime class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdate.jsx";
import "qt/qt.jsx";
import "qt/qtime.jsx";

native class QDateTime
{
    function constructor ();
    function constructor (arg__1 : QDate);
    function constructor (arg__1 : QDate, arg__2 : QTime, spec : Qt_TimeSpec);
    function constructor (date : QDate, time : QTime, spec : Qt_TimeSpec, offsetSeconds : int);
    function constructor (other : Date);

    // Static Members
    static function currentDateTime () : Date;
    static function currentDateTimeUtc () : Date;
    static function currentMSecsSinceEpoch () : number;
    static function fromMSecsSinceEpoch (msecs : number) : Date;
    static function fromString (s : string, f : Qt_DateFormat) : Date;
    static function fromTime_t (secsSince1Jan1970UTC : int) : Date;

    // Methods
    function addDays (days : number) : Date;
    function addMSecs (msecs : number) : Date;
    function addMonths (months : int) : Date;
    function addSecs (secs : number) : Date;
    function addYears (years : int) : Date;
    function date () : QDate;
    function daysTo (arg__1 : Date) : number;
    function isDaylightTime () : boolean;
    function isNull () : boolean;
    function isValid () : boolean;
    function msecsTo (arg__1 : Date) : number;
    function offsetFromUtc () : int;
    function operator_equal (other : Date) : boolean;
    function operator_less (other : Date) : boolean;
    function secsTo (arg__1 : Date) : number;
    function setDate (date : QDate) : void;
    function setMSecsSinceEpoch (msecs : number) : void;
    function setOffsetFromUtc (offsetSeconds : int) : void;
    function setTime (time : QTime) : void;
    function setTimeSpec (spec : Qt_TimeSpec) : void;
    function setTime_t (secsSince1Jan1970UTC : int) : void;
    function setUtcOffset (seconds : int) : void;
    function swap (other : Date) : void;
    function time () : QTime;
    function timeSpec () : Qt_TimeSpec;
    function timeZoneAbbreviation () : string;
    function toLocalTime () : Date;
    function toMSecsSinceEpoch () : number;
    function toOffsetFromUtc (offsetSeconds : int) : Date;
    function toTimeSpec (spec : Qt_TimeSpec) : Date;
    function toTime_t () : int;
    function toUTC () : Date;
    function utcOffset () : int;
}
