/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomText class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomcharacterdata.jsx";

native class QDomText extends QDomCharacterData
{
    function constructor ();
    function constructor (x : QDomText);

    // Methods
    function splitText (offset : int) : QDomText;
}
