/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomEntity class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomnode.jsx";

native class QDomEntity extends QDomNode
{
    function constructor ();
    function constructor (x : QDomEntity);

    // Methods
    function notationName () : string;
    function publicId () : string;
    function systemId () : string;
}
