/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomEntityReference class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomnode.jsx";

native class QDomEntityReference extends QDomNode
{
    function constructor ();
    function constructor (x : QDomEntityReference);
}
