/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomComment class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomcharacterdata.jsx";

native class QDomComment extends QDomCharacterData
{
    function constructor ();
    function constructor (x : QDomComment);
}
