/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomDocumentType class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomnamednodemap.jsx";
import "qt/qdomnode.jsx";

native class QDomDocumentType extends QDomNode
{
    function constructor ();
    function constructor (x : QDomDocumentType);

    // Methods
    function entities () : QDomNamedNodeMap;
    function internalSubset () : string;
    function name () : string;
    function notations () : QDomNamedNodeMap;
    function publicId () : string;
    function systemId () : string;
}
