/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomCDATASection class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomtext.jsx";

native class QDomCDATASection extends QDomText
{
    function constructor ();
    function constructor (x : QDomCDATASection);
}
