/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomNodeList class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomnode.jsx";

native class QDomNodeList
{
    function constructor ();
    function constructor (arg__1 : QDomNodeList);

    // Methods
    function at (index : int) : QDomNode;
    function count () : int;
    function isEmpty () : boolean;
    function item (index : int) : QDomNode;
    function length () : int;
    function operator_equal (arg__1 : QDomNodeList) : boolean;
    function size () : int;
}
