/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomNotation class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomnode.jsx";

native class QDomNotation extends QDomNode
{
    function constructor ();
    function constructor (x : QDomNotation);

    // Methods
    function publicId () : string;
    function systemId () : string;
}
