/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDoubleSpinBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractspinbox.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QDoubleSpinBox extends QAbstractSpinBox
{
    function constructor (parent : QWidget);

    // Methods
    function setRange (min : number, max : number) : void;
    function textFromValue (val : number) : string;
    function valueFromText (text : string) : number;

    // Signals
    var valueChanged : QtJSXdoubleSignal;

    // Instance Properties
    var prefix : string;
    var suffix : string;
    var cleanText : string;
    var decimals : int;
    var minimum : number;
    var maximum : number;
    var singleStep : number;
    var value : number;
} = '''QDoubleSpinBox;
QDoubleSpinBox.prototype.valueChanged = QDoubleSpinBox.prototype['valueChanged(double)'];
''';
