/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDrag class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qmimedata.jsx";
import "qt/qobject.jsx";
import "qt/qpixmap.jsx";
import "qt/qpoint.jsx";
import "qt/qt.jsx";
import "qt/_signals.jsx";

native class QDrag extends QObject
{
    function constructor (dragSource : QObject);

    // Methods
    function defaultAction () : Qt_DropAction;
    function dragCursor (action : Qt_DropAction) : QPixmap;
    function exec (supportedActions : Qt_DropActions) : Qt_DropAction;
    function exec (supportedActions : Qt_DropActions, defaultAction : Qt_DropAction) : Qt_DropAction;
    function hotSpot () : QPoint;
    function mimeData () : QMimeData;
    function pixmap () : QPixmap;
    function setDragCursor (cursor : QPixmap, action : Qt_DropAction) : void;
    function setHotSpot (hotspot : QPoint) : void;
    function setMimeData (data : QMimeData) : void;
    function setPixmap (arg__1 : QPixmap) : void;
    function source () : QObject;
    function supportedActions () : Qt_DropActions;
    function target () : QObject;

    // Signals
    var actionChanged : QtJSXQt_DropActionSignal;
    var targetChanged : QtJSXQObjectSignal;
}
