/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDragEnterEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdragmoveevent.jsx";
import "qt/qmimedata.jsx";
import "qt/qpoint.jsx";
import "qt/qt.jsx";

native class QDragEnterEvent extends QDragMoveEvent
{
    function constructor (pos : QPoint, actions : Qt_DropActions, data : QMimeData, buttons : Qt_MouseButtons, modifiers : Qt_KeyboardModifiers);
}
