/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDragMoveEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdropevent.jsx";
import "qt/qevent.jsx";
import "qt/qmimedata.jsx";
import "qt/qpoint.jsx";
import "qt/qrect.jsx";
import "qt/qt.jsx";

native class QDragMoveEvent extends QDropEvent
{
    function constructor (pos : QPoint, actions : Qt_DropActions, data : QMimeData, buttons : Qt_MouseButtons, modifiers : Qt_KeyboardModifiers, type : Qt_QEvent_Type);

    // Methods
    function accept (r : QRect) : void;
    function answerRect () : QRect;
    function ignore (r : QRect) : void;
}
