/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDropEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qmimedata.jsx";
import "qt/qobject.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";

native class QDropEvent extends QEvent
{
    function constructor (pos : QPointF, actions : Qt_DropActions, data : QMimeData, buttons : Qt_MouseButtons, modifiers : Qt_KeyboardModifiers, type : Qt_QEvent_Type);

    // Methods
    function acceptProposedAction () : void;
    function dropAction () : Qt_DropAction;
    function keyboardModifiers () : Qt_KeyboardModifiers;
    function mimeData () : QMimeData;
    function mouseButtons () : Qt_MouseButtons;
    function pos () : QPoint;
    function posF () : QPointF;
    function possibleActions () : Qt_DropActions;
    function proposedAction () : Qt_DropAction;
    function setDropAction (action : Qt_DropAction) : void;
    function source () : QObject;
}
