/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDynamicPropertyChangeEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qevent.jsx";

native class QDynamicPropertyChangeEvent extends QEvent
{
    function constructor (name : QByteArray);

    // Methods
    function propertyName () : QByteArray;
}
