/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFileInfo class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdir.jsx";
import "qt/qfile.jsx";

native class QFileInfo
{
    function constructor ();
    function constructor (dir : QDir, file : string);
    function constructor (file : QFile);
    function constructor (fileinfo : QFileInfo);
    function constructor (file : string);

    // Static Members
    static function exists (file : string) : boolean;

    // Methods
    function absoluteDir () : QDir;
    function absoluteFilePath () : string;
    function absolutePath () : string;
    function baseName () : string;
    function bundleName () : string;
    function caching () : boolean;
    function canonicalFilePath () : string;
    function canonicalPath () : string;
    function completeBaseName () : string;
    function completeSuffix () : string;
    function created () : Date;
    function dir () : QDir;
    function exists () : boolean;
    function fileName () : string;
    function filePath () : string;
    function group () : string;
    function groupId () : int;
    function isAbsolute () : boolean;
    function isBundle () : boolean;
    function isDir () : boolean;
    function isExecutable () : boolean;
    function isFile () : boolean;
    function isHidden () : boolean;
    function isNativePath () : boolean;
    function isReadable () : boolean;
    function isRelative () : boolean;
    function isRoot () : boolean;
    function isSymLink () : boolean;
    function isWritable () : boolean;
    function lastModified () : Date;
    function lastRead () : Date;
    function makeAbsolute () : boolean;
    function owner () : string;
    function ownerId () : int;
    function path () : string;
    function refresh () : void;
    function setCaching (on : boolean) : void;
    function setFile (dir : QDir, file : string) : void;
    function setFile (file : QFile) : void;
    function setFile (file : string) : void;
    function size () : number;
    function suffix () : string;
    function swap (other : QFileInfo) : void;
    function symLinkTarget () : string;
}
