/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFileDevice class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qiodevice.jsx";

final native class Qt_QFileDevice_Permission {}

final native class Qt_QFileDevice_Permissions {}

final native class Qt_QFileDevice_MemoryMapFlags {}

final native class Qt_QFileDevice_FileHandleFlag {}

final native class Qt_QFileDevice_FileHandleFlags {}

final native class Qt_QFileDevice_FileError {}

native class QFileDevice extends QIODevice
{

    static const ExeOther : Qt_QFileDevice_Permission;
    static const WriteOther : Qt_QFileDevice_Permission;
    static const ReadOther : Qt_QFileDevice_Permission;
    static const ExeGroup : Qt_QFileDevice_Permission;
    static const WriteGroup : Qt_QFileDevice_Permission;
    static const ReadGroup : Qt_QFileDevice_Permission;
    static const ExeUser : Qt_QFileDevice_Permission;
    static const WriteUser : Qt_QFileDevice_Permission;
    static const ReadUser : Qt_QFileDevice_Permission;
    static const ExeOwner : Qt_QFileDevice_Permission;
    static const WriteOwner : Qt_QFileDevice_Permission;
    static const ReadOwner : Qt_QFileDevice_Permission;
    static function Permission(value : Qt_QFileDevice_Permission) : Qt_QFileDevice_Permission;
    static function Permissions(...value : Qt_QFileDevice_Permission) : Qt_QFileDevice_Permissions;

    static const NoOptions : Qt_QFileDevice_MemoryMapFlags;
    static function MemoryMapFlags(value : Qt_QFileDevice_MemoryMapFlags) : Qt_QFileDevice_MemoryMapFlags;

    static const DontCloseHandle : Qt_QFileDevice_FileHandleFlag;
    static const AutoCloseHandle : Qt_QFileDevice_FileHandleFlag;
    static function FileHandleFlag(value : Qt_QFileDevice_FileHandleFlag) : Qt_QFileDevice_FileHandleFlag;
    static function FileHandleFlags(...value : Qt_QFileDevice_FileHandleFlag) : Qt_QFileDevice_FileHandleFlags;

    static const NoError : Qt_QFileDevice_FileError;
    static const ReadError : Qt_QFileDevice_FileError;
    static const WriteError : Qt_QFileDevice_FileError;
    static const FatalError : Qt_QFileDevice_FileError;
    static const ResourceError : Qt_QFileDevice_FileError;
    static const OpenError : Qt_QFileDevice_FileError;
    static const AbortError : Qt_QFileDevice_FileError;
    static const TimeOutError : Qt_QFileDevice_FileError;
    static const UnspecifiedError : Qt_QFileDevice_FileError;
    static const RemoveError : Qt_QFileDevice_FileError;
    static const RenameError : Qt_QFileDevice_FileError;
    static const PositionError : Qt_QFileDevice_FileError;
    static const ResizeError : Qt_QFileDevice_FileError;
    static const PermissionsError : Qt_QFileDevice_FileError;
    static const CopyError : Qt_QFileDevice_FileError;
    static function FileError(value : Qt_QFileDevice_FileError) : Qt_QFileDevice_FileError;

    // Methods
    function error () : Qt_QFileDevice_FileError;
    function fileName () : string;
    function flush () : boolean;
    function handle () : int;
    function map (offset : number, size : number, flags : Qt_QFileDevice_MemoryMapFlags) : string;
    function permissions () : Qt_QFileDevice_Permissions;
    function resize (sz : number) : boolean;
    function setPermissions (permissionSpec : Qt_QFileDevice_Permissions) : boolean;
    function unsetError () : void;
}
