/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFinalState class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractstate.jsx";
import "qt/qstate.jsx";

native class QFinalState extends QAbstractState
{
    function constructor (parent : QState);
}
