/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFontComboBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcombobox.jsx";
import "qt/qfont.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QFontComboBox_FontFilter {}

final native class Qt_QFontComboBox_FontFilters {}

native class QFontComboBox extends QComboBox
{
    function constructor (parent : QWidget);

    static const AllFonts : Qt_QFontComboBox_FontFilter;
    static const ScalableFonts : Qt_QFontComboBox_FontFilter;
    static const NonScalableFonts : Qt_QFontComboBox_FontFilter;
    static const MonospacedFonts : Qt_QFontComboBox_FontFilter;
    static const ProportionalFonts : Qt_QFontComboBox_FontFilter;
    static function FontFilter(value : Qt_QFontComboBox_FontFilter) : Qt_QFontComboBox_FontFilter;
    static function FontFilters(...value : Qt_QFontComboBox_FontFilter) : Qt_QFontComboBox_FontFilters;

    // Signals
    var currentFontChanged : QtJSXQFontSignal;

    // Instance Properties
    var fontFilters : Qt_QFontComboBox_FontFilters;
    var currentFont : QFont;
}
