/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFutureWatcher class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qfuture.jsx";

native class QFutureWatcher
{
    function constructor ();

    // Methods
    function setFuture (future : QFuture) : void;
}
