/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFutureWatcherVoid class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qfuture.jsx";

native class QFutureWatcherVoid
{
    function constructor ();

    // Methods
    function setFuture (future : QFuture) : void;
}
