/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGesture class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";

final native class Qt_QGesture_GestureCancelPolicy {}

native class QGesture extends QObject
{
    function constructor (parent : QObject);

    static const CancelNone : Qt_QGesture_GestureCancelPolicy;
    static const CancelAllInContext : Qt_QGesture_GestureCancelPolicy;
    static function GestureCancelPolicy(value : Qt_QGesture_GestureCancelPolicy) : Qt_QGesture_GestureCancelPolicy;

    // Methods
    function unsetHotSpot () : void;

    // Instance Properties
    var state : Qt_GestureState;
    var gestureType : Qt_GestureType;
    var gestureCancelPolicy : Qt_QGesture_GestureCancelPolicy;
    var hotSpot : QPointF;
    var hasHotSpot : boolean;
}
