/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLFramebufferObject class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qglframebufferobjectformat.jsx";
import "qt/qimage.jsx";
import "qt/qpaintdevice.jsx";
import "qt/qsize.jsx";

final native class Qt_QGLFramebufferObject_Attachment {}

native class QGLFramebufferObject extends QPaintDevice
{
    function constructor (size : QSize, format : QGLFramebufferObjectFormat);
    function constructor (width : int, height : int, format : QGLFramebufferObjectFormat);

    // Static Members
    static function bindDefault () : boolean;
    static function hasOpenGLFramebufferBlit () : boolean;
    static function hasOpenGLFramebufferObjects () : boolean;

    static const NoAttachment : Qt_QGLFramebufferObject_Attachment;
    static const CombinedDepthStencil : Qt_QGLFramebufferObject_Attachment;
    static const Depth : Qt_QGLFramebufferObject_Attachment;
    static function Attachment(value : Qt_QGLFramebufferObject_Attachment) : Qt_QGLFramebufferObject_Attachment;

    // Methods
    function attachment () : Qt_QGLFramebufferObject_Attachment;
    function bind () : boolean;
    function format () : QGLFramebufferObjectFormat;
    function isBound () : boolean;
    function isValid () : boolean;
    function release () : boolean;
    function size () : QSize;
    function toImage () : QImage;
}
