/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLShaderProgram class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qcolor.jsx";
import "qt/qglcontext.jsx";
import "qt/qglshader.jsx";
import "qt/qmatrix3x3.jsx";
import "qt/qmatrix4x4.jsx";
import "qt/qobject.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qsize.jsx";
import "qt/qsizef.jsx";
import "qt/qtransform.jsx";
import "qt/qvector2d.jsx";
import "qt/qvector3d.jsx";
import "qt/qvector4d.jsx";

native class QGLShaderProgram extends QObject
{
    function constructor (parent : QObject);
    function constructor (context : QGLContext, parent : QObject);

    // Static Members
    static function hasOpenGLShaderPrograms (context : QGLContext) : boolean;

    // Methods
    function addShader (shader : QGLShader) : boolean;
    function addShaderFromSourceCode (type : Qt_QGLShader_ShaderType, source : QByteArray) : boolean;
    function addShaderFromSourceCode (type : Qt_QGLShader_ShaderType, source : string) : boolean;
    function addShaderFromSourceFile (type : Qt_QGLShader_ShaderType, fileName : string) : boolean;
    function attributeLocation (name : QByteArray) : int;
    function attributeLocation (name : string) : int;
    function bind () : boolean;
    function bindAttributeLocation (name : QByteArray, location : int) : void;
    function bindAttributeLocation (name : string, location : int) : void;
    function disableAttributeArray (name : string) : void;
    function disableAttributeArray (location : int) : void;
    function enableAttributeArray (name : string) : void;
    function enableAttributeArray (location : int) : void;
    function geometryOutputVertexCount () : int;
    function isLinked () : boolean;
    function link () : boolean;
    function log () : string;
    function maxGeometryOutputVertices () : int;
    function release () : void;
    function removeAllShaders () : void;
    function removeShader (shader : QGLShader) : void;
    function setAttributeArray_QVector2D (name : string, values : QVector2D, stride : int) : void;
    function setAttributeArray_QVector2D (location : int, values : QVector2D, stride : int) : void;
    function setAttributeArray_QVector3D (name : string, values : QVector3D, stride : int) : void;
    function setAttributeArray_QVector3D (location : int, values : QVector3D, stride : int) : void;
    function setAttributeArray_QVector4D (name : string, values : QVector4D, stride : int) : void;
    function setAttributeArray_QVector4D (location : int, values : QVector4D, stride : int) : void;
    function setAttributeValue (name : string, value : QColor) : void;
    function setAttributeValue (name : string, value : QVector2D) : void;
    function setAttributeValue (name : string, value : QVector3D) : void;
    function setAttributeValue (name : string, value : QVector4D) : void;
    function setAttributeValue (location : int, value : QColor) : void;
    function setAttributeValue (location : int, value : QVector2D) : void;
    function setAttributeValue (location : int, value : QVector3D) : void;
    function setAttributeValue (location : int, value : QVector4D) : void;
    function setGeometryOutputVertexCount (count : int) : void;
    function setUniformValue (name : string, color : QColor) : void;
    function setUniformValue (name : string, value : QMatrix3x3) : void;
    function setUniformValue (name : string, value : QMatrix4x4) : void;
    function setUniformValue (name : string, point : QPoint) : void;
    function setUniformValue (name : string, point : QPointF) : void;
    function setUniformValue (name : string, size : QSize) : void;
    function setUniformValue (name : string, size : QSizeF) : void;
    function setUniformValue (name : string, value : QTransform) : void;
    function setUniformValue (name : string, value : QVector2D) : void;
    function setUniformValue (name : string, value : QVector3D) : void;
    function setUniformValue (name : string, value : QVector4D) : void;
    function setUniformValue (location : int, color : QColor) : void;
    function setUniformValue (location : int, value : QMatrix3x3) : void;
    function setUniformValue (location : int, value : QMatrix4x4) : void;
    function setUniformValue (location : int, point : QPoint) : void;
    function setUniformValue (location : int, point : QPointF) : void;
    function setUniformValue (location : int, size : QSize) : void;
    function setUniformValue (location : int, size : QSizeF) : void;
    function setUniformValue (location : int, value : QTransform) : void;
    function setUniformValue (location : int, value : QVector2D) : void;
    function setUniformValue (location : int, value : QVector3D) : void;
    function setUniformValue (location : int, value : QVector4D) : void;
    function setUniformValueArray (name : string, values : QMatrix3x3, count : int) : void;
    function setUniformValueArray (name : string, values : QMatrix4x4, count : int) : void;
    function setUniformValueArray (location : int, values : QMatrix3x3, count : int) : void;
    function setUniformValueArray (location : int, values : QMatrix4x4, count : int) : void;
    function setUniformValueArray_QVector2D (name : string, values : QVector2D, count : int) : void;
    function setUniformValueArray_QVector2D (location : int, values : QVector2D, count : int) : void;
    function setUniformValueArray_QVector3D (name : string, values : QVector3D, count : int) : void;
    function setUniformValueArray_QVector3D (location : int, values : QVector3D, count : int) : void;
    function setUniformValueArray_QVector4D (name : string, values : QVector4D, count : int) : void;
    function setUniformValueArray_QVector4D (location : int, values : QVector4D, count : int) : void;
    function shaders () : QGLShader[];
    function uniformLocation (name : QByteArray) : int;
    function uniformLocation (name : string) : int;
}
