/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneHoverEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qgraphicssceneevent.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";

native class QGraphicsSceneHoverEvent extends QGraphicsSceneEvent
{
    function constructor (type : Qt_QEvent_Type);

    // Methods
    function lastPos () : QPointF;
    function lastScenePos () : QPointF;
    function lastScreenPos () : QPoint;
    function modifiers () : Qt_KeyboardModifiers;
    function pos () : QPointF;
    function scenePos () : QPointF;
    function screenPos () : QPoint;
    function setLastPos (pos : QPointF) : void;
    function setLastScenePos (pos : QPointF) : void;
    function setLastScreenPos (pos : QPoint) : void;
    function setModifiers (modifiers : Qt_KeyboardModifiers) : void;
    function setPos (pos : QPointF) : void;
    function setScenePos (pos : QPointF) : void;
    function setScreenPos (pos : QPoint) : void;
}
