/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsTextItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";
import "qt/qfont.jsx";
import "qt/qgraphicsitem.jsx";
import "qt/qgraphicsobject.jsx";
import "qt/qt.jsx";
import "qt/qtextcursor.jsx";
import "qt/qtextdocument.jsx";
import "qt/_signals.jsx";

native class QGraphicsTextItem extends QGraphicsObject
{
    function constructor (parent : QGraphicsItem);
    function constructor (text : string, parent : QGraphicsItem);

    // Methods
    function adjustSize () : void;
    function defaultTextColor () : QColor;
    function document () : QTextDocument;
    function font () : QFont;
    function openExternalLinks () : boolean;
    function setDefaultTextColor (c : QColor) : void;
    function setDocument (document : QTextDocument) : void;
    function setFont (font : QFont) : void;
    function setHtml (html : string) : void;
    function setOpenExternalLinks (open : boolean) : void;
    function setPlainText (text : string) : void;
    function setTabChangesFocus (b : boolean) : void;
    function setTextCursor (cursor : QTextCursor) : void;
    function setTextInteractionFlags (flags : Qt_TextInteractionFlags) : void;
    function setTextWidth (width : number) : void;
    function tabChangesFocus () : boolean;
    function textCursor () : QTextCursor;
    function textInteractionFlags () : Qt_TextInteractionFlags;
    function textWidth () : number;
    function toHtml () : string;
    function toPlainText () : string;

    // Signals
    var linkActivated : QtJSXQStringSignal;
    var linkHovered : QtJSXQStringSignal;
}
