/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsBlurEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicseffect.jsx";
import "qt/qobject.jsx";
import "qt/_signals.jsx";

final native class Qt_QGraphicsBlurEffect_BlurHint {}

final native class Qt_QGraphicsBlurEffect_BlurHints {}

native class QGraphicsBlurEffect extends QGraphicsEffect
{
    function constructor (parent : QObject);

    static const PerformanceHint : Qt_QGraphicsBlurEffect_BlurHint;
    static const QualityHint : Qt_QGraphicsBlurEffect_BlurHint;
    static const AnimationHint : Qt_QGraphicsBlurEffect_BlurHint;
    static function BlurHint(value : Qt_QGraphicsBlurEffect_BlurHint) : Qt_QGraphicsBlurEffect_BlurHint;
    static function BlurHints(...value : Qt_QGraphicsBlurEffect_BlurHint) : Qt_QGraphicsBlurEffect_BlurHints;

    // Signals
    var blurHintsChanged : QtJSXQt_QGraphicsBlurEffect_BlurHintsSignal;
    var blurRadiusChanged : QtJSXqrealSignal;

    // Instance Properties
    var blurRadius : number;
    var blurHints : Qt_QGraphicsBlurEffect_BlurHints;
}
