/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsColorizeEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";
import "qt/qgraphicseffect.jsx";
import "qt/qobject.jsx";
import "qt/_signals.jsx";

native class QGraphicsColorizeEffect extends QGraphicsEffect
{
    function constructor (parent : QObject);

    // Signals
    var colorChanged : QtJSXQColorSignal;
    var strengthChanged : QtJSXqrealSignal;

    // Instance Properties
    var color : QColor;
    var strength : number;
}
