/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneContextMenuEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qgraphicssceneevent.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";

final native class Qt_QGraphicsSceneContextMenuEvent_Reason {}

native class QGraphicsSceneContextMenuEvent extends QGraphicsSceneEvent
{
    function constructor (type : Qt_QEvent_Type);

    static const Mouse : Qt_QGraphicsSceneContextMenuEvent_Reason;
    static const Keyboard : Qt_QGraphicsSceneContextMenuEvent_Reason;
    static const Other : Qt_QGraphicsSceneContextMenuEvent_Reason;
    static function Reason(value : Qt_QGraphicsSceneContextMenuEvent_Reason) : Qt_QGraphicsSceneContextMenuEvent_Reason;

    // Methods
    function modifiers () : Qt_KeyboardModifiers;
    function pos () : QPointF;
    function reason () : Qt_QGraphicsSceneContextMenuEvent_Reason;
    function scenePos () : QPointF;
    function screenPos () : QPoint;
    function setModifiers (modifiers : Qt_KeyboardModifiers) : void;
    function setPos (pos : QPointF) : void;
    function setReason (reason : Qt_QGraphicsSceneContextMenuEvent_Reason) : void;
    function setScenePos (pos : QPointF) : void;
    function setScreenPos (pos : QPoint) : void;
}
