/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qpainter.jsx";
import "qt/qpixmap.jsx";
import "qt/qpoint.jsx";
import "qt/qrectf.jsx";
import "qt/qt.jsx";
import "qt/_signals.jsx";

final native class Qt_QGraphicsEffect_PixmapPadMode {}

final native class Qt_QGraphicsEffect_ChangeFlag {}

final native class Qt_QGraphicsEffect_ChangeFlags {}

native class QGraphicsEffect extends QObject
{
    function constructor (parent : QObject);

    static const NoPad : Qt_QGraphicsEffect_PixmapPadMode;
    static const PadToTransparentBorder : Qt_QGraphicsEffect_PixmapPadMode;
    static const PadToEffectiveBoundingRect : Qt_QGraphicsEffect_PixmapPadMode;
    static function PixmapPadMode(value : Qt_QGraphicsEffect_PixmapPadMode) : Qt_QGraphicsEffect_PixmapPadMode;

    static const SourceAttached : Qt_QGraphicsEffect_ChangeFlag;
    static const SourceDetached : Qt_QGraphicsEffect_ChangeFlag;
    static const SourceBoundingRectChanged : Qt_QGraphicsEffect_ChangeFlag;
    static const SourceInvalidated : Qt_QGraphicsEffect_ChangeFlag;
    static function ChangeFlag(value : Qt_QGraphicsEffect_ChangeFlag) : Qt_QGraphicsEffect_ChangeFlag;
    static function ChangeFlags(...value : Qt_QGraphicsEffect_ChangeFlag) : Qt_QGraphicsEffect_ChangeFlags;

    // Methods
    function boundingRect () : QRectF;
    function boundingRectFor (sourceRect : QRectF) : QRectF;
    function draw (painter : QPainter) : void;
    function drawSource (painter : QPainter) : void;
    function sourceBoundingRect (system : Qt_CoordinateSystem) : QRectF;
    function sourceChanged (flags : Qt_QGraphicsEffect_ChangeFlags) : void;
    function sourceIsPixmap () : boolean;
    function sourcePixmap (system : Qt_CoordinateSystem, offset : QPoint, mode : Qt_QGraphicsEffect_PixmapPadMode) : QPixmap;
    function updateBoundingRect () : void;

    // Slots
    function update () : void;

    // Signals
    var enabledChanged : QtJSXboolSignal;

    // Instance Properties
    var enabled : boolean;
}
