/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsAnchor class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qsizepolicy.jsx";

native class QGraphicsAnchor extends QObject
{

    // Methods
    function unsetSpacing () : void;

    // Instance Properties
    var spacing : number;
    var sizePolicy : Qt_QSizePolicy_Policy;
}
