/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneWheelEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qgraphicssceneevent.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";

native class QGraphicsSceneWheelEvent extends QGraphicsSceneEvent
{
    function constructor (type : Qt_QEvent_Type);

    // Methods
    function buttons () : Qt_MouseButtons;
    function delta () : int;
    function modifiers () : Qt_KeyboardModifiers;
    function orientation () : Qt_Orientation;
    function pos () : QPointF;
    function scenePos () : QPointF;
    function screenPos () : QPoint;
    function setButtons (buttons : Qt_MouseButtons) : void;
    function setDelta (delta : int) : void;
    function setModifiers (modifiers : Qt_KeyboardModifiers) : void;
    function setOrientation (orientation : Qt_Orientation) : void;
    function setPos (pos : QPointF) : void;
    function setScenePos (pos : QPointF) : void;
    function setScreenPos (pos : QPoint) : void;
}
