/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsLinearLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicslayout.jsx";
import "qt/qgraphicslayoutitem.jsx";
import "qt/qt.jsx";

native class QGraphicsLinearLayout extends QGraphicsLayout
{
    function constructor (parent : QGraphicsLayoutItem);
    function constructor (orientation : Qt_Orientation, parent : QGraphicsLayoutItem);

    // Methods
    function addItem (item : QGraphicsLayoutItem) : void;
    function addStretch (stretch : int) : void;
    function alignment (item : QGraphicsLayoutItem) : Qt_Alignment;
    function dump (indent : int) : void;
    function insertItem (index : int, item : QGraphicsLayoutItem) : void;
    function insertStretch (index : int, stretch : int) : void;
    function itemSpacing (index : int) : number;
    function orientation () : Qt_Orientation;
    function removeItem (item : QGraphicsLayoutItem) : void;
    function setAlignment (item : QGraphicsLayoutItem, alignment : Qt_Alignment) : void;
    function setItemSpacing (index : int, spacing : number) : void;
    function setOrientation (orientation : Qt_Orientation) : void;
    function setSpacing (spacing : number) : void;
    function setStretchFactor (item : QGraphicsLayoutItem, stretch : int) : void;
    function spacing () : number;
    function stretchFactor (item : QGraphicsLayoutItem) : int;
}
