/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneMouseEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qgraphicssceneevent.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";

native class QGraphicsSceneMouseEvent extends QGraphicsSceneEvent
{
    function constructor (type : Qt_QEvent_Type);

    // Methods
    function button () : Qt_MouseButton;
    function buttonDownPos (button : Qt_MouseButton) : QPointF;
    function buttonDownScenePos (button : Qt_MouseButton) : QPointF;
    function buttonDownScreenPos (button : Qt_MouseButton) : QPoint;
    function buttons () : Qt_MouseButtons;
    function lastPos () : QPointF;
    function lastScenePos () : QPointF;
    function lastScreenPos () : QPoint;
    function modifiers () : Qt_KeyboardModifiers;
    function pos () : QPointF;
    function scenePos () : QPointF;
    function screenPos () : QPoint;
    function setButton (button : Qt_MouseButton) : void;
    function setButtonDownPos (button : Qt_MouseButton, pos : QPointF) : void;
    function setButtonDownScenePos (button : Qt_MouseButton, pos : QPointF) : void;
    function setButtonDownScreenPos (button : Qt_MouseButton, pos : QPoint) : void;
    function setButtons (buttons : Qt_MouseButtons) : void;
    function setLastPos (pos : QPointF) : void;
    function setLastScenePos (pos : QPointF) : void;
    function setLastScreenPos (pos : QPoint) : void;
    function setModifiers (modifiers : Qt_KeyboardModifiers) : void;
    function setPos (pos : QPointF) : void;
    function setScenePos (pos : QPointF) : void;
    function setScreenPos (pos : QPoint) : void;
}
