/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsTransform class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qmatrix4x4.jsx";
import "qt/qobject.jsx";

native class QGraphicsTransform extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function applyTo (matrix : QMatrix4x4) : void;

    // Slots
    function update () : void;
}
