/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneMoveEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";
import "qt/qpointf.jsx";

native class QGraphicsSceneMoveEvent extends QGraphicsSceneEvent
{
    function constructor ();

    // Methods
    function newPos () : QPointF;
    function oldPos () : QPointF;
    function setNewPos (pos : QPointF) : void;
    function setOldPos (pos : QPointF) : void;
}
