/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsScale class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicstransform.jsx";
import "qt/qobject.jsx";
import "qt/qvector3d.jsx";
import "qt/_signals.jsx";

native class QGraphicsScale extends QGraphicsTransform
{
    function constructor (parent : QObject);

    // Signals
    var originChanged : QtJSXSignal;
    var scaleChanged : QtJSXSignal;
    var xScaleChanged : QtJSXSignal;
    var yScaleChanged : QtJSXSignal;
    var zScaleChanged : QtJSXSignal;

    // Instance Properties
    var origin : QVector3D;
    var xScale : number;
    var yScale : number;
    var zScale : number;
}
