/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneDragDropEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qgraphicssceneevent.jsx";
import "qt/qmimedata.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";

native class QGraphicsSceneDragDropEvent extends QGraphicsSceneEvent
{
    function constructor (type : Qt_QEvent_Type);

    // Methods
    function acceptProposedAction () : void;
    function buttons () : Qt_MouseButtons;
    function dropAction () : Qt_DropAction;
    function mimeData () : QMimeData;
    function modifiers () : Qt_KeyboardModifiers;
    function pos () : QPointF;
    function possibleActions () : Qt_DropActions;
    function proposedAction () : Qt_DropAction;
    function scenePos () : QPointF;
    function screenPos () : QPoint;
    function setButtons (buttons : Qt_MouseButtons) : void;
    function setDropAction (action : Qt_DropAction) : void;
    function setModifiers (modifiers : Qt_KeyboardModifiers) : void;
    function setPos (pos : QPointF) : void;
    function setPossibleActions (actions : Qt_DropActions) : void;
    function setProposedAction (action : Qt_DropAction) : void;
    function setScenePos (pos : QPointF) : void;
    function setScreenPos (pos : QPoint) : void;
    function source () : QWidget;
}
