/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGridLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayout.jsx";
import "qt/qlayoutitem.jsx";
import "qt/qrect.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";

native class QGridLayout extends QLayout
{
    function constructor ();
    function constructor (parent : QWidget);

    // Methods
    function addItem (item : QLayoutItem, row : int, column : int, rowSpan : int, columnSpan : int, arg__6 : Qt_Alignment) : void;
    function addLayout (arg__1 : QLayout, row : int, column : int, arg__4 : Qt_Alignment) : void;
    function addLayout (arg__1 : QLayout, row : int, column : int, rowSpan : int, columnSpan : int, arg__6 : Qt_Alignment) : void;
    function addWidget (arg__1 : QWidget, row : int, column : int, arg__4 : Qt_Alignment) : void;
    function addWidget (arg__1 : QWidget, row : int, column : int, rowSpan : int, columnSpan : int, arg__6 : Qt_Alignment) : void;
    function cellRect (row : int, column : int) : QRect;
    function columnCount () : int;
    function columnMinimumWidth (column : int) : int;
    function columnStretch (column : int) : int;
    function getItemPosition (idx : int, row : int, column : int, rowSpan : int, columnSpan : int) : void;
    function horizontalSpacing () : int;
    function itemAtPosition (row : int, column : int) : QLayoutItem;
    function originCorner () : Qt_Corner;
    function rowCount () : int;
    function rowMinimumHeight (row : int) : int;
    function rowStretch (row : int) : int;
    function setColumnMinimumWidth (column : int, minSize : int) : void;
    function setColumnStretch (column : int, stretch : int) : void;
    function setDefaultPositioning (n : int, orient : Qt_Orientation) : void;
    function setHorizontalSpacing (spacing : int) : void;
    function setOriginCorner (arg__1 : Qt_Corner) : void;
    function setRowMinimumHeight (row : int, minSize : int) : void;
    function setRowStretch (row : int, stretch : int) : void;
    function setSpacing (spacing : int) : void;
    function setVerticalSpacing (spacing : int) : void;
    function verticalSpacing () : int;
}
