/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGroupBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoptiongroupbox.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QGroupBox extends QWidget
{
    function constructor (parent : QWidget);
    function constructor (title : string, parent : QWidget);

    // Methods
    function initStyleOption (option : QStyleOptionGroupBox) : void;
    function setAlignment (alignment : int) : void;

    // Signals
    var clicked : QtJSXboolSignal;
    var toggled : QtJSXboolSignal;

    // Instance Properties
    var title : string;
    var alignment : Qt_Alignment;
    var flat : boolean;
    var checkable : boolean;
    var checked : boolean;
}
