/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QHideEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";

native class QHideEvent extends QEvent
{
    function constructor ();
}
