/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QHistoryState class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractstate.jsx";
import "qt/qstate.jsx";

final native class Qt_QHistoryState_HistoryType {}

native class QHistoryState extends QAbstractState
{
    function constructor (type : Qt_QHistoryState_HistoryType, parent : QState);
    function constructor (parent : QState);

    static const ShallowHistory : Qt_QHistoryState_HistoryType;
    static const DeepHistory : Qt_QHistoryState_HistoryType;
    static function HistoryType(value : Qt_QHistoryState_HistoryType) : Qt_QHistoryState_HistoryType;

    // Instance Properties
    var defaultState : QAbstractState;
    var historyType : Qt_QHistoryState_HistoryType;
}
