/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QIconDragEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";

native class QIconDragEvent extends QEvent
{
    function constructor ();
}
