/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QIcon class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpainter.jsx";
import "qt/qpixmap.jsx";
import "qt/qrect.jsx";
import "qt/qsize.jsx";
import "qt/qt.jsx";

final native class Qt_QIcon_Mode {}

final native class Qt_QIcon_State {}

native class QIcon
{
    function constructor ();
    function constructor (other : QIcon);
    function constructor (pixmap : QPixmap);
    function constructor (fileName : string);

    // Static Members
    static function fromTheme (name : string, fallback : QIcon) : QIcon;
    static function hasThemeIcon (name : string) : boolean;
    static function setThemeName (path : string) : void;
    static function setThemeSearchPaths (searchpath : string[]) : void;
    static function themeName () : string;
    static function themeSearchPaths () : string[];

    static const Normal : Qt_QIcon_Mode;
    static const Disabled : Qt_QIcon_Mode;
    static const Active : Qt_QIcon_Mode;
    static const Selected : Qt_QIcon_Mode;
    static function Mode(value : Qt_QIcon_Mode) : Qt_QIcon_Mode;

    static const On : Qt_QIcon_State;
    static const Off : Qt_QIcon_State;
    static function State(value : Qt_QIcon_State) : Qt_QIcon_State;

    // Methods
    function actualSize (size : QSize, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : QSize;
    function addFile (fileName : string, size : QSize, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : void;
    function addPixmap (pixmap : QPixmap, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : void;
    function availableSizes (mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : QSize[];
    function cacheKey () : number;
    function isNull () : boolean;
    function name () : string;
    function paint (painter : QPainter, rect : QRect, alignment : Qt_Alignment, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : void;
    function paint (painter : QPainter, x : int, y : int, w : int, h : int, alignment : Qt_Alignment, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : void;
    function pixmap (size : QSize, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : QPixmap;
    function pixmap (extent : int, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : QPixmap;
    function pixmap (w : int, h : int, mode : Qt_QIcon_Mode, state : Qt_QIcon_State) : QPixmap;
    function swap (other : QIcon) : void;
}
