/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QImageIOPlugin class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qimageiohandler.jsx";
import "qt/qiodevice.jsx";
import "qt/qobject.jsx";

final native class Qt_QImageIOPlugin_Capability {}

final native class Qt_QImageIOPlugin_Capabilities {}

native class QImageIOPlugin extends QObject
{
    function constructor (parent : QObject);

    static const CanRead : Qt_QImageIOPlugin_Capability;
    static const CanWrite : Qt_QImageIOPlugin_Capability;
    static const CanReadIncremental : Qt_QImageIOPlugin_Capability;
    static function Capability(value : Qt_QImageIOPlugin_Capability) : Qt_QImageIOPlugin_Capability;
    static function Capabilities(...value : Qt_QImageIOPlugin_Capability) : Qt_QImageIOPlugin_Capabilities;

    // Methods
    function capabilities (device : QIODevice, format : QByteArray) : Qt_QImageIOPlugin_Capabilities;
    function create (device : QIODevice, format : QByteArray) : QImageIOHandler;
}
