/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QInputEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qt.jsx";

native class QInputEvent extends QEvent
{
    function constructor (type : Qt_QEvent_Type, modifiers : Qt_KeyboardModifiers);

    // Methods
    function modifiers () : Qt_KeyboardModifiers;
    function setModifiers (amodifiers : Qt_KeyboardModifiers) : void;
    function setTimestamp (atimestamp : int) : void;
    function timestamp () : int;
}
