/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLabel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qmovie.jsx";
import "qt/qpicture.jsx";
import "qt/qpixmap.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QLabel extends QFrame
{
    function constructor (parent : QWidget, f : Qt_WindowFlags);
    function constructor (text : string, parent : QWidget, f : Qt_WindowFlags);

    // Methods
    function buddy () : QWidget;
    function movie () : QMovie;
    function picture_private () : QPicture;
    function selectionStart () : int;
    function setBuddy (arg__1 : QWidget) : void;
    function setSelection (arg__1 : int, arg__2 : int) : void;

    // Slots
    function clear () : void;
    function setMovie (movie : QMovie) : void;
    function setNum (arg__1 : number) : void;
    function setNum (arg__1 : int) : void;
    function setPicture (arg__1 : QPicture) : void;

    // Signals
    var linkActivated : QtJSXQStringSignal;
    var linkHovered : QtJSXQStringSignal;

    // Instance Properties
    var text : string;
    var textFormat : Qt_TextFormat;
    var pixmap : QPixmap;
    var scaledContents : boolean;
    var alignment : Qt_Alignment;
    var wordWrap : boolean;
    var margin : int;
    var indent : int;
    var openExternalLinks : boolean;
    var textInteractionFlags : Qt_TextInteractionFlags;
    var hasSelectedText : boolean;
    var selectedText : string;
}
