/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLayoutItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayout.jsx";
import "qt/qrect.jsx";
import "qt/qsize.jsx";
import "qt/qsizepolicy.jsx";
import "qt/qspaceritem.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";

native class QLayoutItem
{
    function constructor (alignment : Qt_Alignment);

    // Methods
    function alignment () : Qt_Alignment;
    function controlTypes () : Qt_QSizePolicy_ControlTypes;
    function expandingDirections () : Qt_Orientations;
    function geometry () : QRect;
    function hasHeightForWidth () : boolean;
    function heightForWidth (arg__1 : int) : int;
    function invalidate () : void;
    function isEmpty () : boolean;
    function layout () : QLayout;
    function maximumSize () : QSize;
    function minimumHeightForWidth (arg__1 : int) : int;
    function minimumSize () : QSize;
    function setAlignment (a : Qt_Alignment) : void;
    function setGeometry (arg__1 : QRect) : void;
    function spacerItem () : QSpacerItem;
    function widget () : QWidget;
}
