/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLine class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpoint.jsx";

native class QLine
{
    function constructor ();
    function constructor (pt1 : QPoint, pt2 : QPoint);
    function constructor (x1 : int, y1 : int, x2 : int, y2 : int);

    // Methods
    function dx () : int;
    function dy () : int;
    function isNull () : boolean;
    function operator_equal (d : QLine) : boolean;
    function p1 () : QPoint;
    function p2 () : QPoint;
    function setLine (x1 : int, y1 : int, x2 : int, y2 : int) : void;
    function setP1 (p1 : QPoint) : void;
    function setP2 (p2 : QPoint) : void;
    function setPoints (p1 : QPoint, p2 : QPoint) : void;
    function translate (p : QPoint) : void;
    function translate (dx : int, dy : int) : void;
    function translated (p : QPoint) : QLine;
    function translated (dx : int, dy : int) : QLine;
    function x1 () : int;
    function x2 () : int;
    function y1 () : int;
    function y2 () : int;
}
