/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QListWidgetItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qfont.jsx";
import "qt/qicon.jsx";
import "qt/qlistwidget.jsx";
import "qt/qsize.jsx";
import "qt/qt.jsx";

final native class Qt_QListWidgetItem_ItemType {}

native class QListWidgetItem
{
    function constructor (view : QListWidget, type : int);
    function constructor (icon : QIcon, text : string, view : QListWidget, type : int);
    function constructor (text : string, view : QListWidget, type : int);

    static const Type : Qt_QListWidgetItem_ItemType;
    static const UserType : Qt_QListWidgetItem_ItemType;
    static function ItemType(value : Qt_QListWidgetItem_ItemType) : Qt_QListWidgetItem_ItemType;

    // Methods
    function background () : QBrush;
    function checkState () : Qt_CheckState;
    function clone () : QListWidgetItem;
    function data (role : int) : variant;
    function flags () : Qt_ItemFlags;
    function font () : QFont;
    function foreground () : QBrush;
    function icon () : QIcon;
    function isHidden () : boolean;
    function isSelected () : boolean;
    function listWidget () : QListWidget;
    function setBackground (brush : QBrush) : void;
    function setCheckState (state : Qt_CheckState) : void;
    function setData (role : int, value : variant) : void;
    function setFlags (flags : Qt_ItemFlags) : void;
    function setFont (font : QFont) : void;
    function setForeground (brush : QBrush) : void;
    function setHidden (hide : boolean) : void;
    function setIcon (icon : QIcon) : void;
    function setSelected (select : boolean) : void;
    function setSizeHint (size : QSize) : void;
    function setStatusTip (statusTip : string) : void;
    function setText (text : string) : void;
    function setTextAlignment (alignment : int) : void;
    function setToolTip (toolTip : string) : void;
    function setWhatsThis (whatsThis : string) : void;
    function statusTip () : string;
    function text () : string;
    function textAlignment () : int;
    function toolTip () : string;
    function type () : int;
    function whatsThis () : string;
}
