/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMainWindow class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qdockwidget.jsx";
import "qt/qmenu.jsx";
import "qt/qmenubar.jsx";
import "qt/qpoint.jsx";
import "qt/qsize.jsx";
import "qt/qstatusbar.jsx";
import "qt/qt.jsx";
import "qt/qtabwidget.jsx";
import "qt/qtoolbar.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QMainWindow_DockOption {}

final native class Qt_QMainWindow_DockOptions {}

native class QMainWindow extends QWidget
{
    function constructor (parent : QWidget, flags : Qt_WindowFlags);

    static const AnimatedDocks : Qt_QMainWindow_DockOption;
    static const AllowNestedDocks : Qt_QMainWindow_DockOption;
    static const AllowTabbedDocks : Qt_QMainWindow_DockOption;
    static const ForceTabbedDocks : Qt_QMainWindow_DockOption;
    static const VerticalTabs : Qt_QMainWindow_DockOption;
    static function DockOption(value : Qt_QMainWindow_DockOption) : Qt_QMainWindow_DockOption;
    static function DockOptions(...value : Qt_QMainWindow_DockOption) : Qt_QMainWindow_DockOptions;

    // Methods
    function addDockWidget (area : Qt_DockWidgetArea, dockwidget : QDockWidget) : void;
    function addDockWidget (area : Qt_DockWidgetArea, dockwidget : QDockWidget, orientation : Qt_Orientation) : void;
    function addToolBar (toolbar : QToolBar) : void;
    function addToolBar (area : Qt_ToolBarArea, toolbar : QToolBar) : void;
    function addToolBar (title : string) : QToolBar;
    function addToolBarBreak (area : Qt_ToolBarArea) : void;
    function centralWidget () : QWidget;
    function corner (corner : Qt_Corner) : Qt_DockWidgetArea;
    function createPopupMenu () : QMenu;
    function dockWidgetArea (dockwidget : QDockWidget) : Qt_DockWidgetArea;
    function insertToolBar (before : QToolBar, toolbar : QToolBar) : void;
    function insertToolBarBreak (before : QToolBar) : void;
    function isSeparator (pos : QPoint) : boolean;
    function menuBar () : QMenuBar;
    function menuWidget () : QWidget;
    function removeDockWidget (dockwidget : QDockWidget) : void;
    function removeToolBar (toolbar : QToolBar) : void;
    function removeToolBarBreak (before : QToolBar) : void;
    function restoreDockWidget (dockwidget : QDockWidget) : boolean;
    function restoreState (state : QByteArray, version : int) : boolean;
    function saveState (version : int) : QByteArray;
    function setCentralWidget (widget : QWidget) : void;
    function setCorner (corner : Qt_Corner, area : Qt_DockWidgetArea) : void;
    function setMenuBar (menubar : QMenuBar) : void;
    function setMenuWidget (menubar : QWidget) : void;
    function setStatusBar (statusbar : QStatusBar) : void;
    function setTabPosition (areas : Qt_DockWidgetAreas, tabPosition : Qt_QTabWidget_TabPosition) : void;
    function splitDockWidget (after : QDockWidget, dockwidget : QDockWidget, orientation : Qt_Orientation) : void;
    function statusBar () : QStatusBar;
    function tabPosition (area : Qt_DockWidgetArea) : Qt_QTabWidget_TabPosition;
    function tabifiedDockWidgets (dockwidget : QDockWidget) : QDockWidget[];
    function tabifyDockWidget (first : QDockWidget, second : QDockWidget) : void;
    function takeCentralWidget () : QWidget;
    function toolBarArea (toolbar : QToolBar) : Qt_ToolBarArea;
    function toolBarBreak (toolbar : QToolBar) : boolean;

    // Signals
    var iconSizeChanged : QtJSXQSizeSignal;
    var toolButtonStyleChanged : QtJSXQt_ToolButtonStyleSignal;

    // Instance Properties
    var iconSize : QSize;
    var toolButtonStyle : Qt_ToolButtonStyle;
    var animated : boolean;
    var documentMode : boolean;
    var tabShape : Qt_QTabWidget_TabShape;
    var dockNestingEnabled : boolean;
    var dockOptions : Qt_QMainWindow_DockOptions;
    var unifiedTitleAndToolBarOnMac : boolean;
}
