/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMargins class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QMargins
{
    function constructor ();
    function constructor (left : int, top : int, right : int, bottom : int);

    // Methods
    function bottom () : int;
    function isNull () : boolean;
    function left () : int;
    function operator_equal (m2 : QMargins) : boolean;
    function right () : int;
    function setBottom (bottom : int) : void;
    function setLeft (left : int) : void;
    function setRight (right : int) : void;
    function setTop (top : int) : void;
    function top () : int;
}
