/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMenuBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qicon.jsx";
import "qt/qmenu.jsx";
import "qt/qpoint.jsx";
import "qt/qrect.jsx";
import "qt/qstyleoptionmenuitem.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QMenuBar extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function actionAt (arg__1 : QPoint) : QAction;
    function actionGeometry (arg__1 : QAction) : QRect;
    function activeAction () : QAction;
    function addAction (text : string) : QAction;
    function addMenu (menu : QMenu) : QAction;
    function addMenu (icon : QIcon, title : string) : QMenu;
    function addMenu (title : string) : QMenu;
    function addSeparator () : QAction;
    function clear () : void;
    function cornerWidget (corner : Qt_Corner) : QWidget;
    function initStyleOption (option : QStyleOptionMenuItem, action : QAction) : void;
    function insertMenu (before : QAction, menu : QMenu) : QAction;
    function insertSeparator (before : QAction) : QAction;
    function setActiveAction (action : QAction) : void;
    function setCornerWidget (w : QWidget, corner : Qt_Corner) : void;

    // Slots
    function setVisible (visible : boolean) : void;

    // Signals
    var hovered : QtJSXQActionSignal;
    var triggered : QtJSXQActionSignal;

    // Instance Properties
    var defaultUp : boolean;
    var nativeMenuBar : boolean;
}
