/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QModelIndex class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemmodel.jsx";
import "qt/qt.jsx";

native class QModelIndex
{
    function constructor ();

    // Methods
    function child (row : int, column : int) : QModelIndex;
    function column () : int;
    function data (role : int) : variant;
    function flags () : Qt_ItemFlags;
    function internalPointer () : variant;
    function isValid () : boolean;
    function model () : QAbstractItemModel;
    function operator_equal (other : QModelIndex) : boolean;
    function operator_less (other : QModelIndex) : boolean;
    function parent () : QModelIndex;
    function row () : int;
    function sibling (row : int, column : int) : QModelIndex;
}
