/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMouseEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qinputevent.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qt.jsx";

native class QMouseEvent extends QInputEvent
{
    function constructor (type : Qt_QEvent_Type, localPos : QPointF, button : Qt_MouseButton, buttons : Qt_MouseButtons, modifiers : Qt_KeyboardModifiers);
    function constructor (type : Qt_QEvent_Type, localPos : QPointF, screenPos : QPointF, button : Qt_MouseButton, buttons : Qt_MouseButtons, modifiers : Qt_KeyboardModifiers);
    function constructor (type : Qt_QEvent_Type, localPos : QPointF, windowPos : QPointF, screenPos : QPointF, button : Qt_MouseButton, buttons : Qt_MouseButtons, modifiers : Qt_KeyboardModifiers);

    // Methods
    function button () : Qt_MouseButton;
    function buttons () : Qt_MouseButtons;
    function globalPos () : QPoint;
    function globalX () : int;
    function globalY () : int;
    function localPos () : QPointF;
    function pos () : QPoint;
    function screenPos () : QPointF;
    function windowPos () : QPointF;
    function x () : int;
    function y () : int;
}
