/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMovie class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qcolor.jsx";
import "qt/qimage.jsx";
import "qt/qimagereader.jsx";
import "qt/qiodevice.jsx";
import "qt/qobject.jsx";
import "qt/qpixmap.jsx";
import "qt/qrect.jsx";
import "qt/qsize.jsx";
import "qt/_signals.jsx";

final native class Qt_QMovie_CacheMode {}

final native class Qt_QMovie_MovieState {}

native class QMovie extends QObject
{
    function constructor (device : QIODevice, format : QByteArray, parent : QObject);
    function constructor (parent : QObject);
    function constructor (fileName : string, format : QByteArray, parent : QObject);

    // Static Members
    static function supportedFormats () : QByteArray[];

    static const CacheNone : Qt_QMovie_CacheMode;
    static const CacheAll : Qt_QMovie_CacheMode;
    static function CacheMode(value : Qt_QMovie_CacheMode) : Qt_QMovie_CacheMode;

    static const NotRunning : Qt_QMovie_MovieState;
    static const Paused : Qt_QMovie_MovieState;
    static const Running : Qt_QMovie_MovieState;
    static function MovieState(value : Qt_QMovie_MovieState) : Qt_QMovie_MovieState;

    // Methods
    function backgroundColor () : QColor;
    function currentFrameNumber () : int;
    function currentImage () : QImage;
    function currentPixmap () : QPixmap;
    function device () : QIODevice;
    function fileName () : string;
    function format () : QByteArray;
    function frameCount () : int;
    function frameRect () : QRect;
    function isValid () : boolean;
    function jumpToFrame (frameNumber : int) : boolean;
    function loopCount () : int;
    function nextFrameDelay () : int;
    function scaledSize () : QSize;
    function setBackgroundColor (color : QColor) : void;
    function setDevice (device : QIODevice) : void;
    function setFileName (fileName : string) : void;
    function setFormat (format : QByteArray) : void;
    function setScaledSize (size : QSize) : void;
    function state () : Qt_QMovie_MovieState;

    // Slots
    function jumpToNextFrame () : boolean;
    function setPaused (paused : boolean) : void;
    function start () : void;
    function stop () : void;

    // Signals
    var error : QtJSXQt_QImageReader_ImageReaderErrorSignal;
    var finished : QtJSXSignal;
    var frameChanged : QtJSXintSignal;
    var resized : QtJSXQSizeSignal;
    var started : QtJSXSignal;
    var stateChanged : QtJSXQt_QMovie_MovieStateSignal;
    var updated : QtJSXQRectSignal;

    // Instance Properties
    var speed : int;
    var cacheMode : Qt_QMovie_CacheMode;
}
