/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMoveEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qpoint.jsx";

native class QMoveEvent extends QEvent
{
    function constructor (pos : QPoint, oldPos : QPoint);

    // Methods
    function oldPos () : QPoint;
    function pos () : QPoint;
}
