/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QNetworkProxyQuery class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qurl.jsx";

final native class Qt_QNetworkProxyQuery_QueryType {}

native class QNetworkProxyQuery
{
    function constructor ();
    function constructor (other : QNetworkProxyQuery);
    function constructor (hostname : string, port : int, protocolTag : string, queryType : Qt_QNetworkProxyQuery_QueryType);
    function constructor (requestUrl : QUrl, queryType : Qt_QNetworkProxyQuery_QueryType);
    function constructor (bindPort : int, protocolTag : string, queryType : Qt_QNetworkProxyQuery_QueryType);

    static const TcpSocket : Qt_QNetworkProxyQuery_QueryType;
    static const UdpSocket : Qt_QNetworkProxyQuery_QueryType;
    static const TcpServer : Qt_QNetworkProxyQuery_QueryType;
    static const UrlRequest : Qt_QNetworkProxyQuery_QueryType;
    static function QueryType(value : Qt_QNetworkProxyQuery_QueryType) : Qt_QNetworkProxyQuery_QueryType;

    // Methods
    function localPort () : int;
    function operator_equal (other : QNetworkProxyQuery) : boolean;
    function peerHostName () : string;
    function peerPort () : int;
    function protocolTag () : string;
    function queryType () : Qt_QNetworkProxyQuery_QueryType;
    function setLocalPort (port : int) : void;
    function setPeerHostName (hostname : string) : void;
    function setPeerPort (port : int) : void;
    function setProtocolTag (protocolTag : string) : void;
    function setQueryType (type : Qt_QNetworkProxyQuery_QueryType) : void;
    function setUrl (url : QUrl) : void;
    function swap (other : QNetworkProxyQuery) : void;
    function url () : QUrl;
}
