/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QNetworkCookieJar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qnetworkcookie.jsx";
import "qt/qobject.jsx";
import "qt/qurl.jsx";

native class QNetworkCookieJar extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function allCookies () : QNetworkCookie[];
    function cookiesForUrl (url : QUrl) : QNetworkCookie[];
    function deleteCookie (cookie : QNetworkCookie) : boolean;
    function insertCookie (cookie : QNetworkCookie) : boolean;
    function setAllCookies (cookieList : QNetworkCookie[]) : void;
    function setCookiesFromUrl (cookieList : QNetworkCookie[], url : QUrl) : boolean;
    function updateCookie (cookie : QNetworkCookie) : boolean;
    function validateCookie (cookie : QNetworkCookie, url : QUrl) : boolean;
}
