/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QNetworkProxyFactory class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qnetworkproxy.jsx";
import "qt/qnetworkproxyquery.jsx";

native class QNetworkProxyFactory
{
    function constructor ();

    // Static Members
    static function proxyForQuery (query : QNetworkProxyQuery) : QNetworkProxy[];
    static function setApplicationProxyFactory (factory : QNetworkProxyFactory) : void;
    static function setUseSystemConfiguration (enable : boolean) : void;
    static function systemProxyForQuery (query : QNetworkProxyQuery) : QNetworkProxy[];

    // Methods
    function queryProxy (query : QNetworkProxyQuery) : QNetworkProxy[];
}
