/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QNetworkDiskCache class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractnetworkcache.jsx";
import "qt/qnetworkcachemetadata.jsx";
import "qt/qobject.jsx";

native class QNetworkDiskCache extends QAbstractNetworkCache
{
    function constructor (parent : QObject);

    // Methods
    function cacheDirectory () : string;
    function expire () : number;
    function fileMetaData (fileName : string) : QNetworkCacheMetaData;
    function maximumCacheSize () : number;
    function setCacheDirectory (cacheDir : string) : void;
    function setMaximumCacheSize (size : number) : void;
}
