/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPageSetupDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdialog.jsx";
import "qt/qobject.jsx";
import "qt/qprinter.jsx";
import "qt/qwidget.jsx";

native class QPageSetupDialog extends QDialog
{
    function constructor (printer : QPrinter, parent : QWidget);
    function constructor (parent : QWidget);

    // Methods
    function open (receiver : QObject, member : string) : void;
    function printer () : QPrinter;
}
