/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPaintDevice class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpaintengine.jsx";
import "qt/qpainter.jsx";
import "qt/qpoint.jsx";

final native class Qt_QPaintDevice_PaintDeviceMetric {}

native class QPaintDevice
{

    static const PdmWidth : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmHeight : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmWidthMM : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmHeightMM : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmNumColors : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmDepth : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmDpiX : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmDpiY : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmPhysicalDpiX : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmPhysicalDpiY : Qt_QPaintDevice_PaintDeviceMetric;
    static const PdmDevicePixelRatio : Qt_QPaintDevice_PaintDeviceMetric;
    static function PaintDeviceMetric(value : Qt_QPaintDevice_PaintDeviceMetric) : Qt_QPaintDevice_PaintDeviceMetric;

    // Methods
    function colorCount () : int;
    function depth () : int;
    function devType () : int;
    function devicePixelRatio () : int;
    function height () : int;
    function heightMM () : int;
    function initPainter (painter : QPainter) : void;
    function logicalDpiX () : int;
    function logicalDpiY () : int;
    function metric (metric : Qt_QPaintDevice_PaintDeviceMetric) : int;
    function paintEngine () : QPaintEngine;
    function paintingActive () : boolean;
    function physicalDpiX () : int;
    function physicalDpiY () : int;
    function redirected (offset : QPoint) : QPaintDevice;
    function sharedPainter () : QPainter;
    function width () : int;
    function widthMM () : int;
}
