/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPaintEngine class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qimage.jsx";
import "qt/qline.jsx";
import "qt/qlinef.jsx";
import "qt/qpaintdevice.jsx";
import "qt/qpaintenginestate.jsx";
import "qt/qpainter.jsx";
import "qt/qpainterpath.jsx";
import "qt/qpixmap.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qrect.jsx";
import "qt/qrectf.jsx";
import "qt/qregion.jsx";
import "qt/qt.jsx";
import "qt/qtextitem.jsx";

final native class Qt_QPaintEngine_Type {}

final native class Qt_QPaintEngine_DirtyFlag {}

final native class Qt_QPaintEngine_DirtyFlags {}

final native class Qt_QPaintEngine_PolygonDrawMode {}

final native class Qt_QPaintEngine_PaintEngineFeature {}

final native class Qt_QPaintEngine_PaintEngineFeatures {}

native class QPaintEngine
{
    function constructor (features : Qt_QPaintEngine_PaintEngineFeatures);

    static const X11 : Qt_QPaintEngine_Type;
    static const Windows : Qt_QPaintEngine_Type;
    static const QuickDraw : Qt_QPaintEngine_Type;
    static const CoreGraphics : Qt_QPaintEngine_Type;
    static const MacPrinter : Qt_QPaintEngine_Type;
    static const QWindowSystem : Qt_QPaintEngine_Type;
    static const PostScript : Qt_QPaintEngine_Type;
    static const OpenGL : Qt_QPaintEngine_Type;
    static const Picture : Qt_QPaintEngine_Type;
    static const SVG : Qt_QPaintEngine_Type;
    static const Raster : Qt_QPaintEngine_Type;
    static const Direct3D : Qt_QPaintEngine_Type;
    static const Pdf : Qt_QPaintEngine_Type;
    static const OpenVG : Qt_QPaintEngine_Type;
    static const OpenGL2 : Qt_QPaintEngine_Type;
    static const PaintBuffer : Qt_QPaintEngine_Type;
    static const Blitter : Qt_QPaintEngine_Type;
    static const User : Qt_QPaintEngine_Type;
    static const MaxUser : Qt_QPaintEngine_Type;
    static function Type(value : Qt_QPaintEngine_Type) : Qt_QPaintEngine_Type;

    static const DirtyPen : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBrush : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBrushOrigin : Qt_QPaintEngine_DirtyFlag;
    static const DirtyFont : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBackground : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBackgroundMode : Qt_QPaintEngine_DirtyFlag;
    static const DirtyTransform : Qt_QPaintEngine_DirtyFlag;
    static const DirtyClipRegion : Qt_QPaintEngine_DirtyFlag;
    static const DirtyClipPath : Qt_QPaintEngine_DirtyFlag;
    static const DirtyHints : Qt_QPaintEngine_DirtyFlag;
    static const DirtyCompositionMode : Qt_QPaintEngine_DirtyFlag;
    static const DirtyClipEnabled : Qt_QPaintEngine_DirtyFlag;
    static const DirtyOpacity : Qt_QPaintEngine_DirtyFlag;
    static const AllDirty : Qt_QPaintEngine_DirtyFlag;
    static function DirtyFlag(value : Qt_QPaintEngine_DirtyFlag) : Qt_QPaintEngine_DirtyFlag;
    static function DirtyFlags(...value : Qt_QPaintEngine_DirtyFlag) : Qt_QPaintEngine_DirtyFlags;

    static const OddEvenMode : Qt_QPaintEngine_PolygonDrawMode;
    static const WindingMode : Qt_QPaintEngine_PolygonDrawMode;
    static const ConvexMode : Qt_QPaintEngine_PolygonDrawMode;
    static const PolylineMode : Qt_QPaintEngine_PolygonDrawMode;
    static function PolygonDrawMode(value : Qt_QPaintEngine_PolygonDrawMode) : Qt_QPaintEngine_PolygonDrawMode;

    static const AllFeatures : Qt_QPaintEngine_PaintEngineFeature;
    static const PrimitiveTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const PatternTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const PixmapTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const PatternBrush : Qt_QPaintEngine_PaintEngineFeature;
    static const LinearGradientFill : Qt_QPaintEngine_PaintEngineFeature;
    static const RadialGradientFill : Qt_QPaintEngine_PaintEngineFeature;
    static const ConicalGradientFill : Qt_QPaintEngine_PaintEngineFeature;
    static const AlphaBlend : Qt_QPaintEngine_PaintEngineFeature;
    static const PorterDuff : Qt_QPaintEngine_PaintEngineFeature;
    static const PainterPaths : Qt_QPaintEngine_PaintEngineFeature;
    static const Antialiasing : Qt_QPaintEngine_PaintEngineFeature;
    static const BrushStroke : Qt_QPaintEngine_PaintEngineFeature;
    static const ConstantOpacity : Qt_QPaintEngine_PaintEngineFeature;
    static const MaskedBrush : Qt_QPaintEngine_PaintEngineFeature;
    static const PerspectiveTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const BlendModes : Qt_QPaintEngine_PaintEngineFeature;
    static const ObjectBoundingModeGradients : Qt_QPaintEngine_PaintEngineFeature;
    static const RasterOpModes : Qt_QPaintEngine_PaintEngineFeature;
    static const PaintOutsidePaintEvent : Qt_QPaintEngine_PaintEngineFeature;
    static function PaintEngineFeature(value : Qt_QPaintEngine_PaintEngineFeature) : Qt_QPaintEngine_PaintEngineFeature;
    static function PaintEngineFeatures(...value : Qt_QPaintEngine_PaintEngineFeature) : Qt_QPaintEngine_PaintEngineFeatures;

    // Methods
    function begin (pdev : QPaintDevice) : boolean;
    function clearDirty (df : Qt_QPaintEngine_DirtyFlags) : void;
    function coordinateOffset () : QPoint;
    function drawEllipse (r : QRect) : void;
    function drawEllipse (r : QRectF) : void;
    function drawImage (r : QRectF, pm : QImage, sr : QRectF, flags : Qt_ImageConversionFlags) : void;
    function drawLines (lines : QLine, lineCount : int) : void;
    function drawLines (lines : QLineF, lineCount : int) : void;
    function drawPath (path : QPainterPath) : void;
    function drawPixmap (r : QRectF, pm : QPixmap, sr : QRectF) : void;
    function drawPoints (points : QPoint, pointCount : int) : void;
    function drawPoints (points : QPointF, pointCount : int) : void;
    function drawPolygon (points : QPoint, pointCount : int, mode : Qt_QPaintEngine_PolygonDrawMode) : void;
    function drawPolygon (points : QPointF, pointCount : int, mode : Qt_QPaintEngine_PolygonDrawMode) : void;
    function drawRects (rects : QRect, rectCount : int) : void;
    function drawRects (rects : QRectF, rectCount : int) : void;
    function drawTextItem (p : QPointF, textItem : QTextItem) : void;
    function drawTiledPixmap (r : QRectF, pixmap : QPixmap, s : QPointF) : void;
    function end () : boolean;
    function hasFeature (feature : Qt_QPaintEngine_PaintEngineFeatures) : boolean;
    function isActive () : boolean;
    function isExtended () : boolean;
    function paintDevice () : QPaintDevice;
    function painter () : QPainter;
    function setActive (newState : boolean) : void;
    function setDirty (df : Qt_QPaintEngine_DirtyFlags) : void;
    function setSystemClip (baseClip : QRegion) : void;
    function setSystemRect (rect : QRect) : void;
    function syncState () : void;
    function systemClip () : QRegion;
    function systemRect () : QRect;
    function testDirty (df : Qt_QPaintEngine_DirtyFlags) : boolean;
    function type () : Qt_QPaintEngine_Type;
    function updateState (state : QPaintEngineState) : void;
}
