/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPanGesture class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgesture.jsx";
import "qt/qobject.jsx";
import "qt/qpointf.jsx";

native class QPanGesture extends QGesture
{
    function constructor (parent : QObject);

    // Instance Properties
    var lastOffset : QPointF;
    var offset : QPointF;
    var delta : QPointF;
    var acceleration : number;
}
