/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QParallelAnimationGroup class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qanimationgroup.jsx";
import "qt/qobject.jsx";

native class QParallelAnimationGroup extends QAnimationGroup
{
    function constructor (parent : QObject);
}
