/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPauseAnimation class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractanimation.jsx";
import "qt/qobject.jsx";

native class QPauseAnimation extends QAbstractAnimation
{
    function constructor (parent : QObject);
    function constructor (msecs : int, parent : QObject);

    // Instance Properties
}
