/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPixmapCache_Key class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QPixmapCache_Key
{
    function constructor ();
    function constructor (other : QPixmapCache_Key);

    // Methods
    function operator_assign (other : QPixmapCache_Key) : QPixmapCache_Key;
    function operator_equal (key : QPixmapCache_Key) : boolean;
}
