/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPoint class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QPoint
{
    function constructor ();
    function constructor (xpos : int, ypos : int);

    // Static Members
    static function dotProduct (p1 : QPoint, p2 : QPoint) : int;

    // Methods
    function isNull () : boolean;
    function manhattanLength () : int;
    function operator_add_assign (p : QPoint) : QPoint;
    function operator_divide_assign (divisor : number) : QPoint;
    function operator_equal (p2 : QPoint) : boolean;
    function operator_multiply_assign (factor : number) : QPoint;
    function operator_multiply_assign (factor : int) : QPoint;
    function operator_subtract_assign (p : QPoint) : QPoint;
    function setX (x : int) : void;
    function setY (y : int) : void;
    function x () : int;
    function y () : int;
}
