/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPointF class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpoint.jsx";

native class QPointF
{
    function constructor ();
    function constructor (p : QPoint);
    function constructor (xpos : number, ypos : number);

    // Static Members
    static function dotProduct (p1 : QPointF, p2 : QPointF) : number;

    // Methods
    function isNull () : boolean;
    function manhattanLength () : number;
    function operator_add_assign (p : QPointF) : QPointF;
    function operator_divide_assign (c : number) : QPointF;
    function operator_equal (p2 : QPointF) : boolean;
    function operator_multiply_assign (c : number) : QPointF;
    function operator_subtract_assign (p : QPointF) : QPointF;
    function setX (x : number) : void;
    function setY (y : number) : void;
    function toPoint () : QPoint;
    function x () : number;
    function y () : number;
}
