/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPrinter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpaintdevice.jsx";
import "qt/qpaintengine.jsx";
import "qt/qprintengine.jsx";
import "qt/qrect.jsx";
import "qt/qrectf.jsx";
import "qt/qsizef.jsx";

final native class Qt_QPrinter_PageOrder {}

final native class Qt_QPrinter_PrinterMode {}

final native class Qt_QPrinter_PrintRange {}

final native class Qt_QPrinter_Orientation {}

final native class Qt_QPrinter_ColorMode {}

final native class Qt_QPrinter_PaperSource {}

final native class Qt_QPrinter_Unit {}

final native class Qt_QPrinter_DuplexMode {}

final native class Qt_QPrinter_PrinterState {}

final native class Qt_QPrinter_OutputFormat {}

native class QPrinter
{
    function constructor (mode : Qt_QPrinter_PrinterMode);

    static const FirstPageFirst : Qt_QPrinter_PageOrder;
    static const LastPageFirst : Qt_QPrinter_PageOrder;
    static function PageOrder(value : Qt_QPrinter_PageOrder) : Qt_QPrinter_PageOrder;

    static const ScreenResolution : Qt_QPrinter_PrinterMode;
    static const PrinterResolution : Qt_QPrinter_PrinterMode;
    static const HighResolution : Qt_QPrinter_PrinterMode;
    static function PrinterMode(value : Qt_QPrinter_PrinterMode) : Qt_QPrinter_PrinterMode;

    static const AllPages : Qt_QPrinter_PrintRange;
    static const Selection : Qt_QPrinter_PrintRange;
    static const PageRange : Qt_QPrinter_PrintRange;
    static const CurrentPage : Qt_QPrinter_PrintRange;
    static function PrintRange(value : Qt_QPrinter_PrintRange) : Qt_QPrinter_PrintRange;

    static const Portrait : Qt_QPrinter_Orientation;
    static const Landscape : Qt_QPrinter_Orientation;
    static function Orientation(value : Qt_QPrinter_Orientation) : Qt_QPrinter_Orientation;

    static const GrayScale : Qt_QPrinter_ColorMode;
    static const Color : Qt_QPrinter_ColorMode;
    static function ColorMode(value : Qt_QPrinter_ColorMode) : Qt_QPrinter_ColorMode;

    static const OnlyOne : Qt_QPrinter_PaperSource;
    static const Lower : Qt_QPrinter_PaperSource;
    static const Middle : Qt_QPrinter_PaperSource;
    static const Manual : Qt_QPrinter_PaperSource;
    static const Envelope : Qt_QPrinter_PaperSource;
    static const EnvelopeManual : Qt_QPrinter_PaperSource;
    static const Auto : Qt_QPrinter_PaperSource;
    static const Tractor : Qt_QPrinter_PaperSource;
    static const SmallFormat : Qt_QPrinter_PaperSource;
    static const LargeFormat : Qt_QPrinter_PaperSource;
    static const LargeCapacity : Qt_QPrinter_PaperSource;
    static const Cassette : Qt_QPrinter_PaperSource;
    static const FormSource : Qt_QPrinter_PaperSource;
    static const MaxPageSource : Qt_QPrinter_PaperSource;
    static function PaperSource(value : Qt_QPrinter_PaperSource) : Qt_QPrinter_PaperSource;

    static const Millimeter : Qt_QPrinter_Unit;
    static const Point : Qt_QPrinter_Unit;
    static const Inch : Qt_QPrinter_Unit;
    static const Pica : Qt_QPrinter_Unit;
    static const Didot : Qt_QPrinter_Unit;
    static const Cicero : Qt_QPrinter_Unit;
    static const DevicePixel : Qt_QPrinter_Unit;
    static function Unit(value : Qt_QPrinter_Unit) : Qt_QPrinter_Unit;

    static const DuplexNone : Qt_QPrinter_DuplexMode;
    static const DuplexAuto : Qt_QPrinter_DuplexMode;
    static const DuplexLongSide : Qt_QPrinter_DuplexMode;
    static const DuplexShortSide : Qt_QPrinter_DuplexMode;
    static function DuplexMode(value : Qt_QPrinter_DuplexMode) : Qt_QPrinter_DuplexMode;

    static const Idle : Qt_QPrinter_PrinterState;
    static const Active : Qt_QPrinter_PrinterState;
    static const Aborted : Qt_QPrinter_PrinterState;
    static const Error : Qt_QPrinter_PrinterState;
    static function PrinterState(value : Qt_QPrinter_PrinterState) : Qt_QPrinter_PrinterState;

    static const NativeFormat : Qt_QPrinter_OutputFormat;
    static const PdfFormat : Qt_QPrinter_OutputFormat;
    static function OutputFormat(value : Qt_QPrinter_OutputFormat) : Qt_QPrinter_OutputFormat;

    // Methods
    function abort () : boolean;
    function actualNumCopies () : int;
    function collateCopies () : boolean;
    function colorMode () : Qt_QPrinter_ColorMode;
    function copyCount () : int;
    function creator () : string;
    function devType () : int;
    function docName () : string;
    function doubleSidedPrinting () : boolean;
    function duplex () : Qt_QPrinter_DuplexMode;
    function fontEmbeddingEnabled () : boolean;
    function fromPage () : int;
    function fullPage () : boolean;
    function getPageMargins (left : number, top : number, right : number, bottom : number, unit : Qt_QPrinter_Unit) : void;
    function isValid () : boolean;
    function metric (arg__1 : Qt_QPaintDevice_PaintDeviceMetric) : int;
    function newPage () : boolean;
    function numCopies () : int;
    function orientation () : Qt_QPrinter_Orientation;
    function outputFileName () : string;
    function outputFormat () : Qt_QPrinter_OutputFormat;
    function pageOrder () : Qt_QPrinter_PageOrder;
    function pageRect () : QRect;
    function pageRect (arg__1 : Qt_QPrinter_Unit) : QRectF;
    function paintEngine () : QPaintEngine;
    function paperName () : string;
    function paperRect () : QRect;
    function paperRect (arg__1 : Qt_QPrinter_Unit) : QRectF;
    function paperSize (unit : Qt_QPrinter_Unit) : QSizeF;
    function paperSource () : Qt_QPrinter_PaperSource;
    function printEngine () : QPrintEngine;
    function printProgram () : string;
    function printRange () : Qt_QPrinter_PrintRange;
    function printerName () : string;
    function printerState () : Qt_QPrinter_PrinterState;
    function resolution () : int;
    function setCollateCopies (collate : boolean) : void;
    function setColorMode (arg__1 : Qt_QPrinter_ColorMode) : void;
    function setCopyCount (arg__1 : int) : void;
    function setCreator (arg__1 : string) : void;
    function setDocName (arg__1 : string) : void;
    function setDoubleSidedPrinting (enable : boolean) : void;
    function setDuplex (duplex : Qt_QPrinter_DuplexMode) : void;
    function setEngines (printEngine : QPrintEngine, paintEngine : QPaintEngine) : void;
    function setFontEmbeddingEnabled (enable : boolean) : void;
    function setFromTo (fromPage : int, toPage : int) : void;
    function setFullPage (arg__1 : boolean) : void;
    function setNumCopies (arg__1 : int) : void;
    function setOrientation (arg__1 : Qt_QPrinter_Orientation) : void;
    function setOutputFileName (arg__1 : string) : void;
    function setOutputFormat (format : Qt_QPrinter_OutputFormat) : void;
    function setPageMargins (left : number, top : number, right : number, bottom : number, unit : Qt_QPrinter_Unit) : void;
    function setPageOrder (arg__1 : Qt_QPrinter_PageOrder) : void;
    function setPageSizeMM (size : QSizeF) : void;
    function setPaperName (paperName : string) : void;
    function setPaperSize (paperSize : QSizeF, unit : Qt_QPrinter_Unit) : void;
    function setPaperSource (arg__1 : Qt_QPrinter_PaperSource) : void;
    function setPrintProgram (arg__1 : string) : void;
    function setPrintRange (range : Qt_QPrinter_PrintRange) : void;
    function setPrinterName (arg__1 : string) : void;
    function setResolution (arg__1 : int) : void;
    function supportedResolutions () : int[];
    function supportsMultipleCopies () : boolean;
    function toPage () : int;
}
