/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPrintEngine class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpaintdevice.jsx";
import "qt/qprinter.jsx";

final native class Qt_QPrintEngine_PrintEnginePropertyKey {}

native class QPrintEngine
{
    function constructor ();

    static const PPK_CollateCopies : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_ColorMode : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_Creator : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_DocumentName : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_FullPage : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_NumberOfCopies : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_Orientation : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_OutputFileName : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PageOrder : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PageRect : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PageSize : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PaperRect : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PaperSource : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PrinterName : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PrinterProgram : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_Resolution : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_SelectionOption : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_SupportedResolutions : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_WindowsPageSize : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_FontEmbedding : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_Duplex : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PaperSources : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_CustomPaperSize : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PageMargins : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_CopyCount : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_SupportsMultipleCopies : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_PaperName : Qt_QPrintEngine_PrintEnginePropertyKey;
    static const PPK_CustomBase : Qt_QPrintEngine_PrintEnginePropertyKey;
    static function PrintEnginePropertyKey(value : Qt_QPrintEngine_PrintEnginePropertyKey) : Qt_QPrintEngine_PrintEnginePropertyKey;

    // Methods
    function abort () : boolean;
    function metric (arg__1 : Qt_QPaintDevice_PaintDeviceMetric) : int;
    function newPage () : boolean;
    function printerState () : Qt_QPrinter_PrinterState;
    function property (key : Qt_QPrintEngine_PrintEnginePropertyKey) : variant;
    function setProperty (key : Qt_QPrintEngine_PrintEnginePropertyKey, value : variant) : void;
}
