/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPropertyAnimation class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qobject.jsx";
import "qt/qvariantanimation.jsx";

native class QPropertyAnimation extends QVariantAnimation
{
    function constructor (parent : QObject);
    function constructor (target : QObject, propertyName : QByteArray, parent : QObject);

    // Instance Properties
    var propertyName : QByteArray;
    var targetObject : QObject;
}
