/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QProcessEnvironment class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QProcessEnvironment
{
    function constructor ();
    function constructor (other : QProcessEnvironment);

    // Static Members
    static function systemEnvironment () : QProcessEnvironment;

    // Methods
    function clear () : void;
    function contains (name : string) : boolean;
    function insert (e : QProcessEnvironment) : void;
    function insert (name : string, value : string) : void;
    function isEmpty () : boolean;
    function keys () : string[];
    function operator_assign (other : QProcessEnvironment) : QProcessEnvironment;
    function operator_equal (other : QProcessEnvironment) : boolean;
    function remove (name : string) : void;
    function swap (other : QProcessEnvironment) : void;
    function toStringList () : string[];
    function value (name : string, defaultValue : string) : string;
}
