/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPushButton class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractbutton.jsx";
import "qt/qicon.jsx";
import "qt/qmenu.jsx";
import "qt/qstyleoptionbutton.jsx";
import "qt/qwidget.jsx";

native class QPushButton extends QAbstractButton
{
    function constructor (parent : QWidget);
    function constructor (icon : QIcon, text : string, parent : QWidget);
    function constructor (text : string, parent : QWidget);

    // Methods
    function initStyleOption (option : QStyleOptionButton) : void;
    function menu () : QMenu;
    function setMenu (menu : QMenu) : void;

    // Slots
    function showMenu () : void;

    // Instance Properties
    var autoDefault : boolean;
    var default : boolean;
    var flat : boolean;
}
