/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QRegExpValidator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qvalidator.jsx";
import "qt/_signals.jsx";

native class QRegExpValidator extends QValidator
{
    function constructor (parent : QObject);
    function constructor (rx : RegExp, parent : QObject);

    // Signals
    var regExpChanged : QtJSXQRegExpSignal;

    // Instance Properties
    var regExp : RegExp;
}
