/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QShortcutEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qkeysequence.jsx";

native class QShortcutEvent extends QEvent
{
    function constructor (key : QKeySequence, id : int, ambiguous : boolean);

    // Methods
    function isAmbiguous () : boolean;
    function key () : QKeySequence;
    function shortcutId () : int;
}
