/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QShowEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";

native class QShowEvent extends QEvent
{
    function constructor ();
}
