/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSound class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";

final native class Qt_QSound_Loop {}

native class QSound extends QObject
{
    function constructor (filename : string, parent : QObject);

    // Static Members
    static function play (filename : string) : void;

    static const Infinite : Qt_QSound_Loop;
    static function Loop(value : Qt_QSound_Loop) : Qt_QSound_Loop;

    // Methods
    function fileName () : string;
    function isFinished () : boolean;
    function loops () : int;
    function loopsRemaining () : int;
    function setLoops (arg__1 : int) : void;

    // Slots
    function play () : void;
    function stop () : void;
}
