/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSplitterHandle class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsplitter.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";

native class QSplitterHandle extends QWidget
{
    function constructor (o : Qt_Orientation, parent : QSplitter);

    // Methods
    function closestLegalPosition (p : int) : int;
    function moveSplitter (p : int) : void;
    function opaqueResize () : boolean;
    function orientation () : Qt_Orientation;
    function setOrientation (o : Qt_Orientation) : void;
    function splitter () : QSplitter;
}
