/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSsl namespace
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QSsl_EncodingFormat {}

final native class Qt_QSsl_KeyAlgorithm {}

final native class Qt_QSsl_SslProtocol {}

final native class Qt_QSsl_KeyType {}

native class QSsl
{

    static const Pem : Qt_QSsl_EncodingFormat;
    static const Der : Qt_QSsl_EncodingFormat;
    static function EncodingFormat(value : Qt_QSsl_EncodingFormat) : Qt_QSsl_EncodingFormat;

    static const Opaque : Qt_QSsl_KeyAlgorithm;
    static const Rsa : Qt_QSsl_KeyAlgorithm;
    static const Dsa : Qt_QSsl_KeyAlgorithm;
    static function KeyAlgorithm(value : Qt_QSsl_KeyAlgorithm) : Qt_QSsl_KeyAlgorithm;

    static const UnknownProtocol : Qt_QSsl_SslProtocol;
    static const SslV3 : Qt_QSsl_SslProtocol;
    static const SslV2 : Qt_QSsl_SslProtocol;
    static const TlsV1_0 : Qt_QSsl_SslProtocol;
    static const TlsV1_1 : Qt_QSsl_SslProtocol;
    static const TlsV1_2 : Qt_QSsl_SslProtocol;
    static const AnyProtocol : Qt_QSsl_SslProtocol;
    static const TlsV1SslV3 : Qt_QSsl_SslProtocol;
    static const SecureProtocols : Qt_QSsl_SslProtocol;
    static function SslProtocol(value : Qt_QSsl_SslProtocol) : Qt_QSsl_SslProtocol;

    static const PrivateKey : Qt_QSsl_KeyType;
    static const PublicKey : Qt_QSsl_KeyType;
    static function KeyType(value : Qt_QSsl_KeyType) : Qt_QSsl_KeyType;
}
