/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSslKey class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qiodevice.jsx";
import "qt/qssl.jsx";

native class QSslKey
{
    function constructor ();
    function constructor (device : QIODevice, algorithm : Qt_QSsl_KeyAlgorithm, format : Qt_QSsl_EncodingFormat, type : Qt_QSsl_KeyType, passPhrase : QByteArray);
    function constructor (encoded : QByteArray, algorithm : Qt_QSsl_KeyAlgorithm, format : Qt_QSsl_EncodingFormat, type : Qt_QSsl_KeyType, passPhrase : QByteArray);
    function constructor (other : QSslKey);

    // Methods
    function algorithm () : Qt_QSsl_KeyAlgorithm;
    function clear () : void;
    function isNull () : boolean;
    function length () : int;
    function operator_assign (other : QSslKey) : QSslKey;
    function operator_equal (key : QSslKey) : boolean;
    function swap (other : QSslKey) : void;
    function toDer (passPhrase : QByteArray) : QByteArray;
    function toPem (passPhrase : QByteArray) : QByteArray;
    function type () : Qt_QSsl_KeyType;
}
