/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QState class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractstate.jsx";
import "qt/qabstracttransition.jsx";
import "qt/qobject.jsx";
import "qt/qsignaltransition.jsx";

final native class Qt_QState_ChildMode {}

native class QState extends QAbstractState
{
    function constructor (parent : QState);
    function constructor (childMode : Qt_QState_ChildMode, parent : QState);

    static const ExclusiveStates : Qt_QState_ChildMode;
    static const ParallelStates : Qt_QState_ChildMode;
    static function ChildMode(value : Qt_QState_ChildMode) : Qt_QState_ChildMode;

    // Methods
    function addTransition (target : QAbstractState) : QAbstractTransition;
    function addTransition (transition : QAbstractTransition) : void;
    function addTransition (sender : QObject, signal : string, target : QAbstractState) : QSignalTransition;
    function assignProperty (object : QObject, name : string, value : variant) : void;
    function removeTransition (transition : QAbstractTransition) : void;
    function transitions () : QAbstractTransition[];

    // Instance Properties
    var initialState : QAbstractState;
    var errorState : QAbstractState;
    var childMode : Qt_QState_ChildMode;
}
