/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStatusTipEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";

native class QStatusTipEvent extends QEvent
{
    function constructor (tip : string);

    // Methods
    function tip () : string;
}
