/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStateMachine_SignalEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qobject.jsx";

native class QStateMachine_SignalEvent extends QEvent
{
    function constructor (sender : QObject, signalIndex : int, arguments : variant[]);

    // Methods
    function arguments () : variant[];
    function sender () : QObject;
    function signalIndex () : int;
}
