/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyleOptionToolButton class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoptioncomplex.jsx";

final native class Qt_QStyleOptionToolButton_StyleOptionVersion {}

final native class Qt_QStyleOptionToolButton_ToolButtonFeature {}

final native class Qt_QStyleOptionToolButton_ToolButtonFeatures {}

final native class Qt_QStyleOptionToolButton_StyleOptionType {}

native class QStyleOptionToolButton extends QStyleOptionComplex
{
    function constructor ();
    function constructor (other : QStyleOptionToolButton);

    static const Version : Qt_QStyleOptionToolButton_StyleOptionVersion;
    static function StyleOptionVersion(value : Qt_QStyleOptionToolButton_StyleOptionVersion) : Qt_QStyleOptionToolButton_StyleOptionVersion;

    static const None : Qt_QStyleOptionToolButton_ToolButtonFeature;
    static const Arrow : Qt_QStyleOptionToolButton_ToolButtonFeature;
    static const Menu : Qt_QStyleOptionToolButton_ToolButtonFeature;
    static const PopupDelay : Qt_QStyleOptionToolButton_ToolButtonFeature;
    static const HasMenu : Qt_QStyleOptionToolButton_ToolButtonFeature;
    static function ToolButtonFeature(value : Qt_QStyleOptionToolButton_ToolButtonFeature) : Qt_QStyleOptionToolButton_ToolButtonFeature;
    static function ToolButtonFeatures(...value : Qt_QStyleOptionToolButton_ToolButtonFeature) : Qt_QStyleOptionToolButton_ToolButtonFeatures;

    static const Type : Qt_QStyleOptionToolButton_StyleOptionType;
    static function StyleOptionType(value : Qt_QStyleOptionToolButton_StyleOptionType) : Qt_QStyleOptionToolButton_StyleOptionType;
}
