/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyledItemDelegate class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemdelegate.jsx";
import "qt/qitemeditorfactory.jsx";
import "qt/qlocale.jsx";
import "qt/qmodelindex.jsx";
import "qt/qobject.jsx";
import "qt/qstyleoptionviewitem.jsx";

native class QStyledItemDelegate extends QAbstractItemDelegate
{
    function constructor (parent : QObject);

    // Methods
    function displayText (value : variant, locale : QLocale) : string;
    function initStyleOption (option : QStyleOptionViewItem, index : QModelIndex) : void;
    function itemEditorFactory () : QItemEditorFactory;
    function setItemEditorFactory (factory : QItemEditorFactory) : void;
}
