/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyleOptionProgressBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoption.jsx";

final native class Qt_QStyleOptionProgressBar_StyleOptionVersion {}

final native class Qt_QStyleOptionProgressBar_StyleOptionType {}

native class QStyleOptionProgressBar extends QStyleOption
{
    function constructor ();
    function constructor (other : QStyleOptionProgressBar);

    static const Version : Qt_QStyleOptionProgressBar_StyleOptionVersion;
    static function StyleOptionVersion(value : Qt_QStyleOptionProgressBar_StyleOptionVersion) : Qt_QStyleOptionProgressBar_StyleOptionVersion;

    static const Type : Qt_QStyleOptionProgressBar_StyleOptionType;
    static function StyleOptionType(value : Qt_QStyleOptionProgressBar_StyleOptionType) : Qt_QStyleOptionProgressBar_StyleOptionType;
}
