/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStylePlugin class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qstyle.jsx";

native class QStylePlugin extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function create (key : string) : QStyle;
}
