/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyleOptionHeader class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoption.jsx";

final native class Qt_QStyleOptionHeader_StyleOptionVersion {}

final native class Qt_QStyleOptionHeader_SelectedPosition {}

final native class Qt_QStyleOptionHeader_SortIndicator {}

final native class Qt_QStyleOptionHeader_StyleOptionType {}

final native class Qt_QStyleOptionHeader_SectionPosition {}

native class QStyleOptionHeader extends QStyleOption
{
    function constructor ();
    function constructor (other : QStyleOptionHeader);

    static const Version : Qt_QStyleOptionHeader_StyleOptionVersion;
    static function StyleOptionVersion(value : Qt_QStyleOptionHeader_StyleOptionVersion) : Qt_QStyleOptionHeader_StyleOptionVersion;

    static const NotAdjacent : Qt_QStyleOptionHeader_SelectedPosition;
    static const NextIsSelected : Qt_QStyleOptionHeader_SelectedPosition;
    static const PreviousIsSelected : Qt_QStyleOptionHeader_SelectedPosition;
    static const NextAndPreviousAreSelected : Qt_QStyleOptionHeader_SelectedPosition;
    static function SelectedPosition(value : Qt_QStyleOptionHeader_SelectedPosition) : Qt_QStyleOptionHeader_SelectedPosition;

    static const None : Qt_QStyleOptionHeader_SortIndicator;
    static const SortUp : Qt_QStyleOptionHeader_SortIndicator;
    static const SortDown : Qt_QStyleOptionHeader_SortIndicator;
    static function SortIndicator(value : Qt_QStyleOptionHeader_SortIndicator) : Qt_QStyleOptionHeader_SortIndicator;

    static const Type : Qt_QStyleOptionHeader_StyleOptionType;
    static function StyleOptionType(value : Qt_QStyleOptionHeader_StyleOptionType) : Qt_QStyleOptionHeader_StyleOptionType;

    static const Beginning : Qt_QStyleOptionHeader_SectionPosition;
    static const Middle : Qt_QStyleOptionHeader_SectionPosition;
    static const End : Qt_QStyleOptionHeader_SectionPosition;
    static const OnlyOneSection : Qt_QStyleOptionHeader_SectionPosition;
    static function SectionPosition(value : Qt_QStyleOptionHeader_SectionPosition) : Qt_QStyleOptionHeader_SectionPosition;
}
