/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyleOptionFrame class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoption.jsx";

final native class Qt_QStyleOptionFrame_StyleOptionVersion {}

final native class Qt_QStyleOptionFrame_StyleOptionType {}

final native class Qt_QStyleOptionFrame_FrameFeature {}

final native class Qt_QStyleOptionFrame_FrameFeatures {}

native class QStyleOptionFrame extends QStyleOption
{
    function constructor ();
    function constructor (other : QStyleOptionFrame);

    static const Version : Qt_QStyleOptionFrame_StyleOptionVersion;
    static function StyleOptionVersion(value : Qt_QStyleOptionFrame_StyleOptionVersion) : Qt_QStyleOptionFrame_StyleOptionVersion;

    static const Type : Qt_QStyleOptionFrame_StyleOptionType;
    static function StyleOptionType(value : Qt_QStyleOptionFrame_StyleOptionType) : Qt_QStyleOptionFrame_StyleOptionType;

    static const None : Qt_QStyleOptionFrame_FrameFeature;
    static const Flat : Qt_QStyleOptionFrame_FrameFeature;
    static const Rounded : Qt_QStyleOptionFrame_FrameFeature;
    static function FrameFeature(value : Qt_QStyleOptionFrame_FrameFeature) : Qt_QStyleOptionFrame_FrameFeature;
    static function FrameFeatures(...value : Qt_QStyleOptionFrame_FrameFeature) : Qt_QStyleOptionFrame_FrameFeatures;
}
