/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyleOptionComplex class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoption.jsx";

final native class Qt_QStyleOptionComplex_StyleOptionVersion {}

final native class Qt_QStyleOptionComplex_StyleOptionType {}

native class QStyleOptionComplex extends QStyleOption
{
    function constructor (other : QStyleOptionComplex);
    function constructor (version : int, type : int);

    static const Version : Qt_QStyleOptionComplex_StyleOptionVersion;
    static function StyleOptionVersion(value : Qt_QStyleOptionComplex_StyleOptionVersion) : Qt_QStyleOptionComplex_StyleOptionVersion;

    static const Type : Qt_QStyleOptionComplex_StyleOptionType;
    static function StyleOptionType(value : Qt_QStyleOptionComplex_StyleOptionType) : Qt_QStyleOptionComplex_StyleOptionType;
}
