/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgRenderer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qmatrix.jsx";
import "qt/qobject.jsx";
import "qt/qpainter.jsx";
import "qt/qrectf.jsx";
import "qt/qsize.jsx";
import "qt/qxmlstreamreader.jsx";
import "qt/_signals.jsx";

native class QSvgRenderer extends QObject
{
    function constructor (parent : QObject);
    function constructor (contents : QXmlStreamReader, parent : QObject);
    function constructor (contents : QByteArray, parent : QObject);
    function constructor (filename : string, parent : QObject);

    // Methods
    function animated () : boolean;
    function animationDuration () : int;
    function boundsOnElement (id : string) : QRectF;
    function defaultSize () : QSize;
    function elementExists (id : string) : boolean;
    function isValid () : boolean;
    function matrixForElement (id : string) : QMatrix;

    // Slots
    function load (contents : QXmlStreamReader) : boolean;
    function load (contents : QByteArray) : boolean;
    function load (filename : string) : boolean;
    function render (p : QPainter) : void;
    function render (p : QPainter, bounds : QRectF) : void;
    function render (p : QPainter, elementId : string, bounds : QRectF) : void;

    // Signals
    var repaintNeeded : QtJSXSignal;

    // Instance Properties
    var viewBox : QRectF;
    var framesPerSecond : int;
    var currentFrame : int;
}
