/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgGenerator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qiodevice.jsx";
import "qt/qpaintdevice.jsx";
import "qt/qrectf.jsx";
import "qt/qsize.jsx";

native class QSvgGenerator extends QPaintDevice
{
    function constructor ();

    // Methods

    // Instance Properties
    var size : QSize;
    var viewBox : QRectF;
    var title : string;
    var description : string;
    var fileName : string;
    var outputDevice : QIODevice;
    var resolution : int;
}
