/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qsvgrenderer.jsx";
import "qt/qwidget.jsx";

native class QSvgWidget extends QWidget
{
    function constructor (parent : QWidget);
    function constructor (file : string, parent : QWidget);

    // Methods
    function renderer () : QSvgRenderer;

    // Slots
    function load (contents : QByteArray) : void;
    function load (file : string) : void;
}
