/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSystemSemaphore class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QSystemSemaphore_AccessMode {}

final native class Qt_QSystemSemaphore_SystemSemaphoreError {}

native class QSystemSemaphore
{
    function constructor (key : string, initialValue : int, mode : Qt_QSystemSemaphore_AccessMode);

    static const Open : Qt_QSystemSemaphore_AccessMode;
    static const Create : Qt_QSystemSemaphore_AccessMode;
    static function AccessMode(value : Qt_QSystemSemaphore_AccessMode) : Qt_QSystemSemaphore_AccessMode;

    static const NoError : Qt_QSystemSemaphore_SystemSemaphoreError;
    static const PermissionDenied : Qt_QSystemSemaphore_SystemSemaphoreError;
    static const KeyError : Qt_QSystemSemaphore_SystemSemaphoreError;
    static const AlreadyExists : Qt_QSystemSemaphore_SystemSemaphoreError;
    static const NotFound : Qt_QSystemSemaphore_SystemSemaphoreError;
    static const OutOfResources : Qt_QSystemSemaphore_SystemSemaphoreError;
    static const UnknownError : Qt_QSystemSemaphore_SystemSemaphoreError;
    static function SystemSemaphoreError(value : Qt_QSystemSemaphore_SystemSemaphoreError) : Qt_QSystemSemaphore_SystemSemaphoreError;

    // Methods
    function acquire () : boolean;
    function error () : Qt_QSystemSemaphore_SystemSemaphoreError;
    function errorString () : string;
    function key () : string;
    function release (n : int) : boolean;
    function setKey (key : string, initialValue : int, mode : Qt_QSystemSemaphore_AccessMode) : void;
}
