/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * Qt namespace
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_BrushStyle {}

final native class Qt_LayoutDirection {}

final native class Qt_Corner {}

final native class Qt_ClipOperation {}

final native class Qt_ItemDataRole {}

final native class Qt_ContextMenuPolicy {}

final native class Qt_PenStyle {}

final native class Qt_TextFlag {}

final native class Qt_WindowState {}

final native class Qt_WindowStates {}

final native class Qt_TextFormat {}

final native class Qt_SizeHint {}

final native class Qt_GestureType {}

final native class Qt_ConnectionType {}

final native class Qt_ItemFlag {}

final native class Qt_ItemFlags {}

final native class Qt_SortOrder {}

final native class Qt_ShortcutContext {}

final native class Qt_GestureState {}

final native class Qt_UIEffect {}

final native class Qt_DayOfWeek {}

final native class Qt_ItemSelectionMode {}

final native class Qt_TransformationMode {}

final native class Qt_AspectRatioMode {}

final native class Qt_CoordinateSystem {}

final native class Qt_Orientation {}

final native class Qt_Orientations {}

final native class Qt_ApplicationAttribute {}

final native class Qt_GlobalColor {}

final native class Qt_CheckState {}

final native class Qt_TileRule {}

final native class Qt_ToolBarArea {}

final native class Qt_ToolBarAreas {}

final native class Qt_WidgetAttribute {}

final native class Qt_KeyboardModifier {}

final native class Qt_KeyboardModifiers {}

final native class Qt_DockWidgetAreaSizes {}

final native class Qt_BGMode {}

final native class Qt_MatchFlag {}

final native class Qt_MatchFlags {}

final native class Qt_TimerType {}

final native class Qt_MouseButton {}

final native class Qt_MouseButtons {}

final native class Qt_DockWidgetArea {}

final native class Qt_DockWidgetAreas {}

final native class Qt_AnchorPoint {}

final native class Qt_GestureFlag {}

final native class Qt_GestureFlags {}

final native class Qt_WindowType {}

final native class Qt_WindowFlags {}

final native class Qt_Key {}

final native class Qt_TextElideMode {}

final native class Qt_FindChildOption {}

final native class Qt_ArrowType {}

final native class Qt_PenCapStyle {}

final native class Qt_CaseSensitivity {}

final native class Qt_FillRule {}

final native class Qt_TimeSpec {}

final native class Qt_ScreenOrientation {}

final native class Qt_ScrollBarPolicy {}

final native class Qt_CursorShape {}

final native class Qt_ImageConversionFlag {}

final native class Qt_ImageConversionFlags {}

final native class Qt_MaskMode {}

final native class Qt_ToolBarAreaSizes {}

final native class Qt_SizeMode {}

final native class Qt_TouchPointState {}

final native class Qt_TouchPointStates {}

final native class Qt_CursorMoveStyle {}

final native class Qt_InputMethodHint {}

final native class Qt_InputMethodHints {}

final native class Qt_Axis {}

final native class Qt_NavigationMode {}

final native class Qt_AlignmentFlag {}

final native class Qt_Alignment {}

final native class Qt_InputMethodQuery {}

final native class Qt_HitTestAccuracy {}

final native class Qt_FocusPolicy {}

final native class Qt_WindowModality {}

final native class Qt_PenJoinStyle {}

final native class Qt_EventPriority {}

final native class Qt_FocusReason {}

final native class Qt_TextInteractionFlag {}

final native class Qt_TextInteractionFlags {}

final native class Qt_DateFormat {}

final native class Qt_ToolButtonStyle {}

final native class Qt_WindowFrameSection {}

final native class Qt_WhiteSpaceMode {}

final native class Qt_DropAction {}

final native class Qt_DropActions {}

native class Qt
{

    static const NoBrush : Qt_BrushStyle;
    static const SolidPattern : Qt_BrushStyle;
    static const Dense1Pattern : Qt_BrushStyle;
    static const Dense2Pattern : Qt_BrushStyle;
    static const Dense3Pattern : Qt_BrushStyle;
    static const Dense4Pattern : Qt_BrushStyle;
    static const Dense5Pattern : Qt_BrushStyle;
    static const Dense6Pattern : Qt_BrushStyle;
    static const Dense7Pattern : Qt_BrushStyle;
    static const HorPattern : Qt_BrushStyle;
    static const VerPattern : Qt_BrushStyle;
    static const CrossPattern : Qt_BrushStyle;
    static const BDiagPattern : Qt_BrushStyle;
    static const FDiagPattern : Qt_BrushStyle;
    static const DiagCrossPattern : Qt_BrushStyle;
    static const LinearGradientPattern : Qt_BrushStyle;
    static const RadialGradientPattern : Qt_BrushStyle;
    static const ConicalGradientPattern : Qt_BrushStyle;
    static const TexturePattern : Qt_BrushStyle;
    static function BrushStyle(value : Qt_BrushStyle) : Qt_BrushStyle;

    static const LeftToRight : Qt_LayoutDirection;
    static const RightToLeft : Qt_LayoutDirection;
    static const LayoutDirectionAuto : Qt_LayoutDirection;
    static function LayoutDirection(value : Qt_LayoutDirection) : Qt_LayoutDirection;

    static const TopLeftCorner : Qt_Corner;
    static const TopRightCorner : Qt_Corner;
    static const BottomLeftCorner : Qt_Corner;
    static const BottomRightCorner : Qt_Corner;
    static function Corner(value : Qt_Corner) : Qt_Corner;

    static const NoClip : Qt_ClipOperation;
    static const ReplaceClip : Qt_ClipOperation;
    static const IntersectClip : Qt_ClipOperation;
    static function ClipOperation(value : Qt_ClipOperation) : Qt_ClipOperation;

    static const DisplayRole : Qt_ItemDataRole;
    static const DecorationRole : Qt_ItemDataRole;
    static const EditRole : Qt_ItemDataRole;
    static const ToolTipRole : Qt_ItemDataRole;
    static const StatusTipRole : Qt_ItemDataRole;
    static const WhatsThisRole : Qt_ItemDataRole;
    static const FontRole : Qt_ItemDataRole;
    static const TextAlignmentRole : Qt_ItemDataRole;
    static const BackgroundColorRole : Qt_ItemDataRole;
    static const TextColorRole : Qt_ItemDataRole;
    static const CheckStateRole : Qt_ItemDataRole;
    static const AccessibleTextRole : Qt_ItemDataRole;
    static const AccessibleDescriptionRole : Qt_ItemDataRole;
    static const SizeHintRole : Qt_ItemDataRole;
    static const InitialSortOrderRole : Qt_ItemDataRole;
    static const DisplayPropertyRole : Qt_ItemDataRole;
    static const DecorationPropertyRole : Qt_ItemDataRole;
    static const ToolTipPropertyRole : Qt_ItemDataRole;
    static const StatusTipPropertyRole : Qt_ItemDataRole;
    static const WhatsThisPropertyRole : Qt_ItemDataRole;
    static const UserRole : Qt_ItemDataRole;
    static function ItemDataRole(value : Qt_ItemDataRole) : Qt_ItemDataRole;

    static const NoContextMenu : Qt_ContextMenuPolicy;
    static const DefaultContextMenu : Qt_ContextMenuPolicy;
    static const ActionsContextMenu : Qt_ContextMenuPolicy;
    static const CustomContextMenu : Qt_ContextMenuPolicy;
    static const PreventContextMenu : Qt_ContextMenuPolicy;
    static function ContextMenuPolicy(value : Qt_ContextMenuPolicy) : Qt_ContextMenuPolicy;

    static const NoPen : Qt_PenStyle;
    static const SolidLine : Qt_PenStyle;
    static const DashLine : Qt_PenStyle;
    static const DotLine : Qt_PenStyle;
    static const DashDotLine : Qt_PenStyle;
    static const DashDotDotLine : Qt_PenStyle;
    static const CustomDashLine : Qt_PenStyle;
    static const MPenStyle : Qt_PenStyle;
    static function PenStyle(value : Qt_PenStyle) : Qt_PenStyle;

    static const TextSingleLine : Qt_TextFlag;
    static const TextDontClip : Qt_TextFlag;
    static const TextExpandTabs : Qt_TextFlag;
    static const TextShowMnemonic : Qt_TextFlag;
    static const TextWordWrap : Qt_TextFlag;
    static const TextWrapAnywhere : Qt_TextFlag;
    static const TextDontPrint : Qt_TextFlag;
    static const TextHideMnemonic : Qt_TextFlag;
    static const TextJustificationForced : Qt_TextFlag;
    static const TextForceLeftToRight : Qt_TextFlag;
    static const TextForceRightToLeft : Qt_TextFlag;
    static const TextLongestVariant : Qt_TextFlag;
    static const TextBypassShaping : Qt_TextFlag;
    static const TextIncludeTrailingSpaces : Qt_TextFlag;
    static function TextFlag(value : Qt_TextFlag) : Qt_TextFlag;

    static const WindowNoState : Qt_WindowState;
    static const WindowMinimized : Qt_WindowState;
    static const WindowMaximized : Qt_WindowState;
    static const WindowFullScreen : Qt_WindowState;
    static const WindowActive : Qt_WindowState;
    static function WindowState(value : Qt_WindowState) : Qt_WindowState;
    static function WindowStates(...value : Qt_WindowState) : Qt_WindowStates;

    static const PlainText : Qt_TextFormat;
    static const RichText : Qt_TextFormat;
    static const AutoText : Qt_TextFormat;
    static function TextFormat(value : Qt_TextFormat) : Qt_TextFormat;

    static const MinimumSize : Qt_SizeHint;
    static const PreferredSize : Qt_SizeHint;
    static const MaximumSize : Qt_SizeHint;
    static const MinimumDescent : Qt_SizeHint;
    static const NSizeHints : Qt_SizeHint;
    static function SizeHint(value : Qt_SizeHint) : Qt_SizeHint;

    static const TapGesture : Qt_GestureType;
    static const TapAndHoldGesture : Qt_GestureType;
    static const PanGesture : Qt_GestureType;
    static const PinchGesture : Qt_GestureType;
    static const SwipeGesture : Qt_GestureType;
    static const CustomGesture : Qt_GestureType;
    static const LastGestureType : Qt_GestureType;
    static function GestureType(value : Qt_GestureType) : Qt_GestureType;

    static const AutoConnection : Qt_ConnectionType;
    static const DirectConnection : Qt_ConnectionType;
    static const QueuedConnection : Qt_ConnectionType;
    static const BlockingQueuedConnection : Qt_ConnectionType;
    static const UniqueConnection : Qt_ConnectionType;
    static function ConnectionType(value : Qt_ConnectionType) : Qt_ConnectionType;

    static const NoItemFlags : Qt_ItemFlag;
    static const ItemIsSelectable : Qt_ItemFlag;
    static const ItemIsEditable : Qt_ItemFlag;
    static const ItemIsDragEnabled : Qt_ItemFlag;
    static const ItemIsDropEnabled : Qt_ItemFlag;
    static const ItemIsUserCheckable : Qt_ItemFlag;
    static const ItemIsEnabled : Qt_ItemFlag;
    static const ItemIsTristate : Qt_ItemFlag;
    static const ItemNeverHasChildren : Qt_ItemFlag;
    static function ItemFlag(value : Qt_ItemFlag) : Qt_ItemFlag;
    static function ItemFlags(...value : Qt_ItemFlag) : Qt_ItemFlags;

    static const AscendingOrder : Qt_SortOrder;
    static const DescendingOrder : Qt_SortOrder;
    static function SortOrder(value : Qt_SortOrder) : Qt_SortOrder;

    static const WidgetShortcut : Qt_ShortcutContext;
    static const WindowShortcut : Qt_ShortcutContext;
    static const ApplicationShortcut : Qt_ShortcutContext;
    static const WidgetWithChildrenShortcut : Qt_ShortcutContext;
    static function ShortcutContext(value : Qt_ShortcutContext) : Qt_ShortcutContext;

    static const NoGesture : Qt_GestureState;
    static const GestureStarted : Qt_GestureState;
    static const GestureUpdated : Qt_GestureState;
    static const GestureFinished : Qt_GestureState;
    static const GestureCanceled : Qt_GestureState;
    static function GestureState(value : Qt_GestureState) : Qt_GestureState;

    static const UI_General : Qt_UIEffect;
    static const UI_AnimateMenu : Qt_UIEffect;
    static const UI_FadeMenu : Qt_UIEffect;
    static const UI_AnimateCombo : Qt_UIEffect;
    static const UI_AnimateTooltip : Qt_UIEffect;
    static const UI_FadeTooltip : Qt_UIEffect;
    static const UI_AnimateToolBox : Qt_UIEffect;
    static function UIEffect(value : Qt_UIEffect) : Qt_UIEffect;

    static const Monday : Qt_DayOfWeek;
    static const Tuesday : Qt_DayOfWeek;
    static const Wednesday : Qt_DayOfWeek;
    static const Thursday : Qt_DayOfWeek;
    static const Friday : Qt_DayOfWeek;
    static const Saturday : Qt_DayOfWeek;
    static const Sunday : Qt_DayOfWeek;
    static function DayOfWeek(value : Qt_DayOfWeek) : Qt_DayOfWeek;

    static const ContainsItemShape : Qt_ItemSelectionMode;
    static const IntersectsItemShape : Qt_ItemSelectionMode;
    static const ContainsItemBoundingRect : Qt_ItemSelectionMode;
    static const IntersectsItemBoundingRect : Qt_ItemSelectionMode;
    static function ItemSelectionMode(value : Qt_ItemSelectionMode) : Qt_ItemSelectionMode;

    static const FastTransformation : Qt_TransformationMode;
    static const SmoothTransformation : Qt_TransformationMode;
    static function TransformationMode(value : Qt_TransformationMode) : Qt_TransformationMode;

    static const IgnoreAspectRatio : Qt_AspectRatioMode;
    static const KeepAspectRatio : Qt_AspectRatioMode;
    static const KeepAspectRatioByExpanding : Qt_AspectRatioMode;
    static function AspectRatioMode(value : Qt_AspectRatioMode) : Qt_AspectRatioMode;

    static const DeviceCoordinates : Qt_CoordinateSystem;
    static const LogicalCoordinates : Qt_CoordinateSystem;
    static function CoordinateSystem(value : Qt_CoordinateSystem) : Qt_CoordinateSystem;

    static const Horizontal : Qt_Orientation;
    static const Vertical : Qt_Orientation;
    static function Orientation(value : Qt_Orientation) : Qt_Orientation;
    static function Orientations(...value : Qt_Orientation) : Qt_Orientations;

    static const AA_ImmediateWidgetCreation : Qt_ApplicationAttribute;
    static const AA_MSWindowsUseDirect3DByDefault : Qt_ApplicationAttribute;
    static const AA_DontShowIconsInMenus : Qt_ApplicationAttribute;
    static const AA_NativeWindows : Qt_ApplicationAttribute;
    static const AA_DontCreateNativeWidgetSiblings : Qt_ApplicationAttribute;
    static const AA_MacPluginApplication : Qt_ApplicationAttribute;
    static const AA_DontUseNativeMenuBar : Qt_ApplicationAttribute;
    static const AA_MacDontSwapCtrlAndMeta : Qt_ApplicationAttribute;
    static const AA_Use96Dpi : Qt_ApplicationAttribute;
    static const AA_X11InitThreads : Qt_ApplicationAttribute;
    static const AA_SynthesizeTouchForUnhandledMouseEvents : Qt_ApplicationAttribute;
    static const AA_SynthesizeMouseForUnhandledTouchEvents : Qt_ApplicationAttribute;
    static const AA_UseHighDpiPixmaps : Qt_ApplicationAttribute;
    static const AA_AttributeCount : Qt_ApplicationAttribute;
    static function ApplicationAttribute(value : Qt_ApplicationAttribute) : Qt_ApplicationAttribute;

    static const color0 : Qt_GlobalColor;
    static const color1 : Qt_GlobalColor;
    static const black : Qt_GlobalColor;
    static const white : Qt_GlobalColor;
    static const darkGray : Qt_GlobalColor;
    static const gray : Qt_GlobalColor;
    static const lightGray : Qt_GlobalColor;
    static const red : Qt_GlobalColor;
    static const green : Qt_GlobalColor;
    static const blue : Qt_GlobalColor;
    static const cyan : Qt_GlobalColor;
    static const magenta : Qt_GlobalColor;
    static const yellow : Qt_GlobalColor;
    static const darkRed : Qt_GlobalColor;
    static const darkGreen : Qt_GlobalColor;
    static const darkBlue : Qt_GlobalColor;
    static const darkCyan : Qt_GlobalColor;
    static const darkMagenta : Qt_GlobalColor;
    static const darkYellow : Qt_GlobalColor;
    static const transparent : Qt_GlobalColor;
    static function GlobalColor(value : Qt_GlobalColor) : Qt_GlobalColor;

    static const Unchecked : Qt_CheckState;
    static const PartiallyChecked : Qt_CheckState;
    static const Checked : Qt_CheckState;
    static function CheckState(value : Qt_CheckState) : Qt_CheckState;

    static const StretchTile : Qt_TileRule;
    static const RepeatTile : Qt_TileRule;
    static const RoundTile : Qt_TileRule;
    static function TileRule(value : Qt_TileRule) : Qt_TileRule;

    static const NoToolBarArea : Qt_ToolBarArea;
    static const LeftToolBarArea : Qt_ToolBarArea;
    static const RightToolBarArea : Qt_ToolBarArea;
    static const TopToolBarArea : Qt_ToolBarArea;
    static const BottomToolBarArea : Qt_ToolBarArea;
    static const ToolBarArea_Mask : Qt_ToolBarArea;
    static function ToolBarArea(value : Qt_ToolBarArea) : Qt_ToolBarArea;
    static function ToolBarAreas(...value : Qt_ToolBarArea) : Qt_ToolBarAreas;

    static const WA_Disabled : Qt_WidgetAttribute;
    static const WA_UnderMouse : Qt_WidgetAttribute;
    static const WA_MouseTracking : Qt_WidgetAttribute;
    static const WA_ContentsPropagated : Qt_WidgetAttribute;
    static const WA_OpaquePaintEvent : Qt_WidgetAttribute;
    static const WA_StaticContents : Qt_WidgetAttribute;
    static const WA_LaidOut : Qt_WidgetAttribute;
    static const WA_PaintOnScreen : Qt_WidgetAttribute;
    static const WA_NoSystemBackground : Qt_WidgetAttribute;
    static const WA_UpdatesDisabled : Qt_WidgetAttribute;
    static const WA_Mapped : Qt_WidgetAttribute;
    static const WA_MacNoClickThrough : Qt_WidgetAttribute;
    static const WA_InputMethodEnabled : Qt_WidgetAttribute;
    static const WA_WState_Visible : Qt_WidgetAttribute;
    static const WA_WState_Hidden : Qt_WidgetAttribute;
    static const WA_ForceDisabled : Qt_WidgetAttribute;
    static const WA_KeyCompression : Qt_WidgetAttribute;
    static const WA_PendingMoveEvent : Qt_WidgetAttribute;
    static const WA_PendingResizeEvent : Qt_WidgetAttribute;
    static const WA_SetPalette : Qt_WidgetAttribute;
    static const WA_SetFont : Qt_WidgetAttribute;
    static const WA_SetCursor : Qt_WidgetAttribute;
    static const WA_NoChildEventsFromChildren : Qt_WidgetAttribute;
    static const WA_WindowModified : Qt_WidgetAttribute;
    static const WA_Resized : Qt_WidgetAttribute;
    static const WA_Moved : Qt_WidgetAttribute;
    static const WA_PendingUpdate : Qt_WidgetAttribute;
    static const WA_InvalidSize : Qt_WidgetAttribute;
    static const WA_MacBrushedMetal : Qt_WidgetAttribute;
    static const WA_CustomWhatsThis : Qt_WidgetAttribute;
    static const WA_LayoutOnEntireRect : Qt_WidgetAttribute;
    static const WA_OutsideWSRange : Qt_WidgetAttribute;
    static const WA_GrabbedShortcut : Qt_WidgetAttribute;
    static const WA_TransparentForMouseEvents : Qt_WidgetAttribute;
    static const WA_PaintUnclipped : Qt_WidgetAttribute;
    static const WA_SetWindowIcon : Qt_WidgetAttribute;
    static const WA_NoMouseReplay : Qt_WidgetAttribute;
    static const WA_DeleteOnClose : Qt_WidgetAttribute;
    static const WA_RightToLeft : Qt_WidgetAttribute;
    static const WA_SetLayoutDirection : Qt_WidgetAttribute;
    static const WA_NoChildEventsForParent : Qt_WidgetAttribute;
    static const WA_ForceUpdatesDisabled : Qt_WidgetAttribute;
    static const WA_WState_Created : Qt_WidgetAttribute;
    static const WA_WState_CompressKeys : Qt_WidgetAttribute;
    static const WA_WState_InPaintEvent : Qt_WidgetAttribute;
    static const WA_WState_Reparented : Qt_WidgetAttribute;
    static const WA_WState_ConfigPending : Qt_WidgetAttribute;
    static const WA_WState_Polished : Qt_WidgetAttribute;
    static const WA_WState_DND : Qt_WidgetAttribute;
    static const WA_WState_OwnSizePolicy : Qt_WidgetAttribute;
    static const WA_WState_ExplicitShowHide : Qt_WidgetAttribute;
    static const WA_ShowModal : Qt_WidgetAttribute;
    static const WA_MouseNoMask : Qt_WidgetAttribute;
    static const WA_GroupLeader : Qt_WidgetAttribute;
    static const WA_NoMousePropagation : Qt_WidgetAttribute;
    static const WA_Hover : Qt_WidgetAttribute;
    static const WA_InputMethodTransparent : Qt_WidgetAttribute;
    static const WA_QuitOnClose : Qt_WidgetAttribute;
    static const WA_KeyboardFocusChange : Qt_WidgetAttribute;
    static const WA_AcceptDrops : Qt_WidgetAttribute;
    static const WA_DropSiteRegistered : Qt_WidgetAttribute;
    static const WA_WindowPropagation : Qt_WidgetAttribute;
    static const WA_NoX11EventCompression : Qt_WidgetAttribute;
    static const WA_TintedBackground : Qt_WidgetAttribute;
    static const WA_X11OpenGLOverlay : Qt_WidgetAttribute;
    static const WA_AlwaysShowToolTips : Qt_WidgetAttribute;
    static const WA_MacOpaqueSizeGrip : Qt_WidgetAttribute;
    static const WA_SetStyle : Qt_WidgetAttribute;
    static const WA_SetLocale : Qt_WidgetAttribute;
    static const WA_MacShowFocusRect : Qt_WidgetAttribute;
    static const WA_MacNormalSize : Qt_WidgetAttribute;
    static const WA_MacSmallSize : Qt_WidgetAttribute;
    static const WA_MacMiniSize : Qt_WidgetAttribute;
    static const WA_LayoutUsesWidgetRect : Qt_WidgetAttribute;
    static const WA_StyledBackground : Qt_WidgetAttribute;
    static const WA_MSWindowsUseDirect3D : Qt_WidgetAttribute;
    static const WA_CanHostQMdiSubWindowTitleBar : Qt_WidgetAttribute;
    static const WA_MacAlwaysShowToolWindow : Qt_WidgetAttribute;
    static const WA_StyleSheet : Qt_WidgetAttribute;
    static const WA_ShowWithoutActivating : Qt_WidgetAttribute;
    static const WA_X11BypassTransientForHint : Qt_WidgetAttribute;
    static const WA_NativeWindow : Qt_WidgetAttribute;
    static const WA_DontCreateNativeAncestors : Qt_WidgetAttribute;
    static const WA_MacVariableSize : Qt_WidgetAttribute;
    static const WA_DontShowOnScreen : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeDesktop : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeDock : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeToolBar : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeMenu : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeUtility : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeSplash : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeDialog : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeDropDownMenu : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypePopupMenu : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeToolTip : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeNotification : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeCombo : Qt_WidgetAttribute;
    static const WA_X11NetWmWindowTypeDND : Qt_WidgetAttribute;
    static const WA_MacFrameworkScaled : Qt_WidgetAttribute;
    static const WA_SetWindowModality : Qt_WidgetAttribute;
    static const WA_WState_WindowOpacitySet : Qt_WidgetAttribute;
    static const WA_TranslucentBackground : Qt_WidgetAttribute;
    static const WA_AcceptTouchEvents : Qt_WidgetAttribute;
    static const WA_WState_AcceptedTouchBeginEvent : Qt_WidgetAttribute;
    static const WA_TouchPadAcceptSingleTouchEvents : Qt_WidgetAttribute;
    static const WA_X11DoNotAcceptFocus : Qt_WidgetAttribute;
    static const WA_MacNoShadow : Qt_WidgetAttribute;
    static const WA_AttributeCount : Qt_WidgetAttribute;
    static function WidgetAttribute(value : Qt_WidgetAttribute) : Qt_WidgetAttribute;

    static const KeyboardModifierMask : Qt_KeyboardModifier;
    static const NoModifier : Qt_KeyboardModifier;
    static const ShiftModifier : Qt_KeyboardModifier;
    static const ControlModifier : Qt_KeyboardModifier;
    static const AltModifier : Qt_KeyboardModifier;
    static const MetaModifier : Qt_KeyboardModifier;
    static const KeypadModifier : Qt_KeyboardModifier;
    static const GroupSwitchModifier : Qt_KeyboardModifier;
    static function KeyboardModifier(value : Qt_KeyboardModifier) : Qt_KeyboardModifier;
    static function KeyboardModifiers(...value : Qt_KeyboardModifier) : Qt_KeyboardModifiers;

    static const NDockWidgetAreas : Qt_DockWidgetAreaSizes;
    static function DockWidgetAreaSizes(value : Qt_DockWidgetAreaSizes) : Qt_DockWidgetAreaSizes;

    static const TransparentMode : Qt_BGMode;
    static const OpaqueMode : Qt_BGMode;
    static function BGMode(value : Qt_BGMode) : Qt_BGMode;

    static const MatchExactly : Qt_MatchFlag;
    static const MatchContains : Qt_MatchFlag;
    static const MatchStartsWith : Qt_MatchFlag;
    static const MatchEndsWith : Qt_MatchFlag;
    static const MatchRegExp : Qt_MatchFlag;
    static const MatchWildcard : Qt_MatchFlag;
    static const MatchFixedString : Qt_MatchFlag;
    static const MatchCaseSensitive : Qt_MatchFlag;
    static const MatchWrap : Qt_MatchFlag;
    static const MatchRecursive : Qt_MatchFlag;
    static function MatchFlag(value : Qt_MatchFlag) : Qt_MatchFlag;
    static function MatchFlags(...value : Qt_MatchFlag) : Qt_MatchFlags;

    static const PreciseTimer : Qt_TimerType;
    static const CoarseTimer : Qt_TimerType;
    static const VeryCoarseTimer : Qt_TimerType;
    static function TimerType(value : Qt_TimerType) : Qt_TimerType;

    static const MouseButtonMask : Qt_MouseButton;
    static const NoButton : Qt_MouseButton;
    static const LeftButton : Qt_MouseButton;
    static const RightButton : Qt_MouseButton;
    static const MidButton : Qt_MouseButton;
    static const BackButton : Qt_MouseButton;
    static const ForwardButton : Qt_MouseButton;
    static const TaskButton : Qt_MouseButton;
    static const ExtraButton4 : Qt_MouseButton;
    static const ExtraButton5 : Qt_MouseButton;
    static const ExtraButton6 : Qt_MouseButton;
    static const ExtraButton7 : Qt_MouseButton;
    static const ExtraButton8 : Qt_MouseButton;
    static const ExtraButton9 : Qt_MouseButton;
    static const ExtraButton10 : Qt_MouseButton;
    static const ExtraButton11 : Qt_MouseButton;
    static const ExtraButton12 : Qt_MouseButton;
    static const ExtraButton13 : Qt_MouseButton;
    static const ExtraButton14 : Qt_MouseButton;
    static const ExtraButton15 : Qt_MouseButton;
    static const ExtraButton16 : Qt_MouseButton;
    static const ExtraButton17 : Qt_MouseButton;
    static const ExtraButton18 : Qt_MouseButton;
    static const ExtraButton19 : Qt_MouseButton;
    static const ExtraButton20 : Qt_MouseButton;
    static const ExtraButton21 : Qt_MouseButton;
    static const ExtraButton22 : Qt_MouseButton;
    static const ExtraButton23 : Qt_MouseButton;
    static const ExtraButton24 : Qt_MouseButton;
    static const AllButtons : Qt_MouseButton;
    static function MouseButton(value : Qt_MouseButton) : Qt_MouseButton;
    static function MouseButtons(...value : Qt_MouseButton) : Qt_MouseButtons;

    static const NoDockWidgetArea : Qt_DockWidgetArea;
    static const LeftDockWidgetArea : Qt_DockWidgetArea;
    static const RightDockWidgetArea : Qt_DockWidgetArea;
    static const TopDockWidgetArea : Qt_DockWidgetArea;
    static const BottomDockWidgetArea : Qt_DockWidgetArea;
    static const DockWidgetArea_Mask : Qt_DockWidgetArea;
    static function DockWidgetArea(value : Qt_DockWidgetArea) : Qt_DockWidgetArea;
    static function DockWidgetAreas(...value : Qt_DockWidgetArea) : Qt_DockWidgetAreas;

    static const AnchorLeft : Qt_AnchorPoint;
    static const AnchorHorizontalCenter : Qt_AnchorPoint;
    static const AnchorRight : Qt_AnchorPoint;
    static const AnchorTop : Qt_AnchorPoint;
    static const AnchorVerticalCenter : Qt_AnchorPoint;
    static const AnchorBottom : Qt_AnchorPoint;
    static function AnchorPoint(value : Qt_AnchorPoint) : Qt_AnchorPoint;

    static const DontStartGestureOnChildren : Qt_GestureFlag;
    static const ReceivePartialGestures : Qt_GestureFlag;
    static const IgnoredGesturesPropagateToParent : Qt_GestureFlag;
    static function GestureFlag(value : Qt_GestureFlag) : Qt_GestureFlag;
    static function GestureFlags(...value : Qt_GestureFlag) : Qt_GestureFlags;

    static const WindowFullscreenButtonHint : Qt_WindowType;
    static const Widget : Qt_WindowType;
    static const Window : Qt_WindowType;
    static const Dialog : Qt_WindowType;
    static const Sheet : Qt_WindowType;
    static const Drawer : Qt_WindowType;
    static const Popup : Qt_WindowType;
    static const Tool : Qt_WindowType;
    static const ToolTip : Qt_WindowType;
    static const SplashScreen : Qt_WindowType;
    static const Desktop : Qt_WindowType;
    static const SubWindow : Qt_WindowType;
    static const ForeignWindow : Qt_WindowType;
    static const CoverWindow : Qt_WindowType;
    static const WindowType_Mask : Qt_WindowType;
    static const MSWindowsFixedSizeDialogHint : Qt_WindowType;
    static const MSWindowsOwnDC : Qt_WindowType;
    static const BypassWindowManagerHint : Qt_WindowType;
    static const FramelessWindowHint : Qt_WindowType;
    static const WindowTitleHint : Qt_WindowType;
    static const WindowSystemMenuHint : Qt_WindowType;
    static const WindowMinimizeButtonHint : Qt_WindowType;
    static const WindowMaximizeButtonHint : Qt_WindowType;
    static const WindowMinMaxButtonsHint : Qt_WindowType;
    static const WindowContextHelpButtonHint : Qt_WindowType;
    static const WindowShadeButtonHint : Qt_WindowType;
    static const WindowStaysOnTopHint : Qt_WindowType;
    static const WindowTransparentForInput : Qt_WindowType;
    static const WindowOverridesSystemGestures : Qt_WindowType;
    static const WindowDoesNotAcceptFocus : Qt_WindowType;
    static const CustomizeWindowHint : Qt_WindowType;
    static const WindowStaysOnBottomHint : Qt_WindowType;
    static const WindowCloseButtonHint : Qt_WindowType;
    static const MacWindowToolBarButtonHint : Qt_WindowType;
    static const BypassGraphicsProxyWidget : Qt_WindowType;
    static const NoDropShadowWindowHint : Qt_WindowType;
    static function WindowType(value : Qt_WindowType) : Qt_WindowType;
    static function WindowFlags(...value : Qt_WindowType) : Qt_WindowFlags;

    static const Key_Space : Qt_Key;
    static const Key_Exclam : Qt_Key;
    static const Key_QuoteDbl : Qt_Key;
    static const Key_NumberSign : Qt_Key;
    static const Key_Dollar : Qt_Key;
    static const Key_Percent : Qt_Key;
    static const Key_Ampersand : Qt_Key;
    static const Key_Apostrophe : Qt_Key;
    static const Key_ParenLeft : Qt_Key;
    static const Key_ParenRight : Qt_Key;
    static const Key_Asterisk : Qt_Key;
    static const Key_Plus : Qt_Key;
    static const Key_Comma : Qt_Key;
    static const Key_Minus : Qt_Key;
    static const Key_Period : Qt_Key;
    static const Key_Slash : Qt_Key;
    static const Key_0 : Qt_Key;
    static const Key_1 : Qt_Key;
    static const Key_2 : Qt_Key;
    static const Key_3 : Qt_Key;
    static const Key_4 : Qt_Key;
    static const Key_5 : Qt_Key;
    static const Key_6 : Qt_Key;
    static const Key_7 : Qt_Key;
    static const Key_8 : Qt_Key;
    static const Key_9 : Qt_Key;
    static const Key_Colon : Qt_Key;
    static const Key_Semicolon : Qt_Key;
    static const Key_Less : Qt_Key;
    static const Key_Equal : Qt_Key;
    static const Key_Greater : Qt_Key;
    static const Key_Question : Qt_Key;
    static const Key_At : Qt_Key;
    static const Key_A : Qt_Key;
    static const Key_B : Qt_Key;
    static const Key_C : Qt_Key;
    static const Key_D : Qt_Key;
    static const Key_E : Qt_Key;
    static const Key_F : Qt_Key;
    static const Key_G : Qt_Key;
    static const Key_H : Qt_Key;
    static const Key_I : Qt_Key;
    static const Key_J : Qt_Key;
    static const Key_K : Qt_Key;
    static const Key_L : Qt_Key;
    static const Key_M : Qt_Key;
    static const Key_N : Qt_Key;
    static const Key_O : Qt_Key;
    static const Key_P : Qt_Key;
    static const Key_Q : Qt_Key;
    static const Key_R : Qt_Key;
    static const Key_S : Qt_Key;
    static const Key_T : Qt_Key;
    static const Key_U : Qt_Key;
    static const Key_V : Qt_Key;
    static const Key_W : Qt_Key;
    static const Key_X : Qt_Key;
    static const Key_Y : Qt_Key;
    static const Key_Z : Qt_Key;
    static const Key_BracketLeft : Qt_Key;
    static const Key_Backslash : Qt_Key;
    static const Key_BracketRight : Qt_Key;
    static const Key_AsciiCircum : Qt_Key;
    static const Key_Underscore : Qt_Key;
    static const Key_QuoteLeft : Qt_Key;
    static const Key_BraceLeft : Qt_Key;
    static const Key_Bar : Qt_Key;
    static const Key_BraceRight : Qt_Key;
    static const Key_AsciiTilde : Qt_Key;
    static const Key_nobreakspace : Qt_Key;
    static const Key_exclamdown : Qt_Key;
    static const Key_cent : Qt_Key;
    static const Key_sterling : Qt_Key;
    static const Key_currency : Qt_Key;
    static const Key_yen : Qt_Key;
    static const Key_brokenbar : Qt_Key;
    static const Key_section : Qt_Key;
    static const Key_diaeresis : Qt_Key;
    static const Key_copyright : Qt_Key;
    static const Key_ordfeminine : Qt_Key;
    static const Key_guillemotleft : Qt_Key;
    static const Key_notsign : Qt_Key;
    static const Key_hyphen : Qt_Key;
    static const Key_registered : Qt_Key;
    static const Key_macron : Qt_Key;
    static const Key_degree : Qt_Key;
    static const Key_plusminus : Qt_Key;
    static const Key_twosuperior : Qt_Key;
    static const Key_threesuperior : Qt_Key;
    static const Key_acute : Qt_Key;
    static const Key_mu : Qt_Key;
    static const Key_paragraph : Qt_Key;
    static const Key_periodcentered : Qt_Key;
    static const Key_cedilla : Qt_Key;
    static const Key_onesuperior : Qt_Key;
    static const Key_masculine : Qt_Key;
    static const Key_guillemotright : Qt_Key;
    static const Key_onequarter : Qt_Key;
    static const Key_onehalf : Qt_Key;
    static const Key_threequarters : Qt_Key;
    static const Key_questiondown : Qt_Key;
    static const Key_Agrave : Qt_Key;
    static const Key_Aacute : Qt_Key;
    static const Key_Acircumflex : Qt_Key;
    static const Key_Atilde : Qt_Key;
    static const Key_Adiaeresis : Qt_Key;
    static const Key_Aring : Qt_Key;
    static const Key_AE : Qt_Key;
    static const Key_Ccedilla : Qt_Key;
    static const Key_Egrave : Qt_Key;
    static const Key_Eacute : Qt_Key;
    static const Key_Ecircumflex : Qt_Key;
    static const Key_Ediaeresis : Qt_Key;
    static const Key_Igrave : Qt_Key;
    static const Key_Iacute : Qt_Key;
    static const Key_Icircumflex : Qt_Key;
    static const Key_Idiaeresis : Qt_Key;
    static const Key_ETH : Qt_Key;
    static const Key_Ntilde : Qt_Key;
    static const Key_Ograve : Qt_Key;
    static const Key_Oacute : Qt_Key;
    static const Key_Ocircumflex : Qt_Key;
    static const Key_Otilde : Qt_Key;
    static const Key_Odiaeresis : Qt_Key;
    static const Key_multiply : Qt_Key;
    static const Key_Ooblique : Qt_Key;
    static const Key_Ugrave : Qt_Key;
    static const Key_Uacute : Qt_Key;
    static const Key_Ucircumflex : Qt_Key;
    static const Key_Udiaeresis : Qt_Key;
    static const Key_Yacute : Qt_Key;
    static const Key_THORN : Qt_Key;
    static const Key_ssharp : Qt_Key;
    static const Key_division : Qt_Key;
    static const Key_ydiaeresis : Qt_Key;
    static const Key_Escape : Qt_Key;
    static const Key_Tab : Qt_Key;
    static const Key_Backtab : Qt_Key;
    static const Key_Backspace : Qt_Key;
    static const Key_Return : Qt_Key;
    static const Key_Enter : Qt_Key;
    static const Key_Insert : Qt_Key;
    static const Key_Delete : Qt_Key;
    static const Key_Pause : Qt_Key;
    static const Key_Print : Qt_Key;
    static const Key_SysReq : Qt_Key;
    static const Key_Clear : Qt_Key;
    static const Key_Home : Qt_Key;
    static const Key_End : Qt_Key;
    static const Key_Left : Qt_Key;
    static const Key_Up : Qt_Key;
    static const Key_Right : Qt_Key;
    static const Key_Down : Qt_Key;
    static const Key_PageUp : Qt_Key;
    static const Key_PageDown : Qt_Key;
    static const Key_Shift : Qt_Key;
    static const Key_Control : Qt_Key;
    static const Key_Meta : Qt_Key;
    static const Key_Alt : Qt_Key;
    static const Key_CapsLock : Qt_Key;
    static const Key_NumLock : Qt_Key;
    static const Key_ScrollLock : Qt_Key;
    static const Key_F1 : Qt_Key;
    static const Key_F2 : Qt_Key;
    static const Key_F3 : Qt_Key;
    static const Key_F4 : Qt_Key;
    static const Key_F5 : Qt_Key;
    static const Key_F6 : Qt_Key;
    static const Key_F7 : Qt_Key;
    static const Key_F8 : Qt_Key;
    static const Key_F9 : Qt_Key;
    static const Key_F10 : Qt_Key;
    static const Key_F11 : Qt_Key;
    static const Key_F12 : Qt_Key;
    static const Key_F13 : Qt_Key;
    static const Key_F14 : Qt_Key;
    static const Key_F15 : Qt_Key;
    static const Key_F16 : Qt_Key;
    static const Key_F17 : Qt_Key;
    static const Key_F18 : Qt_Key;
    static const Key_F19 : Qt_Key;
    static const Key_F20 : Qt_Key;
    static const Key_F21 : Qt_Key;
    static const Key_F22 : Qt_Key;
    static const Key_F23 : Qt_Key;
    static const Key_F24 : Qt_Key;
    static const Key_F25 : Qt_Key;
    static const Key_F26 : Qt_Key;
    static const Key_F27 : Qt_Key;
    static const Key_F28 : Qt_Key;
    static const Key_F29 : Qt_Key;
    static const Key_F30 : Qt_Key;
    static const Key_F31 : Qt_Key;
    static const Key_F32 : Qt_Key;
    static const Key_F33 : Qt_Key;
    static const Key_F34 : Qt_Key;
    static const Key_F35 : Qt_Key;
    static const Key_Super_L : Qt_Key;
    static const Key_Super_R : Qt_Key;
    static const Key_Menu : Qt_Key;
    static const Key_Hyper_L : Qt_Key;
    static const Key_Hyper_R : Qt_Key;
    static const Key_Help : Qt_Key;
    static const Key_Direction_L : Qt_Key;
    static const Key_Direction_R : Qt_Key;
    static const Key_Back : Qt_Key;
    static const Key_Forward : Qt_Key;
    static const Key_Stop : Qt_Key;
    static const Key_Refresh : Qt_Key;
    static const Key_VolumeDown : Qt_Key;
    static const Key_VolumeMute : Qt_Key;
    static const Key_VolumeUp : Qt_Key;
    static const Key_BassBoost : Qt_Key;
    static const Key_BassUp : Qt_Key;
    static const Key_BassDown : Qt_Key;
    static const Key_TrebleUp : Qt_Key;
    static const Key_TrebleDown : Qt_Key;
    static const Key_MediaPlay : Qt_Key;
    static const Key_MediaStop : Qt_Key;
    static const Key_MediaPrevious : Qt_Key;
    static const Key_MediaNext : Qt_Key;
    static const Key_MediaRecord : Qt_Key;
    static const Key_MediaPause : Qt_Key;
    static const Key_MediaTogglePlayPause : Qt_Key;
    static const Key_HomePage : Qt_Key;
    static const Key_Favorites : Qt_Key;
    static const Key_Search : Qt_Key;
    static const Key_Standby : Qt_Key;
    static const Key_OpenUrl : Qt_Key;
    static const Key_LaunchMail : Qt_Key;
    static const Key_LaunchMedia : Qt_Key;
    static const Key_Launch0 : Qt_Key;
    static const Key_Launch1 : Qt_Key;
    static const Key_Launch2 : Qt_Key;
    static const Key_Launch3 : Qt_Key;
    static const Key_Launch4 : Qt_Key;
    static const Key_Launch5 : Qt_Key;
    static const Key_Launch6 : Qt_Key;
    static const Key_Launch7 : Qt_Key;
    static const Key_Launch8 : Qt_Key;
    static const Key_Launch9 : Qt_Key;
    static const Key_LaunchA : Qt_Key;
    static const Key_LaunchB : Qt_Key;
    static const Key_LaunchC : Qt_Key;
    static const Key_LaunchD : Qt_Key;
    static const Key_LaunchE : Qt_Key;
    static const Key_LaunchF : Qt_Key;
    static const Key_MonBrightnessUp : Qt_Key;
    static const Key_MonBrightnessDown : Qt_Key;
    static const Key_KeyboardLightOnOff : Qt_Key;
    static const Key_KeyboardBrightnessUp : Qt_Key;
    static const Key_KeyboardBrightnessDown : Qt_Key;
    static const Key_PowerOff : Qt_Key;
    static const Key_WakeUp : Qt_Key;
    static const Key_Eject : Qt_Key;
    static const Key_ScreenSaver : Qt_Key;
    static const Key_WWW : Qt_Key;
    static const Key_Memo : Qt_Key;
    static const Key_LightBulb : Qt_Key;
    static const Key_Shop : Qt_Key;
    static const Key_History : Qt_Key;
    static const Key_AddFavorite : Qt_Key;
    static const Key_HotLinks : Qt_Key;
    static const Key_BrightnessAdjust : Qt_Key;
    static const Key_Finance : Qt_Key;
    static const Key_Community : Qt_Key;
    static const Key_AudioRewind : Qt_Key;
    static const Key_BackForward : Qt_Key;
    static const Key_ApplicationLeft : Qt_Key;
    static const Key_ApplicationRight : Qt_Key;
    static const Key_Book : Qt_Key;
    static const Key_CD : Qt_Key;
    static const Key_Calculator : Qt_Key;
    static const Key_ToDoList : Qt_Key;
    static const Key_ClearGrab : Qt_Key;
    static const Key_Close : Qt_Key;
    static const Key_Copy : Qt_Key;
    static const Key_Cut : Qt_Key;
    static const Key_Display : Qt_Key;
    static const Key_DOS : Qt_Key;
    static const Key_Documents : Qt_Key;
    static const Key_Excel : Qt_Key;
    static const Key_Explorer : Qt_Key;
    static const Key_Game : Qt_Key;
    static const Key_Go : Qt_Key;
    static const Key_iTouch : Qt_Key;
    static const Key_LogOff : Qt_Key;
    static const Key_Market : Qt_Key;
    static const Key_Meeting : Qt_Key;
    static const Key_MenuKB : Qt_Key;
    static const Key_MenuPB : Qt_Key;
    static const Key_MySites : Qt_Key;
    static const Key_News : Qt_Key;
    static const Key_OfficeHome : Qt_Key;
    static const Key_Option : Qt_Key;
    static const Key_Paste : Qt_Key;
    static const Key_Phone : Qt_Key;
    static const Key_Calendar : Qt_Key;
    static const Key_Reply : Qt_Key;
    static const Key_Reload : Qt_Key;
    static const Key_RotateWindows : Qt_Key;
    static const Key_RotationPB : Qt_Key;
    static const Key_RotationKB : Qt_Key;
    static const Key_Save : Qt_Key;
    static const Key_Send : Qt_Key;
    static const Key_Spell : Qt_Key;
    static const Key_SplitScreen : Qt_Key;
    static const Key_Support : Qt_Key;
    static const Key_TaskPane : Qt_Key;
    static const Key_Terminal : Qt_Key;
    static const Key_Tools : Qt_Key;
    static const Key_Travel : Qt_Key;
    static const Key_Video : Qt_Key;
    static const Key_Word : Qt_Key;
    static const Key_Xfer : Qt_Key;
    static const Key_ZoomIn : Qt_Key;
    static const Key_ZoomOut : Qt_Key;
    static const Key_Away : Qt_Key;
    static const Key_Messenger : Qt_Key;
    static const Key_WebCam : Qt_Key;
    static const Key_MailForward : Qt_Key;
    static const Key_Pictures : Qt_Key;
    static const Key_Music : Qt_Key;
    static const Key_Battery : Qt_Key;
    static const Key_Bluetooth : Qt_Key;
    static const Key_WLAN : Qt_Key;
    static const Key_UWB : Qt_Key;
    static const Key_AudioForward : Qt_Key;
    static const Key_AudioRepeat : Qt_Key;
    static const Key_AudioRandomPlay : Qt_Key;
    static const Key_Subtitle : Qt_Key;
    static const Key_AudioCycleTrack : Qt_Key;
    static const Key_Time : Qt_Key;
    static const Key_Hibernate : Qt_Key;
    static const Key_View : Qt_Key;
    static const Key_TopMenu : Qt_Key;
    static const Key_PowerDown : Qt_Key;
    static const Key_Suspend : Qt_Key;
    static const Key_ContrastAdjust : Qt_Key;
    static const Key_LaunchG : Qt_Key;
    static const Key_LaunchH : Qt_Key;
    static const Key_TouchpadToggle : Qt_Key;
    static const Key_TouchpadOn : Qt_Key;
    static const Key_TouchpadOff : Qt_Key;
    static const Key_MicMute : Qt_Key;
    static const Key_Red : Qt_Key;
    static const Key_Green : Qt_Key;
    static const Key_Yellow : Qt_Key;
    static const Key_Blue : Qt_Key;
    static const Key_ChannelUp : Qt_Key;
    static const Key_ChannelDown : Qt_Key;
    static const Key_AltGr : Qt_Key;
    static const Key_Multi_key : Qt_Key;
    static const Key_Kanji : Qt_Key;
    static const Key_Muhenkan : Qt_Key;
    static const Key_Henkan : Qt_Key;
    static const Key_Romaji : Qt_Key;
    static const Key_Hiragana : Qt_Key;
    static const Key_Katakana : Qt_Key;
    static const Key_Hiragana_Katakana : Qt_Key;
    static const Key_Zenkaku : Qt_Key;
    static const Key_Hankaku : Qt_Key;
    static const Key_Zenkaku_Hankaku : Qt_Key;
    static const Key_Touroku : Qt_Key;
    static const Key_Massyo : Qt_Key;
    static const Key_Kana_Lock : Qt_Key;
    static const Key_Kana_Shift : Qt_Key;
    static const Key_Eisu_Shift : Qt_Key;
    static const Key_Eisu_toggle : Qt_Key;
    static const Key_Hangul : Qt_Key;
    static const Key_Hangul_Start : Qt_Key;
    static const Key_Hangul_End : Qt_Key;
    static const Key_Hangul_Hanja : Qt_Key;
    static const Key_Hangul_Jamo : Qt_Key;
    static const Key_Hangul_Romaja : Qt_Key;
    static const Key_Codeinput : Qt_Key;
    static const Key_Hangul_Jeonja : Qt_Key;
    static const Key_Hangul_Banja : Qt_Key;
    static const Key_Hangul_PreHanja : Qt_Key;
    static const Key_Hangul_PostHanja : Qt_Key;
    static const Key_SingleCandidate : Qt_Key;
    static const Key_MultipleCandidate : Qt_Key;
    static const Key_PreviousCandidate : Qt_Key;
    static const Key_Hangul_Special : Qt_Key;
    static const Key_Mode_switch : Qt_Key;
    static const Key_Dead_Grave : Qt_Key;
    static const Key_Dead_Acute : Qt_Key;
    static const Key_Dead_Circumflex : Qt_Key;
    static const Key_Dead_Tilde : Qt_Key;
    static const Key_Dead_Macron : Qt_Key;
    static const Key_Dead_Breve : Qt_Key;
    static const Key_Dead_Abovedot : Qt_Key;
    static const Key_Dead_Diaeresis : Qt_Key;
    static const Key_Dead_Abovering : Qt_Key;
    static const Key_Dead_Doubleacute : Qt_Key;
    static const Key_Dead_Caron : Qt_Key;
    static const Key_Dead_Cedilla : Qt_Key;
    static const Key_Dead_Ogonek : Qt_Key;
    static const Key_Dead_Iota : Qt_Key;
    static const Key_Dead_Voiced_Sound : Qt_Key;
    static const Key_Dead_Semivoiced_Sound : Qt_Key;
    static const Key_Dead_Belowdot : Qt_Key;
    static const Key_Dead_Hook : Qt_Key;
    static const Key_Dead_Horn : Qt_Key;
    static const Key_MediaLast : Qt_Key;
    static const Key_Select : Qt_Key;
    static const Key_Yes : Qt_Key;
    static const Key_No : Qt_Key;
    static const Key_Cancel : Qt_Key;
    static const Key_Printer : Qt_Key;
    static const Key_Execute : Qt_Key;
    static const Key_Sleep : Qt_Key;
    static const Key_Play : Qt_Key;
    static const Key_Zoom : Qt_Key;
    static const Key_Context1 : Qt_Key;
    static const Key_Context2 : Qt_Key;
    static const Key_Context3 : Qt_Key;
    static const Key_Context4 : Qt_Key;
    static const Key_Call : Qt_Key;
    static const Key_Hangup : Qt_Key;
    static const Key_Flip : Qt_Key;
    static const Key_ToggleCallHangup : Qt_Key;
    static const Key_VoiceDial : Qt_Key;
    static const Key_LastNumberRedial : Qt_Key;
    static const Key_Camera : Qt_Key;
    static const Key_CameraFocus : Qt_Key;
    static const Key_unknown : Qt_Key;
    static function Key(value : Qt_Key) : Qt_Key;

    static const ElideLeft : Qt_TextElideMode;
    static const ElideRight : Qt_TextElideMode;
    static const ElideMiddle : Qt_TextElideMode;
    static const ElideNone : Qt_TextElideMode;
    static function TextElideMode(value : Qt_TextElideMode) : Qt_TextElideMode;

    static const FindDirectChildrenOnly : Qt_FindChildOption;
    static const FindChildrenRecursively : Qt_FindChildOption;
    static function FindChildOption(value : Qt_FindChildOption) : Qt_FindChildOption;

    static const NoArrow : Qt_ArrowType;
    static const UpArrow : Qt_ArrowType;
    static const DownArrow : Qt_ArrowType;
    static const LeftArrow : Qt_ArrowType;
    static const RightArrow : Qt_ArrowType;
    static function ArrowType(value : Qt_ArrowType) : Qt_ArrowType;

    static const FlatCap : Qt_PenCapStyle;
    static const SquareCap : Qt_PenCapStyle;
    static const RoundCap : Qt_PenCapStyle;
    static const MPenCapStyle : Qt_PenCapStyle;
    static function PenCapStyle(value : Qt_PenCapStyle) : Qt_PenCapStyle;

    static const CaseInsensitive : Qt_CaseSensitivity;
    static const CaseSensitive : Qt_CaseSensitivity;
    static function CaseSensitivity(value : Qt_CaseSensitivity) : Qt_CaseSensitivity;

    static const OddEvenFill : Qt_FillRule;
    static const WindingFill : Qt_FillRule;
    static function FillRule(value : Qt_FillRule) : Qt_FillRule;

    static const LocalTime : Qt_TimeSpec;
    static const UTC : Qt_TimeSpec;
    static const OffsetFromUTC : Qt_TimeSpec;
    static const TimeZone : Qt_TimeSpec;
    static function TimeSpec(value : Qt_TimeSpec) : Qt_TimeSpec;

    static const PrimaryOrientation : Qt_ScreenOrientation;
    static const PortraitOrientation : Qt_ScreenOrientation;
    static const LandscapeOrientation : Qt_ScreenOrientation;
    static const InvertedPortraitOrientation : Qt_ScreenOrientation;
    static const InvertedLandscapeOrientation : Qt_ScreenOrientation;
    static function ScreenOrientation(value : Qt_ScreenOrientation) : Qt_ScreenOrientation;

    static const ScrollBarAsNeeded : Qt_ScrollBarPolicy;
    static const ScrollBarAlwaysOff : Qt_ScrollBarPolicy;
    static const ScrollBarAlwaysOn : Qt_ScrollBarPolicy;
    static function ScrollBarPolicy(value : Qt_ScrollBarPolicy) : Qt_ScrollBarPolicy;

    static const ArrowCursor : Qt_CursorShape;
    static const UpArrowCursor : Qt_CursorShape;
    static const CrossCursor : Qt_CursorShape;
    static const WaitCursor : Qt_CursorShape;
    static const IBeamCursor : Qt_CursorShape;
    static const SizeVerCursor : Qt_CursorShape;
    static const SizeHorCursor : Qt_CursorShape;
    static const SizeBDiagCursor : Qt_CursorShape;
    static const SizeFDiagCursor : Qt_CursorShape;
    static const SizeAllCursor : Qt_CursorShape;
    static const BlankCursor : Qt_CursorShape;
    static const SplitVCursor : Qt_CursorShape;
    static const SplitHCursor : Qt_CursorShape;
    static const PointingHandCursor : Qt_CursorShape;
    static const ForbiddenCursor : Qt_CursorShape;
    static const WhatsThisCursor : Qt_CursorShape;
    static const BusyCursor : Qt_CursorShape;
    static const OpenHandCursor : Qt_CursorShape;
    static const ClosedHandCursor : Qt_CursorShape;
    static const DragCopyCursor : Qt_CursorShape;
    static const DragMoveCursor : Qt_CursorShape;
    static const DragLinkCursor : Qt_CursorShape;
    static const BitmapCursor : Qt_CursorShape;
    static const CustomCursor : Qt_CursorShape;
    static function CursorShape(value : Qt_CursorShape) : Qt_CursorShape;

    static const AutoColor : Qt_ImageConversionFlag;
    static const MonoOnly : Qt_ImageConversionFlag;
    static const ColorMode_Mask : Qt_ImageConversionFlag;
    static const OrderedAlphaDither : Qt_ImageConversionFlag;
    static const DiffuseAlphaDither : Qt_ImageConversionFlag;
    static const AlphaDither_Mask : Qt_ImageConversionFlag;
    static const OrderedDither : Qt_ImageConversionFlag;
    static const ThresholdDither : Qt_ImageConversionFlag;
    static const Dither_Mask : Qt_ImageConversionFlag;
    static const PreferDither : Qt_ImageConversionFlag;
    static const AvoidDither : Qt_ImageConversionFlag;
    static const DitherMode_Mask : Qt_ImageConversionFlag;
    static const NoOpaqueDetection : Qt_ImageConversionFlag;
    static const NoFormatConversion : Qt_ImageConversionFlag;
    static function ImageConversionFlag(value : Qt_ImageConversionFlag) : Qt_ImageConversionFlag;
    static function ImageConversionFlags(...value : Qt_ImageConversionFlag) : Qt_ImageConversionFlags;

    static const MaskInColor : Qt_MaskMode;
    static const MaskOutColor : Qt_MaskMode;
    static function MaskMode(value : Qt_MaskMode) : Qt_MaskMode;

    static const NToolBarAreas : Qt_ToolBarAreaSizes;
    static function ToolBarAreaSizes(value : Qt_ToolBarAreaSizes) : Qt_ToolBarAreaSizes;

    static const AbsoluteSize : Qt_SizeMode;
    static const RelativeSize : Qt_SizeMode;
    static function SizeMode(value : Qt_SizeMode) : Qt_SizeMode;

    static const TouchPointPressed : Qt_TouchPointState;
    static const TouchPointMoved : Qt_TouchPointState;
    static const TouchPointStationary : Qt_TouchPointState;
    static const TouchPointReleased : Qt_TouchPointState;
    static function TouchPointState(value : Qt_TouchPointState) : Qt_TouchPointState;
    static function TouchPointStates(...value : Qt_TouchPointState) : Qt_TouchPointStates;

    static const LogicalMoveStyle : Qt_CursorMoveStyle;
    static const VisualMoveStyle : Qt_CursorMoveStyle;
    static function CursorMoveStyle(value : Qt_CursorMoveStyle) : Qt_CursorMoveStyle;

    static const ImhExclusiveInputMask : Qt_InputMethodHint;
    static const ImhNone : Qt_InputMethodHint;
    static const ImhHiddenText : Qt_InputMethodHint;
    static const ImhSensitiveData : Qt_InputMethodHint;
    static const ImhNoAutoUppercase : Qt_InputMethodHint;
    static const ImhPreferNumbers : Qt_InputMethodHint;
    static const ImhPreferUppercase : Qt_InputMethodHint;
    static const ImhPreferLowercase : Qt_InputMethodHint;
    static const ImhNoPredictiveText : Qt_InputMethodHint;
    static const ImhDate : Qt_InputMethodHint;
    static const ImhTime : Qt_InputMethodHint;
    static const ImhPreferLatin : Qt_InputMethodHint;
    static const ImhMultiLine : Qt_InputMethodHint;
    static const ImhDigitsOnly : Qt_InputMethodHint;
    static const ImhFormattedNumbersOnly : Qt_InputMethodHint;
    static const ImhUppercaseOnly : Qt_InputMethodHint;
    static const ImhLowercaseOnly : Qt_InputMethodHint;
    static const ImhDialableCharactersOnly : Qt_InputMethodHint;
    static const ImhEmailCharactersOnly : Qt_InputMethodHint;
    static const ImhUrlCharactersOnly : Qt_InputMethodHint;
    static const ImhLatinOnly : Qt_InputMethodHint;
    static function InputMethodHint(value : Qt_InputMethodHint) : Qt_InputMethodHint;
    static function InputMethodHints(...value : Qt_InputMethodHint) : Qt_InputMethodHints;

    static const XAxis : Qt_Axis;
    static const YAxis : Qt_Axis;
    static const ZAxis : Qt_Axis;
    static function Axis(value : Qt_Axis) : Qt_Axis;

    static const NavigationModeNone : Qt_NavigationMode;
    static const NavigationModeKeypadTabOrder : Qt_NavigationMode;
    static const NavigationModeKeypadDirectional : Qt_NavigationMode;
    static const NavigationModeCursorAuto : Qt_NavigationMode;
    static const NavigationModeCursorForceVisible : Qt_NavigationMode;
    static function NavigationMode(value : Qt_NavigationMode) : Qt_NavigationMode;

    static const AlignLeft : Qt_AlignmentFlag;
    static const AlignRight : Qt_AlignmentFlag;
    static const AlignHCenter : Qt_AlignmentFlag;
    static const AlignJustify : Qt_AlignmentFlag;
    static const AlignAbsolute : Qt_AlignmentFlag;
    static const AlignHorizontal_Mask : Qt_AlignmentFlag;
    static const AlignTop : Qt_AlignmentFlag;
    static const AlignBottom : Qt_AlignmentFlag;
    static const AlignVCenter : Qt_AlignmentFlag;
    static const AlignCenter : Qt_AlignmentFlag;
    static const AlignBaseline : Qt_AlignmentFlag;
    static const AlignVertical_Mask : Qt_AlignmentFlag;
    static function AlignmentFlag(value : Qt_AlignmentFlag) : Qt_AlignmentFlag;
    static function Alignment(...value : Qt_AlignmentFlag) : Qt_Alignment;

    static const ImPlatformData : Qt_InputMethodQuery;
    static const ImQueryAll : Qt_InputMethodQuery;
    static const ImEnabled : Qt_InputMethodQuery;
    static const ImCursorRectangle : Qt_InputMethodQuery;
    static const ImFont : Qt_InputMethodQuery;
    static const ImCursorPosition : Qt_InputMethodQuery;
    static const ImSurroundingText : Qt_InputMethodQuery;
    static const ImCurrentSelection : Qt_InputMethodQuery;
    static const ImMaximumTextLength : Qt_InputMethodQuery;
    static const ImAnchorPosition : Qt_InputMethodQuery;
    static const ImQueryInput : Qt_InputMethodQuery;
    static const ImHints : Qt_InputMethodQuery;
    static const ImPreferredLanguage : Qt_InputMethodQuery;
    static function InputMethodQuery(value : Qt_InputMethodQuery) : Qt_InputMethodQuery;

    static const ExactHit : Qt_HitTestAccuracy;
    static const FuzzyHit : Qt_HitTestAccuracy;
    static function HitTestAccuracy(value : Qt_HitTestAccuracy) : Qt_HitTestAccuracy;

    static const NoFocus : Qt_FocusPolicy;
    static const TabFocus : Qt_FocusPolicy;
    static const ClickFocus : Qt_FocusPolicy;
    static const StrongFocus : Qt_FocusPolicy;
    static const WheelFocus : Qt_FocusPolicy;
    static function FocusPolicy(value : Qt_FocusPolicy) : Qt_FocusPolicy;

    static const NonModal : Qt_WindowModality;
    static const WindowModal : Qt_WindowModality;
    static const ApplicationModal : Qt_WindowModality;
    static function WindowModality(value : Qt_WindowModality) : Qt_WindowModality;

    static const MiterJoin : Qt_PenJoinStyle;
    static const BevelJoin : Qt_PenJoinStyle;
    static const RoundJoin : Qt_PenJoinStyle;
    static const SvgMiterJoin : Qt_PenJoinStyle;
    static const MPenJoinStyle : Qt_PenJoinStyle;
    static function PenJoinStyle(value : Qt_PenJoinStyle) : Qt_PenJoinStyle;

    static const LowEventPriority : Qt_EventPriority;
    static const NormalEventPriority : Qt_EventPriority;
    static const HighEventPriority : Qt_EventPriority;
    static function EventPriority(value : Qt_EventPriority) : Qt_EventPriority;

    static const MouseFocusReason : Qt_FocusReason;
    static const TabFocusReason : Qt_FocusReason;
    static const BacktabFocusReason : Qt_FocusReason;
    static const ActiveWindowFocusReason : Qt_FocusReason;
    static const PopupFocusReason : Qt_FocusReason;
    static const ShortcutFocusReason : Qt_FocusReason;
    static const MenuBarFocusReason : Qt_FocusReason;
    static const OtherFocusReason : Qt_FocusReason;
    static const NoFocusReason : Qt_FocusReason;
    static function FocusReason(value : Qt_FocusReason) : Qt_FocusReason;

    static const NoTextInteraction : Qt_TextInteractionFlag;
    static const TextSelectableByMouse : Qt_TextInteractionFlag;
    static const TextSelectableByKeyboard : Qt_TextInteractionFlag;
    static const LinksAccessibleByMouse : Qt_TextInteractionFlag;
    static const LinksAccessibleByKeyboard : Qt_TextInteractionFlag;
    static const TextBrowserInteraction : Qt_TextInteractionFlag;
    static const TextEditable : Qt_TextInteractionFlag;
    static const TextEditorInteraction : Qt_TextInteractionFlag;
    static function TextInteractionFlag(value : Qt_TextInteractionFlag) : Qt_TextInteractionFlag;
    static function TextInteractionFlags(...value : Qt_TextInteractionFlag) : Qt_TextInteractionFlags;

    static const TextDate : Qt_DateFormat;
    static const ISODate : Qt_DateFormat;
    static const SystemLocaleDate : Qt_DateFormat;
    static const LocaleDate : Qt_DateFormat;
    static const SystemLocaleShortDate : Qt_DateFormat;
    static const SystemLocaleLongDate : Qt_DateFormat;
    static const DefaultLocaleShortDate : Qt_DateFormat;
    static const DefaultLocaleLongDate : Qt_DateFormat;
    static const RFC2822Date : Qt_DateFormat;
    static function DateFormat(value : Qt_DateFormat) : Qt_DateFormat;

    static const ToolButtonIconOnly : Qt_ToolButtonStyle;
    static const ToolButtonTextOnly : Qt_ToolButtonStyle;
    static const ToolButtonTextBesideIcon : Qt_ToolButtonStyle;
    static const ToolButtonTextUnderIcon : Qt_ToolButtonStyle;
    static const ToolButtonFollowStyle : Qt_ToolButtonStyle;
    static function ToolButtonStyle(value : Qt_ToolButtonStyle) : Qt_ToolButtonStyle;

    static const NoSection : Qt_WindowFrameSection;
    static const LeftSection : Qt_WindowFrameSection;
    static const TopLeftSection : Qt_WindowFrameSection;
    static const TopSection : Qt_WindowFrameSection;
    static const TopRightSection : Qt_WindowFrameSection;
    static const RightSection : Qt_WindowFrameSection;
    static const BottomRightSection : Qt_WindowFrameSection;
    static const BottomSection : Qt_WindowFrameSection;
    static const BottomLeftSection : Qt_WindowFrameSection;
    static const TitleBarArea : Qt_WindowFrameSection;
    static function WindowFrameSection(value : Qt_WindowFrameSection) : Qt_WindowFrameSection;

    static const WhiteSpaceModeUndefined : Qt_WhiteSpaceMode;
    static const WhiteSpaceNormal : Qt_WhiteSpaceMode;
    static const WhiteSpacePre : Qt_WhiteSpaceMode;
    static const WhiteSpaceNoWrap : Qt_WhiteSpaceMode;
    static function WhiteSpaceMode(value : Qt_WhiteSpaceMode) : Qt_WhiteSpaceMode;

    static const IgnoreAction : Qt_DropAction;
    static const CopyAction : Qt_DropAction;
    static const MoveAction : Qt_DropAction;
    static const LinkAction : Qt_DropAction;
    static const ActionMask : Qt_DropAction;
    static const TargetMoveAction : Qt_DropAction;
    static function DropAction(value : Qt_DropAction) : Qt_DropAction;
    static function DropActions(...value : Qt_DropAction) : Qt_DropActions;
}
