/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTabWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qicon.jsx";
import "qt/qsize.jsx";
import "qt/qstyleoptiontabwidgetframe.jsx";
import "qt/qt.jsx";
import "qt/qtabbar.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QTabWidget_TabShape {}

final native class Qt_QTabWidget_TabPosition {}

native class QTabWidget extends QWidget
{
    function constructor (parent : QWidget);

    static const Rounded : Qt_QTabWidget_TabShape;
    static const Triangular : Qt_QTabWidget_TabShape;
    static function TabShape(value : Qt_QTabWidget_TabShape) : Qt_QTabWidget_TabShape;

    static const North : Qt_QTabWidget_TabPosition;
    static const South : Qt_QTabWidget_TabPosition;
    static const West : Qt_QTabWidget_TabPosition;
    static const East : Qt_QTabWidget_TabPosition;
    static function TabPosition(value : Qt_QTabWidget_TabPosition) : Qt_QTabWidget_TabPosition;

    // Methods
    function addTab (widget : QWidget, icon : QIcon, label : string) : int;
    function addTab (widget : QWidget, arg__2 : string) : int;
    function clear () : void;
    function cornerWidget (corner : Qt_Corner) : QWidget;
    function currentWidget () : QWidget;
    function indexOf (widget : QWidget) : int;
    function initStyleOption (option : QStyleOptionTabWidgetFrame) : void;
    function insertTab (index : int, widget : QWidget, icon : QIcon, label : string) : int;
    function insertTab (index : int, widget : QWidget, arg__3 : string) : int;
    function isTabEnabled (index : int) : boolean;
    function removeTab (index : int) : void;
    function setCornerWidget (w : QWidget, corner : Qt_Corner) : void;
    function setTabBar (arg__1 : QTabBar) : void;
    function setTabEnabled (index : int, arg__2 : boolean) : void;
    function setTabIcon (index : int, icon : QIcon) : void;
    function setTabText (index : int, arg__2 : string) : void;
    function setTabToolTip (index : int, tip : string) : void;
    function setTabWhatsThis (index : int, text : string) : void;
    function tabBar () : QTabBar;
    function tabIcon (index : int) : QIcon;
    function tabInserted (index : int) : void;
    function tabRemoved (index : int) : void;
    function tabText (index : int) : string;
    function tabToolTip (index : int) : string;
    function tabWhatsThis (index : int) : string;
    function widget (index : int) : QWidget;

    // Slots
    function setCurrentWidget (widget : QWidget) : void;

    // Signals
    var currentChanged : QtJSXintSignal;
    var tabBarClicked : QtJSXintSignal;
    var tabBarDoubleClicked : QtJSXintSignal;
    var tabCloseRequested : QtJSXintSignal;

    // Instance Properties
    var tabPosition : Qt_QTabWidget_TabPosition;
    var tabShape : Qt_QTabWidget_TabShape;
    var currentIndex : int;
    var count : int;
    var iconSize : QSize;
    var elideMode : Qt_TextElideMode;
    var usesScrollButtons : boolean;
    var documentMode : boolean;
    var tabsClosable : boolean;
    var movable : boolean;
}
