/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTableView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qheaderview.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";

native class QTableView extends QAbstractItemView
{
    function constructor (parent : QWidget);

    // Methods
    function clearSpans () : void;
    function columnAt (x : int) : int;
    function columnSpan (row : int, column : int) : int;
    function columnViewportPosition (column : int) : int;
    function columnWidth (column : int) : int;
    function horizontalHeader () : QHeaderView;
    function isColumnHidden (column : int) : boolean;
    function isRowHidden (row : int) : boolean;
    function rowAt (y : int) : int;
    function rowHeight (row : int) : int;
    function rowSpan (row : int, column : int) : int;
    function rowViewportPosition (row : int) : int;
    function setColumnHidden (column : int, hide : boolean) : void;
    function setColumnWidth (column : int, width : int) : void;
    function setHorizontalHeader (header : QHeaderView) : void;
    function setRowHeight (row : int, height : int) : void;
    function setRowHidden (row : int, hide : boolean) : void;
    function setSpan (row : int, column : int, rowSpan : int, columnSpan : int) : void;
    function setVerticalHeader (header : QHeaderView) : void;
    function sortByColumn (column : int, order : Qt_SortOrder) : void;
    function verticalHeader () : QHeaderView;

    // Slots
    function columnCountChanged (oldCount : int, newCount : int) : void;
    function columnMoved (column : int, oldIndex : int, newIndex : int) : void;
    function columnResized (column : int, oldWidth : int, newWidth : int) : void;
    function hideColumn (column : int) : void;
    function hideRow (row : int) : void;
    function resizeColumnToContents (column : int) : void;
    function resizeColumnsToContents () : void;
    function resizeRowToContents (row : int) : void;
    function resizeRowsToContents () : void;
    function rowCountChanged (oldCount : int, newCount : int) : void;
    function rowMoved (row : int, oldIndex : int, newIndex : int) : void;
    function rowResized (row : int, oldHeight : int, newHeight : int) : void;
    function selectColumn (column : int) : void;
    function selectRow (row : int) : void;
    function showColumn (column : int) : void;
    function showRow (row : int) : void;

    // Instance Properties
    var showGrid : boolean;
    var gridStyle : Qt_PenStyle;
    var sortingEnabled : boolean;
    var wordWrap : boolean;
    var cornerButtonEnabled : boolean;
}
