/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTableWidgetSelectionRange class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QTableWidgetSelectionRange
{
    function constructor ();
    function constructor (other : QTableWidgetSelectionRange);
    function constructor (top : int, left : int, bottom : int, right : int);

    // Methods
    function bottomRow () : int;
    function columnCount () : int;
    function leftColumn () : int;
    function rightColumn () : int;
    function rowCount () : int;
    function topRow () : int;
}
