/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextFrame class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextcursor.jsx";
import "qt/qtextdocument.jsx";
import "qt/qtextframeformat.jsx";
import "qt/qtextobject.jsx";

native class QTextFrame extends QTextObject
{
    function constructor (doc : QTextDocument);

    // Methods
    function childFrames () : QTextFrame[];
    function firstCursorPosition () : QTextCursor;
    function firstPosition () : int;
    function frameFormat () : QTextFrameFormat;
    function lastCursorPosition () : QTextCursor;
    function lastPosition () : int;
    function parentFrame () : QTextFrame;
    function setFrameFormat (format : QTextFrameFormat) : void;
}
