/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextFrameFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qtextformat.jsx";
import "qt/qtextlength.jsx";

final native class Qt_QTextFrameFormat_BorderStyle {}

final native class Qt_QTextFrameFormat_Position {}

native class QTextFrameFormat extends QTextFormat
{
    function constructor ();

    static const BorderStyle_None : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Dotted : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Dashed : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Solid : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Double : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_DotDash : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_DotDotDash : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Groove : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Ridge : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Inset : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Outset : Qt_QTextFrameFormat_BorderStyle;
    static function BorderStyle(value : Qt_QTextFrameFormat_BorderStyle) : Qt_QTextFrameFormat_BorderStyle;

    static const InFlow : Qt_QTextFrameFormat_Position;
    static const FloatLeft : Qt_QTextFrameFormat_Position;
    static const FloatRight : Qt_QTextFrameFormat_Position;
    static function Position(value : Qt_QTextFrameFormat_Position) : Qt_QTextFrameFormat_Position;

    // Methods
    function border () : number;
    function borderBrush () : QBrush;
    function borderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function bottomMargin () : number;
    function height () : QTextLength;
    function leftMargin () : number;
    function margin () : number;
    function padding () : number;
    function pageBreakPolicy () : Qt_QTextFormat_PageBreakFlags;
    function position () : Qt_QTextFrameFormat_Position;
    function rightMargin () : number;
    function setBorder (border : number) : void;
    function setBorderBrush (brush : QBrush) : void;
    function setBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setBottomMargin (margin : number) : void;
    function setHeight (height : QTextLength) : void;
    function setHeight (height : number) : void;
    function setLeftMargin (margin : number) : void;
    function setMargin (margin : number) : void;
    function setPadding (padding : number) : void;
    function setPageBreakPolicy (flags : Qt_QTextFormat_PageBreakFlags) : void;
    function setPosition (f : Qt_QTextFrameFormat_Position) : void;
    function setRightMargin (margin : number) : void;
    function setTopMargin (margin : number) : void;
    function setWidth (length : QTextLength) : void;
    function setWidth (width : number) : void;
    function topMargin () : number;
    function width () : QTextLength;
}
