/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextFragment class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextcharformat.jsx";

native class QTextFragment
{
    function constructor ();
    function constructor (o : QTextFragment);

    // Methods
    function charFormat () : QTextCharFormat;
    function charFormatIndex () : int;
    function contains (position : int) : boolean;
    function isValid () : boolean;
    function length () : int;
    function operator_equal (o : QTextFragment) : boolean;
    function operator_less (o : QTextFragment) : boolean;
    function position () : int;
    function text () : string;
}
