/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextDocumentWriter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qiodevice.jsx";
import "qt/qtextcodec.jsx";
import "qt/qtextdocument.jsx";
import "qt/qtextdocumentfragment.jsx";

native class QTextDocumentWriter
{
    function constructor ();
    function constructor (device : QIODevice, format : QByteArray);
    function constructor (fileName : string, format : QByteArray);

    // Static Members
    static function supportedDocumentFormats () : QByteArray[];

    // Methods
    function codec () : QTextCodec;
    function device () : QIODevice;
    function fileName () : string;
    function format () : QByteArray;
    function setCodec (codec : QTextCodec) : void;
    function setDevice (device : QIODevice) : void;
    function setFileName (fileName : string) : void;
    function setFormat (format : QByteArray) : void;
    function write (document : QTextDocument) : boolean;
    function write (fragment : QTextDocumentFragment) : boolean;
}
