/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextList class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextblock.jsx";
import "qt/qtextblockgroup.jsx";
import "qt/qtextdocument.jsx";
import "qt/qtextlistformat.jsx";

native class QTextList extends QTextBlockGroup
{
    function constructor (doc : QTextDocument);

    // Methods
    function add (block : QTextBlock) : void;
    function count () : int;
    function item (i : int) : QTextBlock;
    function itemNumber (arg__1 : QTextBlock) : int;
    function itemText (arg__1 : QTextBlock) : string;
    function remove (arg__1 : QTextBlock) : void;
    function removeItem (i : int) : void;
    function setFormat (format : QTextListFormat) : void;
    function textListFormat () : QTextListFormat;
}
