/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextImageFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextcharformat.jsx";

native class QTextImageFormat extends QTextCharFormat
{
    function constructor ();

    // Methods
    function height () : number;
    function name () : string;
    function setHeight (height : number) : void;
    function setName (name : string) : void;
    function setWidth (width : number) : void;
    function width () : number;
}
