/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextBlockFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qt.jsx";
import "qt/qtextformat.jsx";

final native class Qt_QTextBlockFormat_LineHeightTypes {}

native class QTextBlockFormat extends QTextFormat
{
    function constructor ();

    static const SingleHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const ProportionalHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const FixedHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const MinimumHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const LineDistanceHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static function LineHeightTypes(value : Qt_QTextBlockFormat_LineHeightTypes) : Qt_QTextBlockFormat_LineHeightTypes;

    // Methods
    function alignment () : Qt_Alignment;
    function bottomMargin () : number;
    function indent () : int;
    function leftMargin () : number;
    function lineHeight () : number;
    function lineHeight (scriptLineHeight : number, scaling : number) : number;
    function lineHeightType () : int;
    function nonBreakableLines () : boolean;
    function pageBreakPolicy () : Qt_QTextFormat_PageBreakFlags;
    function rightMargin () : number;
    function setAlignment (alignment : Qt_Alignment) : void;
    function setBottomMargin (margin : number) : void;
    function setIndent (indent : int) : void;
    function setLeftMargin (margin : number) : void;
    function setLineHeight (height : number, heightType : int) : void;
    function setNonBreakableLines (b : boolean) : void;
    function setPageBreakPolicy (flags : Qt_QTextFormat_PageBreakFlags) : void;
    function setRightMargin (margin : number) : void;
    function setTextIndent (aindent : number) : void;
    function setTopMargin (margin : number) : void;
    function textIndent () : number;
    function topMargin () : number;
}
