/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextBlock class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qt.jsx";
import "qt/qtextblockformat.jsx";
import "qt/qtextblockuserdata.jsx";
import "qt/qtextcharformat.jsx";
import "qt/qtextdocument.jsx";
import "qt/qtextlayout.jsx";
import "qt/qtextlist.jsx";

native class QTextBlock
{
    function constructor ();
    function constructor (o : QTextBlock);

    // Methods
    function blockFormat () : QTextBlockFormat;
    function blockFormatIndex () : int;
    function blockNumber () : int;
    function charFormat () : QTextCharFormat;
    function charFormatIndex () : int;
    function clearLayout () : void;
    function contains (position : int) : boolean;
    function document () : QTextDocument;
    function firstLineNumber () : int;
    function fragmentIndex () : int;
    function isValid () : boolean;
    function isVisible () : boolean;
    function layout () : QTextLayout;
    function length () : int;
    function lineCount () : int;
    function next () : QTextBlock;
    function operator_equal (o : QTextBlock) : boolean;
    function operator_less (o : QTextBlock) : boolean;
    function position () : int;
    function previous () : QTextBlock;
    function revision () : int;
    function setLineCount (count : int) : void;
    function setRevision (rev : int) : void;
    function setUserData (data : QTextBlockUserData) : void;
    function setUserState (state : int) : void;
    function setVisible (visible : boolean) : void;
    function text () : string;
    function textDirection () : Qt_LayoutDirection;
    function textList () : QTextList;
    function userData () : QTextBlockUserData;
    function userState () : int;
}
