/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTileRules class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qt.jsx";

native class QTileRules
{
    function constructor (horizontalRule : Qt_TileRule, verticalRule : Qt_TileRule);
    function constructor (rule : Qt_TileRule);
}
