/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTimeEdit class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdatetimeedit.jsx";
import "qt/qtime.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QTimeEdit extends QDateTimeEdit
{
    function constructor (parent : QWidget);
    function constructor (time : QTime, parent : QWidget);

    // Signals
    var userTimeChanged : QtJSXQTimeSignal;

    // Instance Properties
    var time : QTime;
}
