/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QToolBarChangeEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";

native class QToolBarChangeEvent extends QEvent
{
    function constructor (t : boolean);

    // Methods
    function toggle () : boolean;
}
