/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QToolTip class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qfont.jsx";
import "qt/qpalette.jsx";
import "qt/qpoint.jsx";
import "qt/qwidget.jsx";

native class QToolTip
{

    // Static Members
    static function font () : QFont;
    static function hideText () : void;
    static function isVisible () : boolean;
    static function palette () : QPalette;
    static function setFont (arg__1 : QFont) : void;
    static function setPalette (arg__1 : QPalette) : void;
    static function showText (pos : QPoint, text : string, w : QWidget) : void;
    static function text () : string;
}
