/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTouchEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qinputevent.jsx";
import "qt/qobject.jsx";
import "qt/qt.jsx";
import "qt/qtouchevent_touchpoint.jsx";

native class QTouchEvent extends QInputEvent
{

    // Methods
    function setTarget (atarget : QObject) : void;
    function setTouchPointStates (aTouchPointStates : Qt_TouchPointStates) : void;
    function setTouchPoints (atouchPoints : QTouchEvent_TouchPoint[]) : void;
    function target () : QObject;
    function touchPointStates () : Qt_TouchPointStates;
    function touchPoints () : QTouchEvent_TouchPoint[];
}
