/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTreeView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qheaderview.jsx";
import "qt/qmodelindex.jsx";
import "qt/qpainter.jsx";
import "qt/qrect.jsx";
import "qt/qregion.jsx";
import "qt/qstyleoptionviewitem.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QTreeView extends QAbstractItemView
{
    function constructor (parent : QWidget);

    // Methods
    function columnAt (x : int) : int;
    function columnViewportPosition (column : int) : int;
    function columnWidth (column : int) : int;
    function drawBranches (painter : QPainter, rect : QRect, index : QModelIndex) : void;
    function drawRow (painter : QPainter, options : QStyleOptionViewItem, index : QModelIndex) : void;
    function drawTree (painter : QPainter, region : QRegion) : void;
    function header () : QHeaderView;
    function indexAbove (index : QModelIndex) : QModelIndex;
    function indexBelow (index : QModelIndex) : QModelIndex;
    function indexRowSizeHint (index : QModelIndex) : int;
    function isColumnHidden (column : int) : boolean;
    function isExpanded (index : QModelIndex) : boolean;
    function isFirstColumnSpanned (row : int, parent : QModelIndex) : boolean;
    function isRowHidden (row : int, parent : QModelIndex) : boolean;
    function rowHeight (index : QModelIndex) : int;
    function setColumnHidden (column : int, hide : boolean) : void;
    function setColumnWidth (column : int, width : int) : void;
    function setExpanded (index : QModelIndex, expand : boolean) : void;
    function setFirstColumnSpanned (row : int, parent : QModelIndex, span : boolean) : void;
    function setHeader (header : QHeaderView) : void;
    function setRowHidden (row : int, parent : QModelIndex, hide : boolean) : void;
    function setTreePosition (logicalIndex : int) : void;
    function sortByColumn (column : int, order : Qt_SortOrder) : void;
    function treePosition () : int;

    // Slots
    function collapse (index : QModelIndex) : void;
    function collapseAll () : void;
    function columnCountChanged (oldCount : int, newCount : int) : void;
    function columnMoved () : void;
    function columnResized (column : int, oldSize : int, newSize : int) : void;
    function expand (index : QModelIndex) : void;
    function expandAll () : void;
    function expandToDepth (depth : int) : void;
    function hideColumn (column : int) : void;
    function reexpand () : void;
    function resizeColumnToContents (column : int) : void;
    function rowsRemoved (parent : QModelIndex, first : int, last : int) : void;
    function showColumn (column : int) : void;

    // Signals
    var collapsed : QtJSXQModelIndexSignal;
    var expanded : QtJSXQModelIndexSignal;

    // Instance Properties
    var autoExpandDelay : int;
    var indentation : int;
    var rootIsDecorated : boolean;
    var uniformRowHeights : boolean;
    var itemsExpandable : boolean;
    var sortingEnabled : boolean;
    var animated : boolean;
    var allColumnsShowFocus : boolean;
    var wordWrap : boolean;
    var headerHidden : boolean;
    var expandsOnDoubleClick : boolean;
}
