/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTreeWidgetItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qfont.jsx";
import "qt/qicon.jsx";
import "qt/qsize.jsx";
import "qt/qt.jsx";
import "qt/qtreewidget.jsx";

final native class Qt_QTreeWidgetItem_ChildIndicatorPolicy {}

final native class Qt_QTreeWidgetItem_ItemType {}

native class QTreeWidgetItem
{
    function constructor (view : QTreeWidget, after : QTreeWidgetItem, type : int);
    function constructor (view : QTreeWidget, strings : string[], type : int);
    function constructor (view : QTreeWidget, type : int);
    function constructor (parent : QTreeWidgetItem, after : QTreeWidgetItem, type : int);
    function constructor (parent : QTreeWidgetItem, strings : string[], type : int);
    function constructor (parent : QTreeWidgetItem, type : int);
    function constructor (strings : string[], type : int);
    function constructor (type : int);

    static const ShowIndicator : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    static const DontShowIndicator : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    static const DontShowIndicatorWhenChildless : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    static function ChildIndicatorPolicy(value : Qt_QTreeWidgetItem_ChildIndicatorPolicy) : Qt_QTreeWidgetItem_ChildIndicatorPolicy;

    static const Type : Qt_QTreeWidgetItem_ItemType;
    static const UserType : Qt_QTreeWidgetItem_ItemType;
    static function ItemType(value : Qt_QTreeWidgetItem_ItemType) : Qt_QTreeWidgetItem_ItemType;

    // Methods
    function addChild (child : QTreeWidgetItem) : void;
    function addChildren (children : QTreeWidgetItem[]) : void;
    function background (column : int) : QBrush;
    function checkState (column : int) : Qt_CheckState;
    function child (index : int) : QTreeWidgetItem;
    function childCount () : int;
    function childIndicatorPolicy () : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    function clone () : QTreeWidgetItem;
    function columnCount () : int;
    function data (column : int, role : int) : variant;
    function emitDataChanged () : void;
    function flags () : Qt_ItemFlags;
    function font (column : int) : QFont;
    function foreground (column : int) : QBrush;
    function icon (column : int) : QIcon;
    function indexOfChild (child : QTreeWidgetItem) : int;
    function insertChild (index : int, child : QTreeWidgetItem) : void;
    function insertChildren (index : int, children : QTreeWidgetItem[]) : void;
    function isDisabled () : boolean;
    function isExpanded () : boolean;
    function isFirstColumnSpanned () : boolean;
    function isHidden () : boolean;
    function isSelected () : boolean;
    function parent () : QTreeWidgetItem;
    function removeChild (child : QTreeWidgetItem) : void;
    function setBackground (column : int, brush : QBrush) : void;
    function setCheckState (column : int, state : Qt_CheckState) : void;
    function setChildIndicatorPolicy (policy : Qt_QTreeWidgetItem_ChildIndicatorPolicy) : void;
    function setData (column : int, role : int, value : variant) : void;
    function setDisabled (disabled : boolean) : void;
    function setExpanded (expand : boolean) : void;
    function setFirstColumnSpanned (span : boolean) : void;
    function setFlags (flags : Qt_ItemFlags) : void;
    function setFont (column : int, font : QFont) : void;
    function setForeground (column : int, brush : QBrush) : void;
    function setHidden (hide : boolean) : void;
    function setIcon (column : int, icon : QIcon) : void;
    function setSelected (select : boolean) : void;
    function setSizeHint (column : int, size : QSize) : void;
    function setStatusTip (column : int, statusTip : string) : void;
    function setText (column : int, text : string) : void;
    function setTextAlignment (column : int, alignment : int) : void;
    function setToolTip (column : int, toolTip : string) : void;
    function setWhatsThis (column : int, whatsThis : string) : void;
    function sortChildren (column : int, order : Qt_SortOrder) : void;
    function statusTip (column : int) : string;
    function takeChild (index : int) : QTreeWidgetItem;
    function takeChildren () : QTreeWidgetItem[];
    function text (column : int) : string;
    function textAlignment (column : int) : int;
    function toolTip (column : int) : string;
    function treeWidget () : QTreeWidget;
    function type () : int;
    function whatsThis (column : int) : string;
}
