/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUiLoader class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qactiongroup.jsx";
import "qt/qdir.jsx";
import "qt/qiodevice.jsx";
import "qt/qlayout.jsx";
import "qt/qobject.jsx";
import "qt/qwidget.jsx";

native class QUiLoader extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function addPluginPath (path : string) : void;
    function availableLayouts () : string[];
    function availableWidgets () : string[];
    function clearPluginPaths () : void;
    function createAction (parent : QObject, name : string) : QAction;
    function createActionGroup (parent : QObject, name : string) : QActionGroup;
    function createLayout (className : string, parent : QObject, name : string) : QLayout;
    function createWidget (className : string, parent : QWidget, name : string) : QWidget;
    function errorString () : string;
    function isLanguageChangeEnabled () : boolean;
    function isTranslationEnabled () : boolean;
    function load (device : QIODevice, parentWidget : QWidget) : QWidget;
    function pluginPaths () : string[];
    function setLanguageChangeEnabled (enabled : boolean) : void;
    function setTranslationEnabled (enabled : boolean) : void;
    function setWorkingDirectory (dir : QDir) : void;
    function workingDirectory () : QDir;
}
