/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QVBoxLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qboxlayout.jsx";
import "qt/qwidget.jsx";

native class QVBoxLayout extends QBoxLayout
{
    function constructor ();
    function constructor (parent : QWidget);
}
