/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QVector3D class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qvector2d.jsx";
import "qt/qvector4d.jsx";

native class QVector3D
{
    function constructor ();
    function constructor (point : QPoint);
    function constructor (point : QPointF);
    function constructor (vector : QVector2D);
    function constructor (vector : QVector2D, zpos : number);
    function constructor (vector : QVector4D);
    function constructor (xpos : number, ypos : number, zpos : number);

    // Static Members
    static function crossProduct (v1 : QVector3D, v2 : QVector3D) : QVector3D;
    static function dotProduct (v1 : QVector3D, v2 : QVector3D) : number;
    static function normal (v1 : QVector3D, v2 : QVector3D) : QVector3D;

    // Methods
    function distanceToLine (point : QVector3D, direction : QVector3D) : number;
    function distanceToPlane (plane : QVector3D, normal : QVector3D) : number;
    function distanceToPlane (plane1 : QVector3D, plane2 : QVector3D, plane3 : QVector3D) : number;
    function distanceToPoint (point : QVector3D) : number;
    function isNull () : boolean;
    function length () : number;
    function lengthSquared () : number;
    function normalize () : void;
    function normalized () : QVector3D;
    function operator_add_assign (vector : QVector3D) : QVector3D;
    function operator_divide_assign (divisor : number) : QVector3D;
    function operator_equal (v2 : QVector3D) : boolean;
    function operator_multiply_assign (vector : QVector3D) : QVector3D;
    function operator_multiply_assign (factor : number) : QVector3D;
    function operator_subscript (i : int) : number;
    function operator_subtract_assign (vector : QVector3D) : QVector3D;
    function setX (x : number) : void;
    function setY (y : number) : void;
    function setZ (z : number) : void;
    function toPoint () : QPoint;
    function toPointF () : QPointF;
    function toVector2D () : QVector2D;
    function toVector4D () : QVector4D;
    function x () : number;
    function y () : number;
    function z () : number;
}
