/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWebPage_ChooseMultipleFilesExtensionReturn class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwebpage_extensionreturn.jsx";

native class QWebPage_ChooseMultipleFilesExtensionReturn extends QWebPage_ExtensionReturn
{
    function constructor ();
}
