/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWebHitTestResult class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpixmap.jsx";
import "qt/qpoint.jsx";
import "qt/qrect.jsx";
import "qt/qurl.jsx";
import "qt/qwebelement.jsx";
import "qt/qwebframe.jsx";

native class QWebHitTestResult
{
    function constructor ();
    function constructor (other : QWebHitTestResult);

    // Methods
    function alternateText () : string;
    function boundingRect () : QRect;
    function element () : QWebElement;
    function enclosingBlockElement () : QWebElement;
    function frame () : QWebFrame;
    function imageUrl () : QUrl;
    function isContentEditable () : boolean;
    function isContentSelected () : boolean;
    function isNull () : boolean;
    function linkElement () : QWebElement;
    function linkTargetFrame () : QWebFrame;
    function linkText () : string;
    function linkTitle () : QUrl;
    function linkUrl () : QUrl;
    function mediaUrl () : QUrl;
    function pixmap () : QPixmap;
    function pos () : QPoint;
    function title () : string;
}
