/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWebInspector class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwebpage.jsx";
import "qt/qwidget.jsx";

native class QWebInspector extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function page () : QWebPage;
    function setPage (page : QWebPage) : void;
}
