/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWebSettings class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qicon.jsx";
import "qt/qpixmap.jsx";
import "qt/qurl.jsx";

final native class Qt_QWebSettings_WebGraphic {}

final native class Qt_QWebSettings_FontSize {}

final native class Qt_QWebSettings_FontFamily {}

final native class Qt_QWebSettings_WebAttribute {}

native class QWebSettings
{

    // Static Members
    static function clearIconDatabase () : void;
    static function clearMemoryCaches () : void;
    static function enablePersistentStorage (path : string) : void;
    static function globalSettings () : QWebSettings;
    static function iconDatabasePath () : string;
    static function iconForUrl (url : QUrl) : QIcon;
    static function maximumPagesInCache () : int;
    static function offlineStorageDefaultQuota () : number;
    static function offlineStoragePath () : string;
    static function offlineWebApplicationCachePath () : string;
    static function offlineWebApplicationCacheQuota () : number;
    static function setIconDatabasePath (location : string) : void;
    static function setMaximumPagesInCache (pages : int) : void;
    static function setObjectCacheCapacities (cacheMinDeadCapacity : int, cacheMaxDead : int, totalCapacity : int) : void;
    static function setOfflineStorageDefaultQuota (maximumSize : number) : void;
    static function setOfflineStoragePath (path : string) : void;
    static function setOfflineWebApplicationCachePath (path : string) : void;
    static function setOfflineWebApplicationCacheQuota (maximumSize : number) : void;
    static function setWebGraphic (type : Qt_QWebSettings_WebGraphic, graphic : QPixmap) : void;
    static function webGraphic (type : Qt_QWebSettings_WebGraphic) : QPixmap;

    static const MissingImageGraphic : Qt_QWebSettings_WebGraphic;
    static const MissingPluginGraphic : Qt_QWebSettings_WebGraphic;
    static const DefaultFrameIconGraphic : Qt_QWebSettings_WebGraphic;
    static const TextAreaSizeGripCornerGraphic : Qt_QWebSettings_WebGraphic;
    static const DeleteButtonGraphic : Qt_QWebSettings_WebGraphic;
    static const InputSpeechButtonGraphic : Qt_QWebSettings_WebGraphic;
    static const SearchCancelButtonGraphic : Qt_QWebSettings_WebGraphic;
    static const SearchCancelButtonPressedGraphic : Qt_QWebSettings_WebGraphic;
    static function WebGraphic(value : Qt_QWebSettings_WebGraphic) : Qt_QWebSettings_WebGraphic;

    static const MinimumFontSize : Qt_QWebSettings_FontSize;
    static const MinimumLogicalFontSize : Qt_QWebSettings_FontSize;
    static const DefaultFontSize : Qt_QWebSettings_FontSize;
    static const DefaultFixedFontSize : Qt_QWebSettings_FontSize;
    static function FontSize(value : Qt_QWebSettings_FontSize) : Qt_QWebSettings_FontSize;

    static const StandardFont : Qt_QWebSettings_FontFamily;
    static const FixedFont : Qt_QWebSettings_FontFamily;
    static const SerifFont : Qt_QWebSettings_FontFamily;
    static const SansSerifFont : Qt_QWebSettings_FontFamily;
    static const CursiveFont : Qt_QWebSettings_FontFamily;
    static const FantasyFont : Qt_QWebSettings_FontFamily;
    static function FontFamily(value : Qt_QWebSettings_FontFamily) : Qt_QWebSettings_FontFamily;

    static const AutoLoadImages : Qt_QWebSettings_WebAttribute;
    static const JavascriptEnabled : Qt_QWebSettings_WebAttribute;
    static const JavaEnabled : Qt_QWebSettings_WebAttribute;
    static const PluginsEnabled : Qt_QWebSettings_WebAttribute;
    static const PrivateBrowsingEnabled : Qt_QWebSettings_WebAttribute;
    static const JavascriptCanOpenWindows : Qt_QWebSettings_WebAttribute;
    static const JavascriptCanAccessClipboard : Qt_QWebSettings_WebAttribute;
    static const DeveloperExtrasEnabled : Qt_QWebSettings_WebAttribute;
    static const LinksIncludedInFocusChain : Qt_QWebSettings_WebAttribute;
    static const ZoomTextOnly : Qt_QWebSettings_WebAttribute;
    static const PrintElementBackgrounds : Qt_QWebSettings_WebAttribute;
    static const OfflineStorageDatabaseEnabled : Qt_QWebSettings_WebAttribute;
    static const OfflineWebApplicationCacheEnabled : Qt_QWebSettings_WebAttribute;
    static const LocalStorageEnabled : Qt_QWebSettings_WebAttribute;
    static const LocalContentCanAccessRemoteUrls : Qt_QWebSettings_WebAttribute;
    static const DnsPrefetchEnabled : Qt_QWebSettings_WebAttribute;
    static const XSSAuditingEnabled : Qt_QWebSettings_WebAttribute;
    static const AcceleratedCompositingEnabled : Qt_QWebSettings_WebAttribute;
    static const SpatialNavigationEnabled : Qt_QWebSettings_WebAttribute;
    static const LocalContentCanAccessFileUrls : Qt_QWebSettings_WebAttribute;
    static const TiledBackingStoreEnabled : Qt_QWebSettings_WebAttribute;
    static const FrameFlatteningEnabled : Qt_QWebSettings_WebAttribute;
    static const SiteSpecificQuirksEnabled : Qt_QWebSettings_WebAttribute;
    static const JavascriptCanCloseWindows : Qt_QWebSettings_WebAttribute;
    static const WebGLEnabled : Qt_QWebSettings_WebAttribute;
    static const CSSRegionsEnabled : Qt_QWebSettings_WebAttribute;
    static const HyperlinkAuditingEnabled : Qt_QWebSettings_WebAttribute;
    static const CSSGridLayoutEnabled : Qt_QWebSettings_WebAttribute;
    static const ScrollAnimatorEnabled : Qt_QWebSettings_WebAttribute;
    static const CaretBrowsingEnabled : Qt_QWebSettings_WebAttribute;
    static const NotificationsEnabled : Qt_QWebSettings_WebAttribute;
    static const WebAudioEnabled : Qt_QWebSettings_WebAttribute;
    static function WebAttribute(value : Qt_QWebSettings_WebAttribute) : Qt_QWebSettings_WebAttribute;

    // Methods
    function cssMediaType () : string;
    function defaultTextEncoding () : string;
    function fontFamily (which : Qt_QWebSettings_FontFamily) : string;
    function fontSize (type : Qt_QWebSettings_FontSize) : int;
    function localStoragePath () : string;
    function resetAttribute (attr : Qt_QWebSettings_WebAttribute) : void;
    function resetFontFamily (which : Qt_QWebSettings_FontFamily) : void;
    function resetFontSize (type : Qt_QWebSettings_FontSize) : void;
    function setAttribute (attr : Qt_QWebSettings_WebAttribute, on : boolean) : void;
    function setCSSMediaType (arg__1 : string) : void;
    function setDefaultTextEncoding (encoding : string) : void;
    function setFontFamily (which : Qt_QWebSettings_FontFamily, family : string) : void;
    function setFontSize (type : Qt_QWebSettings_FontSize, size : int) : void;
    function setLocalStoragePath (path : string) : void;
    function setUserStyleSheetUrl (location : QUrl) : void;
    function testAttribute (attr : Qt_QWebSettings_WebAttribute) : boolean;
    function userStyleSheetUrl () : QUrl;
}
