/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWebPluginFactory_ExtensionOption class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QWebPluginFactory_ExtensionOption
{
    function constructor ();
}
