/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWhatsThisClickedEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";

native class QWhatsThisClickedEvent extends QEvent
{
    function constructor (href : string);

    // Methods
    function href () : string;
}
