/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlDeclHandler class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlDeclHandler
{
    function constructor ();

    // Methods
    function attributeDecl (eName : string, aName : string, type : string, valueDefault : string, value : string) : boolean;
    function errorString () : string;
    function externalEntityDecl (name : string, publicId : string, systemId : string) : boolean;
    function internalEntityDecl (name : string, value : string) : boolean;
}
