/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlLocator class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlLocator
{
    function constructor ();

    // Methods
    function columnNumber () : int;
    function lineNumber () : int;
}
