/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlStreamNotationDeclaration class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlStreamNotationDeclaration
{
    function constructor ();
    function constructor (arg__1 : QXmlStreamNotationDeclaration);

    // Methods
    function name () : string;
    function operator_equal (other : QXmlStreamNotationDeclaration) : boolean;
    function publicId () : string;
    function systemId () : string;
}
