/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlDTDHandler class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlDTDHandler
{
    function constructor ();

    // Methods
    function errorString () : string;
    function notationDecl (name : string, publicId : string, systemId : string) : boolean;
    function unparsedEntityDecl (name : string, publicId : string, systemId : string, notationName : string) : boolean;
}
