/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlDefaultHandler class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qxmlcontenthandler.jsx";

native class QXmlDefaultHandler extends QXmlContentHandler
{
    function constructor ();
}
