/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlStreamEntityResolver class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlStreamEntityResolver
{
    function constructor ();

    // Methods
    function resolveEntity (publicId : string, systemId : string) : string;
    function resolveUndeclaredEntity (name : string) : string;
}
