/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlNamePool class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlNamePool
{
    function constructor ();
    function constructor (other : QXmlNamePool);
}
