/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlContentHandler class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qxmlattributes.jsx";
import "qt/qxmllocator.jsx";

native class QXmlContentHandler
{
    function constructor ();

    // Methods
    function characters (ch : string) : boolean;
    function endDocument () : boolean;
    function endElement (namespaceURI : string, localName : string, qName : string) : boolean;
    function endPrefixMapping (prefix : string) : boolean;
    function errorString () : string;
    function ignorableWhitespace (ch : string) : boolean;
    function processingInstruction (target : string, data : string) : boolean;
    function setDocumentLocator (locator : QXmlLocator) : void;
    function skippedEntity (name : string) : boolean;
    function startDocument () : boolean;
    function startElement (namespaceURI : string, localName : string, qName : string, atts : QXmlAttributes) : boolean;
    function startPrefixMapping (prefix : string, uri : string) : boolean;
}
