/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlLexicalHandler class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlLexicalHandler
{
    function constructor ();

    // Methods
    function comment (ch : string) : boolean;
    function endCDATA () : boolean;
    function endDTD () : boolean;
    function endEntity (name : string) : boolean;
    function errorString () : string;
    function startCDATA () : boolean;
    function startDTD (name : string, publicId : string, systemId : string) : boolean;
    function startEntity (name : string) : boolean;
}
