/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlNodeModelIndex class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractxmlnodemodel.jsx";

final native class Qt_QXmlNodeModelIndex_DocumentOrder {}

final native class Qt_QXmlNodeModelIndex_NodeKind {}

native class QXmlNodeModelIndex
{
    function constructor ();
    function constructor (other : QXmlNodeModelIndex);

    static const Precedes : Qt_QXmlNodeModelIndex_DocumentOrder;
    static const Is : Qt_QXmlNodeModelIndex_DocumentOrder;
    static const Follows : Qt_QXmlNodeModelIndex_DocumentOrder;
    static function DocumentOrder(value : Qt_QXmlNodeModelIndex_DocumentOrder) : Qt_QXmlNodeModelIndex_DocumentOrder;

    static const Attribute : Qt_QXmlNodeModelIndex_NodeKind;
    static const Comment : Qt_QXmlNodeModelIndex_NodeKind;
    static const Document : Qt_QXmlNodeModelIndex_NodeKind;
    static const Element : Qt_QXmlNodeModelIndex_NodeKind;
    static const Namespace : Qt_QXmlNodeModelIndex_NodeKind;
    static const ProcessingInstruction : Qt_QXmlNodeModelIndex_NodeKind;
    static const Text : Qt_QXmlNodeModelIndex_NodeKind;
    static function NodeKind(value : Qt_QXmlNodeModelIndex_NodeKind) : Qt_QXmlNodeModelIndex_NodeKind;

    // Methods
    function additionalData () : number;
    function data () : number;
    function isNull () : boolean;
    function model () : QAbstractXmlNodeModel;
    function operator_equal (other : QXmlNodeModelIndex) : boolean;
}
