/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXML Stream Objects
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qxmlstreamattribute.jsx";
import "qt/qxmlstreamattributes.jsx";
import "qt/qxmlstreamentityresolver.jsx";
import "qt/qxmlstreamreader.jsx";
import "qt/qxmlstreamentitydeclaration.jsx";
import "qt/qxmlstreamnamespacedeclaration.jsx";
import "qt/qxmlstreamnotationdeclaration.jsx";
