/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlInputSource class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qiodevice.jsx";

native class QXmlInputSource
{
    function constructor ();
    function constructor (dev : QIODevice);

    // Methods
    function data () : string;
    function fetchData () : void;
    function fromRawData (data : QByteArray, beginning : boolean) : string;
    function next () : string;
    function reset () : void;
    function setData (dat : QByteArray) : void;
    function setData (dat : string) : void;
}
