/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlErrorHandler class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qxmlparseexception.jsx";

native class QXmlErrorHandler
{
    function constructor ();

    // Methods
    function error (exception : QXmlParseException) : boolean;
    function errorString () : string;
    function fatalError (exception : QXmlParseException) : boolean;
    function warning (exception : QXmlParseException) : boolean;
}
